### ISSUE TITLE
Use of "self" prevents late-static binding

### ISSUE THREAD

**Issue by judgej** [moneyphp/money#161]
This is my use-case: I am writing a simple adapter by extending the `Money` class and then adding a few extra methods.

Taking my extended class to be `MyMoney`, I then try to create an instance:

    $myMoney = MyMoney::GBP(999);

The problem is, this returns an instance of `Money\Money` and not `MyMoney`. The use of `self` when creating new instances is what enforces this. If `static` were used instead, then an instance of my extended class would be created instead (this being late static binding).

I realise I could write an adapter that took an injected instance of `Money\Money` instead, and might still do that, but thought I would raise this issue anyway, just in case it is something overlooked rather than a deliberate decision (you may have good reasons for doing it this way).

**Comment by judgej** [comment]
I can still do this now and get the correct class:

    $amount = new MyMoney(999, new \Money\Currency('GBP'));

but this gives me a different class:

    $amount = MyMoney::GBP(999);

**Comment by judgej** [comment]
Here is my adapter:

https://github.com/academe/SagePay-Integration/blob/master/src/Money/Money.php

It is very simple, and can be used as an alternative to the built-in `Amount` class here:

https://github.com/academe/SagePay-Integration/blob/master/src/Money/Amount.php

since they both share the same interface.

**Comment by judgej** [comment]
This is kind of how I see it working for OmniPay: if someone wants to write a built-in money handler, then great, but so long as it is class that has an interface that OmniPay expeacts, then any third-party package can be used instead. We don't have to argue about which one, since they can all be supported through an adapter.

**Comment by frederikbosch** [comment]
@judgej `Money` 3.0 is [final](http://verraes.net/2014/05/final-classes-in-php/). So you cannot extend it any more. This removes the need for late static binding.

**Comment by frederikbosch** [comment]
@judgej If you want to build a bridge (for Omnipay or else) you use composition rather than inheritance.

```php
<?php
use Money\Money;

class MoneyOmnipayBridge implements AmountInterface {

private $amount;

public function __construct (Money $money) {
  $this->amount = $money;
}

public function getAmount() {
  return $this->amount->getAmount();
}


public function getCurrencyCode() {
  return $this->amount->getCurrency()->getCode();
}

}

**Comment by sagikazarmark** [comment]
I have bad news for you then: Money class will be final as of 3.0. Although I see your use-case, I think it would be better to use encapsulation and create a wrapper around money. Adds complication, but for the sake of interface implementation I am not sure making it non-final makes sense.

**Comment by frederikbosch** [comment]
closed by comments and examples of @sagikazarmark and @frederikbosch.

**Comment by judgej** [comment]
np - I'll change it my end. My gateway is all new and experimental, so nothing there is fixed in stone yet.
