### ISSUE TITLE
Different values in two servers with same php

### ISSUE THREAD

**Issue by rastydnb** [moneyphp/money#172]
we have two server,the two servers have php 5.6.17 , one of server is mi local with nginx ,the other server is production with apache .

When use "add()" function over some moneys, get different result in two servers.

In local we get positive values and no get erros but,
in the producction server get negative values and get this error:

The first parameter of Money must be an integer. It's the amount, expressed in the smallest units of currency (eg cents)

We work with 6 decimals configured in config.yml
We need special php module, or any idea

Thanks

**Comment by frederikbosch** [comment]
@rastydnb What version of Money are you using?Can you say which server is right, which is wrong? Which extensions are on the server that is right, which are on the server that is wrong?

When you work with 6 decimals, you could overflow PHP_MAX_INT. Unlimited integer support has been added in Money 3.0. You should realize that if you want to use Money with unlimited integer calculations, you need bc math or gmp to be installed as extension.

Probably one machine has one of these extensions while the other has not. Or you are Money 1.x. Final option: there is a bug ;)

**Comment by rastydnb** [comment]
HI @frederikbosch thanks for the response. 
In the good server we have debian jessie 64bits nginx and php-fpm, and in the wrong server we have CentOS release 6.7 (Final) 32bits and apache without cgi ,the money version is 1.2.2.
The extension are the same in two servers

We think like you, and is PHP_MAX_INT where is the error

Is posible that the error was because the os is 32bits?

Thx

**Comment by frederikbosch** [comment]
@rastydnb Yes that is possible. You can check PHP_INT_MAX from cli by running.

```sh
php -r "var_dump(PHP_INT_MAX);"
```

Compare that to your amount and you know if that is the cause. Upgrading to the 3.0 alpha release of Money should fix the problem, if you have either BC Math or GMP installed as extension.

**Comment by rastydnb** [comment]
Thanks @frederikbosch

**Comment by frederikbosch** [comment]
@rastydnb Yesterday we released a beta version. Please use that instead of the alpha version. We fixed one important bug in that version.
