### ISSUE TITLE
StringToUnitsParser fails to parse zero correctly ('0', '0.00', etc.)

### ISSUE THREAD

**Issue by damonjones** [moneyphp/money#173]
Because the parse() method performs an ltrim() on $units to remove leading zeros, a zero input is reduced to an empty string which causes the Money constructor validation to fail.

**Comment by frederikbosch** [comment]
@damonjones This is already fixed, see commit 766bdc8

@sagikazarmark We should release a new version that includes this fix. Do you have time to fix the currencies issue (large repo issue)? If not, I can take that one. I think we should tag after we fixed that.
