### ISSUE TITLE
Stable 3.0 release?

### ISSUE THREAD

**Issue by danizord** [moneyphp/money#174]
I wish to use `MoneyFormatter` in my new app, but I'm not sure if 3.0-alpha is ready for production, when you plan to release stable 3.0?

**Comment by frederikbosch** [comment]
We plan to release 3.0 stable if we have finished docs. There will be no more new features in 3.0. Maybe you could give a help on the docs ;).

But, since there are a lot of new features, there will be a beta before a stable release.

**Comment by sagikazarmark** [comment]
I want to be really cautious about releasing a stable. Many other libraries rely on this one which makes it even more important to have a really stable release. We are going through the regular release states. BC breaks should not happen once we reach RC phase. That's the most I can promise at the moment.

**Comment by frederikbosch** [comment]
@sagikazarmark You want be to edit the CHANGELOG? What will be the new version?

**Comment by sagikazarmark** [comment]
Yes

**Comment by frederikbosch** [comment]
@sagikazarmark What will be the new version? Beta1 or alpha2?

**Comment by sagikazarmark** [comment]
I think we are ready for beta. But changelog first.

**Comment by frederikbosch** [comment]
Yes, but changelog contains version name in text headers. Will create it.

**Comment by frederikbosch** [comment]
@sagikazarmark Done. I think we are ready for release.

**Comment by elstamey** [comment]
I'm not sure.  Money broke us today and earlier last month.  I believe it is because of this commit:

https://github.com/moneyphp/money/commit/04490c14cbd46b117d0d13b59c9aae8beda9edb1

Money wasn't able to be a string before, and we were getting a string back instead of the integer we expected, and it's been a not-fun day.

**Comment by sagikazarmark** [comment]
Sorry for the trouble. However the next version of Money is not stable yet, nor the fundamental changes have been documented, so relying on a development version is up to you.

**Comment by elstamey** [comment]
Agreed.  We accidentally left the dev-master in production.  We have resolved that.  But when we determined the problem was related to Money, the Changelog did not give us any idea of the actual change that happened.  I believe changing the value of amount to a string is a significant change and "of note" for others who may wonder what changes are coming.

**Comment by sagikazarmark** [comment]
You are right. We will make sure to mentioned that in the changelog and the upcoming documentation. Thanks for feedback.

**Comment by elstamey** [comment]
Thank you!  :)

**Comment by frederikbosch** [comment]
Money is upgrading from 1.x to 3.x. That indicates a huge step. Kind of harsh to blame oss contributors for your bad day while you left dev-master in yourself.

**Comment by frederikbosch** [comment]
@sagikazarmark I still think we should drop PHP 5.4. If high-quality packages like this one does not make the step, how can we expect others to do it? PHP 5.4 is history and most certainly insecure. Let's be forward looking and secure. We really should require 5.5.

**Comment by sagikazarmark** [comment]
@frederikbosch IMO raising requirement "just because" does not make any sense. If we want to use any features from 5.5, then sure, go ahead and drop support for 5.4. But if there isn't any, then why make this step. I see your reasoning, but I don't see the advantage in just dropping support without any real benefit.

**Comment by frederikbosch** [comment]
@sagikazarmark Packages like `moneyphp` have a huge reach. That gives those packages a certain position in the PHP community. They should take advantage of that position by influencing the community. Force the community to take steps, accompanied with a message why those steps are required.

The position we are in now in makes it even easier. We are going to release a new major version with BC breaks. A perfect reason to stop supporting PHP versions that are insecure. Our next opportunity is 4.0.0, if we follow semantic versioning. Finally: we just released a new 1.x release. The PHP 5.4 users are perfectly served by this package.

**Comment by frederikbosch** [comment]
Alright. Final try, then I'll leave it. Suppose, just suppose, today there is a major security flow found in PHP 5.4 or lower. And internals of PHP decides not to patch it but rather advices people to upgrade to the newer versions. What would we do?

1. We would just leave it
2. We would release a new major version
3. We would release a new minor version (and do a BC break)

Remember: if people want support for PHP 5.4 or PHP 5.5 they can fork the repo, change the version number in the composer.json and they are done. Or they use version `1.x` of this package.

So I still do not get why `Money` should come with a new major version and still support probably insecure end-of-life PHP versions?

**Comment by sagikazarmark** [comment]
Yeah-yeah, I haven't forgot it. In fact, I have been thinking about this every day. :wink: 

I don't have any reasons against it after all. Also, as I can see, composer finally got the feature of overriding the platform, so not even a fork is required.

Anyway, go ahead, increase the PHP version. :smile:

**Comment by frederikbosch** [comment]
:+1:

**Comment by frederikbosch** [comment]
Maybe time to release a first release candidate? RC1?

**Comment by sagikazarmark** [comment]
I have a little bit tough week. I will try to share some love with OSS project next week.

**Comment by frederikbosch** [comment]
Aight, take care!

**Comment by danizord** [comment]
Raising dependency versions is not BC break AFAIK. We can always change PHP version if we feel that we need some PHP 5.5 feature without breaking BC.

**Comment by sagikazarmark** [comment]
Well, it might not be a break, but would make the package uninstallable after a certain version on a certain PHP version.

**Comment by danizord** [comment]
Yeah but the point is that you can do it in minor versions. So I think we could release first 3.0 version supporting 5.4 then raising PHP version in a next version?

**Comment by frederikbosch** [comment]
I think not. The current release is beta, which means subject to any change. The decision to only support stable and secure PHP versions remains.

If it was completely up to me, I am even willing to drop PHP 5.5 support. But I don't think I can persuade @sagikazarmark to agree with me on that one ;)

**Comment by danizord** [comment]
No problem for me :+1:

**Comment by sagikazarmark** [comment]
I've been doing a LOT of research on this topic. What actually made me to drop support for 5.4 was that this actually seems to be the trend. Despite that packages/frameworks don't necessarily use any features from newer PHP versions, they keep dropping support. I realized that @frederikbosch was right, this is somewhat a duty of ours.

However, yeah, dropping 5.5 support.....seems a little early to me.

**Comment by danizord** [comment]
Or... let's make it ^7.0 and take advantage of awesome scalar and return type hints :)

**Comment by frederikbosch** [comment]
Let's release 3.0 and 3.1 with PreciseMoney for PHP 5.5+. Then 4.0 can be PHP 7+.

**Comment by sagikazarmark** [comment]
In terms of features, I think we will reach kind of maximum in 3.x. After that we can drop PHP 5.x support in 4.0 and kind of support both versions then stop supporting 3.x if 7.0 is spread enough.

**Comment by frederikbosch** [comment]
@sagikazarmark Today I have pushed the library a lot. I want to get the release 3.0.0 out. People are mailing me when it will happen. I understand their impatience. For myself it also takes too long. I want to finish this project and maintain it. Let's try to get a new release asap, preferably this week. And a RC next week.

**Comment by sagikazarmark** [comment]
I am okay with releasing an alpha, but the API changed a lot and in RC releases we are not allowed to do that anymore. Also I am on holiday next week, so I would prefer releasing a beta next week and an RC a week after if we find the API stable enough.

**Comment by frederikbosch** [comment]
Sounds great. I will release the alpha now, and a beta next week. I will wait with releasing the RC after we had a conversation on it.

**Comment by frederikbosch** [comment]
Oh, there already is a beta I see. I will have to release a new beta (beta2).

**Comment by frederikbosch** [comment]
I'd love to help out to create a first RC, but I cannot. Maybe @sagikazarmark has time, because I do not have it the next two weeks.

**Comment by sagikazarmark** [comment]
I have to admit I haven't followed the latest development. I will try to catch up (btw. @frederikbosch awesome work!), but I became a maintainer of Guzzle too and I don't know if I will have that much time for OSS now. That said, I will try to review the current state and if I am happy with it, I will push it to RC. However, it shouldn't remain there too long, so I will only do that if I can make sure that after a 1-2-3 week period we can tag a stable release. In the meantime I will try to start the MoneyBundle too, so I can try it out in a few applications too.

**Comment by guiwoda** [comment]
Awesome, thanks!
Docs should be updated too, right? Maybe I can help with that.

**Comment by dereuromark** [comment]
:+1: for a stable release.

**Comment by frederikbosch** [comment]
@dereuromark We will release a new beta this week. There have been backward incompatible changes due to #280. As soon as we have the feeling that we have a stable API, we will tag a release candidate.

**Comment by frederikbosch** [comment]
New beta is there. If there are no API changes - or issues with API related changes - in the upcoming two weeks, we should be able to tag the RC.

**Comment by emaillenin** [comment]
Why do we not have support for string with more than 2 decimals in `StringToUnitsParser`? Is this intended? There are few currencies that have more than 2 decimal places.

**Comment by sagikazarmark** [comment]
@emaillenin  Can you please open a separate issue? Would be nice if you could provide some test code.

**Comment by emaillenin** [comment]
^ Good to see it has been fixed now - https://github.com/moneyphp/money/pull/292

**Comment by frederikbosch** [comment]
@sagikazarmark I'd say we merge #296 and fix #298 and then tag a stable. Our documentation is in a reasonable state an d the library is very complete. We should be happy where we are now. We have done a terrific effort and the result is great, if I may say so. It is time for 3.0 stable. Other improvements can be made later in time in later releases.

**Comment by sagikazarmark** [comment]
#296 is part of my final review. I would set end of October as the deadline.

**Comment by dilab** [comment]
Just a heads up. I do not think DecimalMoneyParser is included in 3.0.0-beta3.
It is documented though http://money.readthedocs.io/en/latest/Parsing.html#decimal-parser

**Comment by frederikbosch** [comment]
@dilab Correct. It was created after beta 3. There is a new release coming up.

**Comment by sagikazarmark** [comment]
So this is the last issue open in the 3.0.0 milestone. I am happy with the current phase and willing to tag the new release soon.

**Comment by frederikbosch** [comment]
Agreed, let's tag the stable release.

**Comment by frederikbosch** [comment]
@sagikazarmark Great work with the domain, logo and readme! It looks really good. Is there anything left?

**Comment by sagikazarmark** [comment]
Nothing, we are done. Tagged https://github.com/moneyphp/money/releases/tag/v3.0.0
