### ISSUE TITLE
Currency list

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#175]
Prior to 3.0-alpha @umpirsky provided us a great solution which allowed us to remove the custom currency list update.

Then @barryvdh came up with the valid point that this dependency is actually 90MB in size and contains about 6000 files.

Since I think this is not only a problem for us, but everyone else who wants to use that repository, I guess it is a good opportunity to solve it generally.

The following solutions were proposed:

- Move the repository to dev dependency and suggest it (does not completely solve the size issue)
- Reimplement a list update mechanism based on that repository
- Create a separate, smaller list package which can be used

Personally I think that update should not be the responsibility of this package, but if there is no other way, I can live with that.

WDYT?

**Comment by umpirsky** [comment]
If it is used only as a dev dependency to just copy only one file which this package needs and keep it versioned, then I think we can consider size problem solved.

**Comment by frederikbosch** [comment]
My suggestion is dev dep, suggest for those who need to update on regular basis and copy file. I would leave ISOCurrencies inside Money.
