### ISSUE TITLE
Amount must be an integer (Bug)?

### ISSUE THREAD

**Issue by superdummy** [moneyphp/money#176]
Thanks for the great library!

I always get the error below (using the 3.0 alpha):

`Amount must be an integer`
`in Money.php line 54`
`at Money->__construct('3500.0000000000', object(Currency)) in Money.php line 224`

Code to reproduce:
`$base = Money::EUR(2500);`
`$toadd = new Money(1000, new Currency('EUR'));`
`$added = $base->add($toadd); `
`dd($added);`

Is this a bug or what am I doing completely wrong? (Note dd() is a vardump from laravel)

Thanks

**Comment by frederikbosch** [comment]
@superdummy What happens if you use dev-master? It seems like the same bug that was reported in #164 and fixed in commit 50753be.

**Comment by superdummy** [comment]
Thanks so much for your help and even more for the great library! Yes with dev-master its working! Thanks!
