### ISSUE TITLE
BC Breaking changes

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#180]
- Money::getAmount() returns a string instead of an int value
- stringToUnits has been moved to a parser

**Comment by elstamey** [comment]
Thanks!

**Comment by elstamey** [comment]
OK, but if the warning isn't actually written in docs, it's not really helpful to the people like me who were surprised and broken.

**Comment by sagikazarmark** [comment]
It will be, this is just a list where we can collect stuff before writting to a dedicated location.

**Comment by frederikbosch** [comment]
I created a new PR, also contains the commit by @elstamey, and suggests three BC breaks. I looked in the commit history and this is what I was able to find.
