### ISSUE TITLE
Extract calculator library

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#188]
Calculator complexity is growing and growing. @frederikbosch do you think it would make sense to extract them to a separate library? Using calculators might make sense in other cases as well and our would be a good base for an abstract library.

**Comment by frederikbosch** [comment]
True. It is growing. But actually is it only the rounding problem that is giving complexity. For me, I rather see Money as a library without any dependencies. Not even within the own organization. Embedding the code always leaves us with the possibility to add/remove a method when we need to within the scope of this library. No waiting for external libs that have created their own dependencies with their own BC issues.

If people want to use our calculators, they can grab the code, or ask to abstract them in another library.

What I do think is necessary is that we do some more abstractions regarding rounding. These blocks in the [BcMath](https://github.com/moneyphp/money/blob/master/src/Calculator/BcMathCalculator.php#L117) and [Gmp](https://github.com/moneyphp/money/blob/master/src/Calculator/GmpCalculator.php#L122) calculator can be much cleaner. I'd say we focus on that.

**Comment by sagikazarmark** [comment]
Sounds reasonable. Is it a blocker for the release? It seems to me that it's mostly optimization, no API break is necessary.

**Comment by frederikbosch** [comment]
Great! I think we can do optimization without BC break.
