### ISSUE TITLE
`StringToUnitsParser` could be static?

### ISSUE THREAD

**Issue by lakhman** [moneyphp/money#195]
Could we make `StringToUnitsParser->parse()` a static function?

Instead of this:

```
$priceFormatter = new StringToUnitsParser();
$money = $priceFormatter->parse('1.50', 'GBP');
```

We could have a cleaner:

```
$money = StringToUnitsParser::parse('1.50', 'GBP');
```

**Comment by frederikbosch** [comment]
We want to provide implementations of the MoneyParser. As such you can type hint the interface, not the concrete class StringToUnitsParser. That is something you inject in your code.

I don't recommend it, but you could create a static class in your own code that does the two calls in your first example.

Is this enough explanation? I could emphasize it with code examples.

**Comment by lakhman** [comment]
can you show a code snippet? it would be helpful.

**Comment by sagikazarmark** [comment]
Something like this:

``` php
use Money\Parser\StringToUnitsParser;

final class StaticUnitParser
{
    /**
     * @var StringToUnitsParser
     */
    private static $parser;

    public static function parse($money, $forceCurrency = null) {
        return static::getParser()->parse($money, $forceCurrency);
    }

    private static function getParser()
    {
        if(null === static::$parser) {
            static::$parser = new StringToUnitsParser();
        }

        return static::$parser;
    }
}
```

**Comment by lakhman** [comment]
yeah ok, gotcha, thanks!

**Comment by frederikbosch** [comment]
Sure!

```php
<?php
namespace My;

class Controller {
  private $moneyParser;

  public function __construct (MoneyParser $moneyParser) {
    $this->moneyParser = $moneyParser;
  }

  public function read (ServerRequestInterface $request, ResponseInterface $response, callable $next) {
    $money = $this->moneyParser->parse($request->getParsedBody()['submittedFormValue'], 'USD');
  }
}

// And now we inject (e.g. using a DI container) the parser that is relevant.
$controller = new My\Controller(new StringToUnitsParser());

**Comment by frederikbosch** [comment]
Now let's go one step further, we are going to create our own parser.

```php
<?php
namespace My;

class FixedCurrencyParser implements CurrencyParser {
  private $currencyCode;
  private $delegatedParser;

  public function __construct(CurrencyParser $delegatedParser, $currencyCode) {
   $this->delegatedParser = $delegatedParser;
   $this->currencyCode = $currencyCode;
  }

  public function parse($money, $forceCurrency = null) {
    return $this->delegatedParser->parse($money, $this->currencyCode);
  }
}

class Controller {
  private $moneyParser;

  public function __construct (MoneyParser $moneyParser) {
    $this->moneyParser = $moneyParser;
  }

  public function read (ServerRequestInterface $request, ResponseInterface $response, callable $next) {
    $money = $this->moneyParser->parse($request->getParsedBody()['submittedFormValue']);
  }
}

// and then our controller
$controller = new My\Controller(new My\FixedCurrencyParser(new StringToUnitsParser(), 'USD'));

**Comment by frederikbosch** [comment]
In the final step, the controller is completely unaware of the parse method. It does not care, as long as it parses. You decide via injection how to do the parsing. Advantage: you can always change the implementation.

**Comment by sagikazarmark** [comment]
`CurrencyParser`?

**Comment by lakhman** [comment]
Excellent! Much cleaner! I'm going to go with the 2nd approach, much cleaner, I can inject into the classes I require, I'm using Symfony3 and this is the correct way of doing things, and yes If I need to change the implementation down the line, this makes it much easier.

I think `FixedCurrencyParser` should implement `MoneyParser` no?

Thanks!

**Comment by frederikbosch** [comment]
@lakhman Right. And yes, @sagikazarmark, `CurrencyParser` is wrong. I did it from the top of my head, so I probably made some errors :) Glad I was able to help.

**Comment by frederikbosch** [comment]
@sagikazarmark The `FixedCurrencyMoneyParser` could be part of the library. Makes sense in my opinion, what do you think?

**Comment by sagikazarmark** [comment]
What's the use case?

**Comment by frederikbosch** [comment]
In my own applications I do not require multiple currencies. A `FixedCurrencyMoneyParser` would really help in such case.

**Comment by sagikazarmark** [comment]
I see. Wouldn't it be better to only define a default currency and if forced currency is passed, use that instead? Or should it be a separate implementation?

**Comment by lakhman** [comment]
A `FixedCurrencyMoneyParser` would be helpful, I also am only using 1 currency, I suspect many others will also do the same.

**Comment by frederikbosch** [comment]
@lakhman @sagikazarmark I am also fine with `DefaulktCurrencyMoneyParser` instead of `FixedCurrencyMoneyParser`.

```php
class FixedCurrencyParser implements MoneyParser {
  private $currencyCode;
  private $delegatedParser;

  public function __construct(CurrencyParser $delegatedParser, $currencyCode) {
   $this->delegatedParser = $delegatedParser;
   $this->currencyCode = $currencyCode;
  }

  public function parse($money, $forceCurrency = null) {
    if ($forceCurrency === null) {
      return $this->delegatedParser->parse($money, $this->currencyCode);
    }
    return $this->delegatedParser->parse($money, $forceCurrency);
  }
}
