### ISSUE TITLE
Throw ParseException in StringToUnitParser

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#208]

**Comment by frederikbosch** [comment]
What do you mean with this? Now a Parse*r*exception is thrown. Do you want to rename the class?

**Comment by sagikazarmark** [comment]
It currently throws an invalid argument exception. IMO it should probably throw a parse exception if we already have one.

**Comment by sagikazarmark** [comment]
The other option is to throw ParseException everywhere.
