### ISSUE TITLE
Money extensions

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#211]
During reviewing the issues I got a little bit confused: we were talking about BigMoney and PreciseMoney, but it seems to me that the two are essentially the same: allow having precision (decimal values). Am I right?

In this case I was thinking about the following: have PreciseMoney as the decimal representation and have BigMoney as well.

BigMoney could be what Money is right now (calculators and the like) and Money could be the same with only using integers (PhpCalculator). I believe that this string representation stuff causes many confusion in people.

However, this would cause lots of other problems with other parts of the library: formatters, parsers, currency pair, etc. (Although we still have think about these issues since we want to add Precise money)

WDYT about these things @frederikbosch ?

**Comment by frederikbosch** [comment]
In my opinion we do not need `BigMoney`. The design of our classes is fine and the mere fact that we use strings internally should not be a problem. People understand it very well when explaining the reason. We should only bring it more upfront. It is something that belongs in the README.

Regarding `PreciseMoney`, that would indeed cause problems with other classes. But maybe `PreciseMoney` is just really different and requires different parsers and formatters. I think we should be careful in sharing code between `Money` and `PreciseMoney`. Just like Mathias wrote in his blog.

**Comment by frederikbosch** [comment]
@sagikazarmark Just created a PR for the README. It now contains a sentence on the usage of strings internally. See #214.

**Comment by frederikbosch** [comment]
Closed by #214.
