### ISSUE TITLE
Money does not allow values higher than PHP_INT_MAX

### ISSUE THREAD

**Issue by frederikbosch** [moneyphp/money#227]
This does not work, while it should.

```php
(new Money(PHP_INT_MAX, new Currency('EUR')))->add(new Money(1, new Currency('EUR')))
```

Cause.
```php
filter_var($amount, FILTER_VALIDATE_INT) === false
```

Apparently, `filter_var` does have `PHP_INT_MAX` as its upper boundary. So we should validate with another method. Of course, regular expressions will work, but I wonder if there is not a faster method.

**Comment by frederikbosch** [comment]
Maybe `ctype_digit`. Although I have not used that for a long time. Is it still valid to use it?

**Comment by sagikazarmark** [comment]
Good catch @frederikbosch
