### ISSUE TITLE
Simple Numeric Formatting - How?

### ISSUE THREAD

**Issue by judgej** [moneyphp/money#232]
I have a money object with some amount in it. I want to put this into a form field so it can be edited, or put into a report to tabulate. In both cases I need the amount appropriately formatted, with a decimal point and trailing zeroes where needed, but no currency symbol. How would this be achieved?

I'm just looking for the quick conversion between what is stored, and what a human would write the amount down as (without adding the currency symbol) in both directions.

**Comment by judgej** [comment]
Just a simple `(string)$myMoney` would be nice.

**Comment by sagikazarmark** [comment]
@judgej Do you use the 1.x stable or the 3.x upcoming version?

In the upcoming version we are working hard on making Money as easy to use as possible.

What you are trying to achieve is quite hard, since the amount is internally stored in integer format, which means Money (Currency) should be aware of the subunit. We tried to avoid this and make the value objects as simple and flexible as possible. Right now we are working on a formatting solution which involves a separate formatter object and a currency repository.

Casting the Money object to string could be a nice addition, but I guess everyone would expect a different result: just the amount, amount with currency, amount with currency symbol, etc.

**Comment by judgej** [comment]
I started on 1.3 b but have moved to the 3.x beta.

So the currency here is not aware of the size of the subunit? I thought I was going mad when I couldn't find it. To have to keep that information separate from the currency itself seems to defeat half the object of this library.

Humans and currency exchange services rates work in major units and minor units. Computers can work largely in minor units. Accounts like to work in fractions of minor units. Being able to easily move between these forms is what is going to make this library much more useful.

**Comment by sagikazarmark** [comment]
> So the currency here is not aware of the size of the subunit?

No, this library never did that. The main reason was that currencies themselves does not necessarily have minor units (although most physical currencies have).

Right now we are thinking about two possible solutions:

1. We already have the term of currency repository which contains basic and meta information for whatever currency you would like to use (see #223)
2. The other possibility is to add subunit support to the currency object itself. However, there are two problems with that:
    - You would have to create currency objects like `new Currency('EUR', 2)`
    - Convenient `Money::EUR(123)` factories wouldn't work anymore

Also, this makes the creation of a money object rather hard: `new Money(123, new Currency('EUR', 2))` In this case, is the input amount €123 or €1.23?

Minor units are actually useful if you want to format the amount. Using 1 or 100 for calculations doesn't matter, it only matters when you want to output the value.

This is a major problem we are aware of and blocks the 3.0 version, but there is no nice solution for this:

- Adding minor units makes many things complicated
- Not adding it makes the library harder to use

**Comment by judgej** [comment]
I'm trying to write decorators for some of the features I need to wrap around `Money`, since it cannot be extended dues to the use of `final`. The problem is, without an interface, the decorators cannot be type-hinted, which is a bit of a pain. If they are type-hinted against `Money` class, then the decorators cannot be nested, which is one of the reasons for using decorators.

I am really growing to dislike the `final` keyword...

**Comment by sagikazarmark** [comment]
What's your usecase for decorators?

**Comment by judgej** [comment]
I need the money object to be castable to a string, for use in a form. The form renderer will take any data type, so long as it will cast to s string. So [GBP, 120] will cast to a string as "1.20".

Also would like an easy formatter for displaying the value in display screens, so `$money->format()` on [GBP, 120] will give me "£1.20".

**Comment by sagikazarmark** [comment]
This is a quite common use case, which I also have. I suggest you reading @webmozart's post about: https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/ (given you are using symfony).

I don't think adding formatter logic to the VO is a good idea, it should be handled by an external service.

**Comment by judgej** [comment]
Hmm, the Form Model Accessors in the Laravel Collective HTML form generator bound to a model is supposed to be able to handle transformations, but it seems it's only on L5.2 and I'm on L5.1 (https://laravelcollective.com/docs/5.2/html#form-model-binding). I'll dig into how it works to see if it can be used in a similar way.

**Comment by Sharom** [comment]
> I don't think adding formatter logic to the VO is a good idea, it should be handled by an external service.

👍 I think, that translation between VO and string representation are responsibilities of a formatter and a parser.

But may be useful to return some string representation for logging or for debugging.

**For example**
```php
$money = new Money(10000, new Currency('USD'));
echo (string) $money;
```

**prints:**

```
 [Money\Money: amount=10000 currency=USD]
```

**or**

```
[Money\Money: amount=10000 currency=[Money\Currency: code=USD]]
```

**Comment by Sharom** [comment]
> I need the money object to be castable to a string, for use in a form. The form renderer will take any data type, so long as it will cast to s string.

**Infrastructure or framework should not affect design of the model.**

@judgej I am sure, that exist some another way to resolve your issue without modification of `Money`. If framework, which you use, does not provide some ability to implement form transformer, you can use DTO for aggregating information from a form. Then you can transform data from DTO to your model and vise versa.

**Comment by sagikazarmark** [comment]
> But may be useful to return some string representation for logging or for debugging.

We already have something similar: JSON serializability.

> Infrastructure or framework should not affect design of the model.

:100: :+1:

**Comment by Sharom** [comment]
> @judgej I am sure, that exist some another way to resolve your issue without modification of Money.
> If framework, which you use, does not provide some ability to implement form transformer, you can use
> [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) for aggregating information from a form.
> Then you can transform data from DTO to your model and vise versa.

I should correct myself. It's better to use [PRESENTATION MODEL](http://martinfowler.com/eaaDev/PresentationModel.html) pattern.

**Comment by Garbee** [comment]
There are two good methods here using a presenter model. The latter could lose precision due to using float, but doable.

<details>
<summary>Assuming bcmath is available<summary>
```php

use Money\Money;

class MoneyPresenter {
    /** @var Money $money */
    private $money;

   public function __construct(Money $object) {
        $this->money = $object;
    }

    public function amount() : string {
        return bcdiv($this->money->getAmount(), 100);
    }
}
```
</details>

<details>
<summary>If bcmath isn't available, return a float and round it on the frontend.<summary>
```php

use Money\Money;

class MoneyPresenter {
    /** @var Money $money */
    private $money;

   public function __construct(Money $object) {
        $this->money = $object;
    }

    public function amount() : float {
        return $this->money->getAmount() / 100;
    }
}
```
</details>

**Comment by judgej** [comment]
Presenting as a string is important here, as floats don't have trailing zeros.

My solution is to create an [accessor](https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators) on my eloquent model to make sure it always returns the underlying integer in the database as a `Money` object. Matching mutators then make sure a `Money` object can be passed back in for saving.

I've creating a macro in Laravel to present the money amount in form for editing. The macro extends the [Laravel Collective form](https://laravelcollective.com/docs/5.1/html) package. That formats it nicely and puts a currency symbol in the field as a bootstrap icon.

    {!! Form::money('my_money_field', null, ['class' => 'form-control']) !!}

When just displaying, I have an application helper. The helper just displays the amount as a string with a currency symbol:

    {{ \AppHelper::formatMoney($model->my_money_field) }}

Now, then submitting a form in Laravel, the input is given directly to the model, which means it is a string. The model mutator is clever enough to accept either a `Money` object or a string, which it then parses into `Money` for saving.

I'm sure there is a layer somewhere in the laravel form handling that should be able to take certain input data in certain contexts and parse it into a `Money` object before my model even sees it, but I've not found where that would be. I'm guessing *not* middleware, because the middleware does not have the context of what is being POSTed - it would not know what should be parsed and what should be left alone.

Anyway, I have a end-to-end solution that works, though does feel kind of bodged and clunky. I think perhaps that feeling comes from how closely bound form items and database columns are in laravel, so data to and from the browser tends to be treated as text or numbers all the way to the database. Maybe a DTO layer would help here? Not sure. Anyway, I'm walking that fine line between learning the *best and proper* way to do things, and trying to get the project out the door, hence my original question, and why I'm happy with my solution even if it does feel a little clunky to me.

**Comment by Garbee** [comment]
You can format either of the presenters I posted however you wish. I just did the math as the example, but you can do a currency format in there. As well as another method to get a string of the integer out with trailing zeros. Give `bcmath` functions some precision, and you'll have trailing zeros in your output.

Laravel doesn't provide a "layer" for this. It is one you'd need to implement on your own. Accessors/Mutators are typically exactly what this is for.

**Comment by frederikbosch** [comment]
Issue solved by merging PR today.

**Comment by sagikazarmark** [comment]
This has been a little bit improved again, see #289. I am thinking about some quick setup code since in many cases ISOCurrencies are used for everything. Although that's convenience stuff, it would live outside the domain, so it's kind of okay.
