### ISSUE TITLE
Add new valute code BYN

### ISSUE THREAD

**Issue by regroute** [moneyphp/money#235]
Could you add new code  BYN in file currencies.php

BYN" => "Belarusian Ruble New"

Thank You;

**Comment by sagikazarmark** [comment]
Please refer to https://github.com/moneyphp/money/pull/193. If it is part of the IANA data sources, we can update the currency list.

/cc @umpirsky

**Comment by umpirsky** [comment]
Basically all someone needs to do is clone https://github.com/umpirsky/currency-list and:

```
composer install
./bin/build
```

And submit the pull request. Sometimes it's hard to setup all dependencies, not sure when will I have time to do it, but I will be happy to merge PR and release new version.
