### ISSUE TITLE
Currencies source: use moneyphp/iso-currencies

### ISSUE THREAD

**Issue by frederikbosch** [moneyphp/money#243]
At this moment we are using @umpirsky library as source for [ISOCurrencies](https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php). This is incorrect because that library is not a representation of the official ISO4217 currencies.

In turn that library [uses `symfony/locale`](https://github.com/umpirsky/currency-list/blob/master/composer.json#L17) [which is deprecated](https://github.com/symfony/locale). One should now use `Symfony/Intl` and that library uses ICU as a source. At this moment the symfony library is using [ICU data version 55](http://site.icu-project.org/download/55). Apart from the fact that we are way too dependent on updates from multiple projects, I cannot confirm we are actually using the official ISO currencies. The website of ICU is a mess, and a [simple search does not lead me to whatever their source is](https://www.google.nl/search?q=site%3Aicu-project.org+currencies+iso).

Moreover, the current library provides very limited data on a currency. It does provide a translation for every currency's name but we do not need that. We need minor/subunits so we can finally provide a comprehensive solution to [all](https://github.com/moneyphp/money/pull/237) [our](https://github.com/moneyphp/money/issues/221) [formatting](https://github.com/moneyphp/money/pull/223) [problems](https://github.com/moneyphp/money/pull/233).

Therefore, I created [a new library `moneyphp/iso-currencies`](https://github.com/moneyphp/iso-currencies) within this organization. It is a very tiny library - and that should stay that way. It uses [the official resource](http://www.currency-iso.org/dam/downloads/lists/list_one.xml) for generating [two resource files](https://github.com/moneyphp/iso-currencies/tree/master/resources) that we could use in this packages. Important fact: it provides minor units for a currency. It is a perfect resource for automatic formatting a currency.

@sagikazarmark How do you feel about this?

**Comment by frederikbosch** [comment]
Oh, forgot to mention that this gives us better control over currency updates. We [need that](https://github.com/moneyphp/money/issues/235).

**Comment by sagikazarmark** [comment]
Do we really need a separate repository for that? Can't we simply place a build script in this one? I am all for separating everything, but I also have bad experience, so I think twice or three times before separating anything.

It is still not decided how we do subunits: access repositories or have it in the currency object?

Apart from that :100: :+1:

**Comment by frederikbosch** [comment]
@sagikazarmark I created an additional repository without thinking, probably because it is external now. On the other hand; it is within our own organization. I do not see a problem with it.

**Comment by frederikbosch** [comment]
Closed.
