### ISSUE TITLE
Release notes for v3.0.0-beta.2

### ISSUE THREAD

**Issue by manticorp** [moneyphp/money#264]
It would be great to have some release notes for v3.0.0-beta.2 - it introduced some breaking changes that took a while to piece together from commits - specifically needing to pass ```Currencies``` to the ```IntlMoneyFormatter```.

I would add them myself, but I'm not sure I can :)

**Comment by frederikbosch** [comment]
You are right! Will do that asap!

**Comment by frederikbosch** [comment]
Thanks for mentioning!
