### ISSUE TITLE
A way to get the numericCode?

### ISSUE THREAD

**Issue by xterr** [moneyphp/money#267]
Any future plans for implementing the possibility to get the numericCode of a certain currency (except BTC which doesn`t have yet a numeric code)? Useful when you want to store the currency in a database in a numeric type field.

**Comment by sagikazarmark** [comment]
Hi @xterr,

Thanks for reaching out. We are trying to make this library as minimal as possible and storing all ISO currency data (as we are talking about ISO currencies) would probably be too much data here.

That being said, there were a number of requests to provide more data for ISO currencies, so we might create a separate package with a set of tools to ease using them, but there is no ETA or roadmap for that yet.

Also, if we are talking about database: I would probably recommend that you use the currency code in the database. It might add some storage overhead, but it will always be unique (you can use imaginary currencies too) and does not require an extra mapping between the code and the currency.

**Comment by frederikbosch** [comment]
@xterr See: https://github.com/moneyphp/iso-currencies. But like @sagikazarmark says: it is not stable and it is also not created for external usage. This is going to be closed because it will not be implemented any time soon.
