### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by sahildua2305** [moneyphp/money#268]
I think the test coverage is not good enough for a lot of classes. There are very brief tests in place as of now. I'd like to add more tests. Let me know what do you think? @frederikbosch  😄

**Comment by sagikazarmark** [comment]
Honestly I haven't followed coverage in this library. I will setup Scrutinizer to see some stats about what's going on. Thanks for the note.

**Comment by sahildua2305** [comment]
Thanks for instant reply @sagikazarmark!

Even I haven't checked any stats about this library. I just had a look at the tests and realized that there was a scope of improvement. I think having more tests (at least covering all the functions/methods) is always better. So let me know if I should go ahead with adding tests or not yet?

**Comment by sagikazarmark** [comment]
Well, I would say go ahead, but try to separate them logically in PRs instead of submitting a huge test suite so that we can review it effectively and as quickly as possible. Thanks for the contribution in advance.

**Comment by sahildua2305** [comment]
Yes, @sagikazarmark! I will push some test over the weekend to make get them reviewed once.

**Comment by sahildua2305** [comment]
I looked a bit deeper and realized that it's actually coverage of unit tests which is pretty low. However the coverage of specs looks good.

Was it planned to keep most of the tests under specs? Let me know if we should aim for better coverage for unit tests as well. @sagikazarmark

**Comment by sagikazarmark** [comment]
The plan is to cover as much as possible with specs (and replace unit tests wherever possible).

**Comment by sahildua2305** [comment]
Okay. I was thinking of adding some more unit tests, which I shouldn't do now. Thanks for letting me know.

**Comment by frederikbosch** [comment]
Since the coverage of the spec tests is good, I will close this one.
