### ISSUE TITLE
How to store money with more than two decimal points?

### ISSUE THREAD

**Issue by jiriko** [moneyphp/money#270]
example: $1.2345

$fiveEur = Money::EUR(123.45);

**Comment by sagikazarmark** [comment]
You will have to store your money as integer:

`$fiveEur = Money::EUR(12345);`

**Comment by jiriko** [comment]
Is Money::EUR(12345) equal to 1.2345?

**Comment by sagikazarmark** [comment]
Yes and no. It depends on what minor units you want to use. Money provides you a way to represent your money value and do some calculations with it. At the moment we are working on this part to clarify whether we want minor units to be included in Currency objects or not. Until then, it's up to you.

It only matters when you want to format your money.
