### ISSUE TITLE
Conversion with different subunits, not working as expected

### ISSUE THREAD

**Issue by muteor** [moneyphp/money#272]
This is for the 3.0 beta.

When converting between two currencies that have different subunits, the conversion is not returning the correct amount.

Here is test case added to `CurrencyPairSpec.php`

```php
function it_converts_correctly_when_currencies_have_different_subunits() {
    $this->beConstructedWith(new Currency('GBP'), new Currency('BHD'), 0.5);

    $money = new Money(100, new Currency('GBP'));

    $resultMoney = $this->convert($money);

    $resultMoney->shouldHaveType(Money::class);
    $resultMoney->getAmount()->shouldBeLike(500);
    $resultMoney->getCurrency()->getCode()->shouldReturn('BHD');
}
```

Running this, `$resultMoney` has value of `50` where it should be `500` because `BHD` has subunit of `1000` not `100`.

This can be fixed by doing `((subunit_to / subunit_from) * amount) * rate` when doing the conversion. So in this example `((1000 / 100) * 100) * 0.5 = 500` which is `500 fils` or `0.5  dinar` (http://www.xe.com/currencyconverter/convert/?Amount=1&From=GBP&To=BHD). 

I had a quick look at the `convert` method but wasn't sure how you would like getting the subunit value into that method, looks like we would need to add a dependency on currencies.

**Comment by piku235** [comment]
I also hit on that some time ago, when testing conversion between EUR (2 minorUnits) and JPY (no minor units). At this moment I'm using a modified version, I highly needed it in one of my projects, generally works. :) I think I'll be able to share with you about my solution pretty soon when I'll finish doing final tests.

**Comment by frederikbosch** [comment]
As soon as Travis in #280 is done, we will merge that PR and this issue will fixed. Thanks for reporting and your help to make this a better package!
