### ISSUE TITLE
Number::isInteger can return false on numbers greater PHP_INT_MAX

### ISSUE THREAD

**Issue by narkaTee** [moneyphp/money#276]
Hi,

we've noticed some Strange behavior when dealing with numbers greater than PHP_INT_MAX in the version v3.0.0-beta.2.

It's easy to reproduce, install version 3.x beta:
`composer require mathiasverraes/money ^3.0-beta`

An run this code:
```php
<?php

namespace TestError;

use Money\Money;
use Money\Number;

require_once 'vendor/autoload.php';

echo "PHP_INT_MAX: ", PHP_INT_MAX, PHP_EOL;
$chunkSize = strlen((string)PHP_INT_MAX)-1;
echo PHP_EOL;

echo "Building Number (Chunk Size ", $chunkSize, "): ", PHP_EOL;
$bogous = str_repeat('1', $chunkSize);
$bogous .= '0123123';

echo "Bogous Number: ", $bogous, PHP_EOL;
echo '$bogous Number::isInteger():', PHP_EOL;
var_dump(Number::isInteger($bogous));

// Will throw InvalidArgumentException: Amount must be an integer
$willThrow = Money::EUR($bogous);
```

I've tracked the problem down to the `Number::isInteger` method, [which splits numbers bigger PHP_INT_MAX into chunks to validate them individually](https://github.com/moneyphp/money/blob/fb5644d929285cbb54c572e436eb1acd77bb5479/src/Number.php#L172-L177).
If one of this chunks has a leading zero the `filer_var` will return false.

The code above results in two chunks:
- '111111111111111111'
- '0123123'

The seconds chunk is an invalid integer.
Every operation (add, multiply, etc..) can result in a number triggering this problem.

Any ideas on how to work around this problem?
- a regex `preg_match` with `^\d+$`
- using `ctype_digit` (requires php to be compiled with ctype support)

**Comment by sagikazarmark** [comment]
Thanks for reporting the issue. Indeed it seems to be a bug. I will try to provide some test cases based on your example and provide a fix too,
