### ISSUE TITLE
Something is wrong with the compare method in Calculator

### ISSUE THREAD

**Issue by wppd** [moneyphp/money#278]
when doing `divide`, it'll call the calculator to verify the divisor **(cast to string first)** isn't zero.

from what I see,  the compare method in BcMathCalculator doesn't have scale as third parameter.

`bccomp($a, $b)`

which makes `bccomp("0.5", 0) === 0`: "Returns 0 if the two operands are equal"

if use GmpCalculator instead,

`ErrorException: gmp_cmp(): Unable to convert variable to GMP - string is not an integer`

**Comment by frederikbosch** [comment]
Why would you want that in a `Money` context? It is [impossible to construct a `Money` object with a decimal](https://github.com/moneyphp/money/blob/master/src/Money.php#L55).

**Comment by frederikbosch** [comment]
The same story is true for almost any `gmp_` method. You cannot `substract` or `add` a decimal number with the current GMP calculator. But since adding and subtracting decimals is not required by this package either (for the same reason I already gave that it is impossible to construct a Money object with a decimal), there will not be support for it until we start working on `PreciseMoney`. See #7.

**Comment by frederikbosch** [comment]
Also relevant in this thread is the [GMP Floating Point Support RFC](https://wiki.php.net/rfc/gmp-floating-point).

**Comment by sagikazarmark** [comment]
We could probably throw a logic exception when doing operations with
decimals.

Frederik Bosch <notifications@github.com> ezt írta (2016. október 1.,
szombat):

**Comment by frederikbosch** [comment]
@sagikazarmark I think we should just leave it. If there is no `Money` problem, there is no problem. We already have insufficient hands to get 3.0 out in reasonable time. If we starting fixing these issues...

**Comment by sagikazarmark** [comment]
Well, I agree. Honestly, I am not sure I completely understood the problem. However, if there is a leak in the API which easily leads to errors like this AND fixing them requires an API change we should do something.

Again: not sure if this is the case.
