### ISSUE TITLE
Improve IDE typehinting

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#282]

**Comment by Sharom** [comment]
I don't think that we need these magic methods. It is not useful for production application. Usually you receive currency from database or some other sources.

You can see `Money::USD(100)` in tests only.

**Comment by Sharom** [comment]
But this can be useful in production:

```php
$currencies = new ISOCurrencies();

$money = new Money(
    $amountFromDatabase,
    $currencies->get($rawCurrencyFromDatabase)
);
```

**Comment by sagikazarmark** [comment]
@Sharom generally I agree with you, but there seems the community wants it. If we can find a way which does not pollute the classes with noise then I am not against it. But in it's current form, the above PR is the third one that I rejected to merge so far.

**Comment by frederikbosch** [comment]
@sagikazarmark There is no real opportunity to do this magic in php doc. I'd say we close it. It hurts my eyes ;)

**Comment by sagikazarmark** [comment]
Agreed.
