### ISSUE TITLE
Current system upgrade: DB with decimal

### ISSUE THREAD

**Issue by vukanac** [moneyphp/money#283]
What could be the most strait forward way to convert Money to float
or at least string that looks like decimal?

Already have DB in MySql and Doctrine 2 with `amount` as decimal(10,2).

I am trying with `IntlMoneyFormatter`, but looks like "overkill".
And then again I got commas: "5,042.10"

    public function moneyToDecimal(Money $money, $fractionDigits = 2)
    {
        $mode = \NumberFormatter::DECIMAL;
        $numberFormatter = new \NumberFormatter('en_US', $mode);
        $numberFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, $fractionDigits);
        $moneyFormatter = new IntlMoneyFormatter($numberFormatter, new ISOCurrencies());
        
        return $moneyFormatter->format($money);
    }

    public function decimalToMoney($amount, $currencyStr)
    {
        $unit = Money::stringToUnits($string);  // 5.00 -> 500
        $currency = new Currency($currencyStr); // EUR
        return new Money($unit, $currency);
    }

Is there anything that exists that do similar to above or:

    $amountFloat = $money->getAmount()->toInt() / $money->getCurrency()->getFractionAsInt();

**Comment by vukanac** [comment]
$currencies->subunitFor(new Currency('USD')); // returns the subunit for the dollar (2)

**Comment by vukanac** [comment]
As I can see, it will be nice to be able to get `$formated` value
from [`IntlMoneyFormatter::format()`](https://github.com/moneyphp/money/blob/master/src/Formatter/IntlMoneyFormatter.php#L59) method.

**Comment by frederikbosch** [comment]
See the integration paragraph in the readme. Store the amount as an integer in your DB, and the currency as a string (varchar).
