### ISSUE TITLE
Finalize documentation

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#291]
- [x] Fix TOC
- [x] Review content
- [x] Check if something is missing

**Comment by frederikbosch** [comment]
@sagikazarmark If you want to setup a site, let me handle this then.

**Comment by sagikazarmark** [comment]
Actually it's not just proofreading: I want to catch up. ;)

The site is not top prio.

I would say we both better proofread, improve whenever we can.

**Comment by tuwannu** [comment]
Speaking of documentation, do you still mean http://money.readthedocs.io?

I noticed the last build was 8 months ago (http://readthedocs.org/projects/money/builds/). So I triggered a new build. The TOC should now be updated

**Comment by frederikbosch** [comment]
Stupid question: how do you do that?

**Comment by frederikbosch** [comment]
@tuwannu Thanks by the way ;)

**Comment by tuwannu** [comment]
Go to http://readthedocs.org/projects/money/builds/ and look for a button that says "Build Version". Pick a version then click the button should run the build.

Actually, you should be able to set ReadTheDocs to build automatically via a webhook. Check out the explanation below "Auto-updating" at http://docs.readthedocs.io/en/latest/features.html#auto-updating

**Comment by frederikbosch** [comment]
@tuwannu Thanks!

@sagikazarmark I see that we already had a webhook, but I think it is broken since we move to another github url. Since I have no access there, could you try to fix it? Simply readding the URL to github is not the solution.

**Comment by sagikazarmark** [comment]
@tuwannu Thanks.

@frederikbosch I am on it.

**Comment by sagikazarmark** [comment]
Hm, I updated the the repo URL, should be ok now

**Comment by frederikbosch** [comment]
Works, great!

**Comment by sagikazarmark** [comment]
@frederikbosch what's your RTD username?

**Comment by frederikbosch** [comment]
@sagikazarmark I dont have RTD :)

**Comment by sagikazarmark** [comment]
Ah, okay. :) Then I can't add you there.

**Comment by tuwannu** [comment]
Right now the docs seem to explain well the money concepts covered in this library. However it's a little difficult for someone to get started i.e. "How do I add/subtract two amounts?", "How do I compare amounts which one is larger/smaller?". That person needs to look through possibly all topics in the docs right now and still don't get an answer.

I would suggest to improve the docs structure to be more like [Carbon](http://carbon.nesbot.com/docs/), where there are clear headings and content for Getters, Setters, Comparison, Addition & Subtraction, etc.

Does this sound like a good idea to you guys? If so I could give this a try and submit a pull request.

**Comment by frederikbosch** [comment]
I am in favor of any enhancement as long as it does not block from releasing 3.0 stable.

**Comment by sagikazarmark** [comment]
I would like to do some improvements before releasing. @tuwannu PRs are very welcome.

**Comment by tuwannu** [comment]
See #311 for my docs suggestions. I added sections about Money operators as well as grouped the TOC a little bit. I hope this structure makes more sense from a user point of view.

**Comment by sagikazarmark** [comment]
I also did some grouping, please feel free to suggest modifications there. I also like the documentation of operators.

**Comment by frederikbosch** [comment]
Great work here! Maybe I would move Bitcoin down to the last position in the ToC. If @tuwannu can rebase his PR, we might have a stable release this week?

**Comment by frederikbosch** [comment]
I checked the boxes, because I think we have done enough in this respect. If you agree too @sagikazarmark then you can close this issue.

**Comment by sagikazarmark** [comment]
Agreed.
