### ISSUE TITLE
StringToUnitsParser - Class not found

### ISSUE THREAD

**Issue by daerimin** [moneyphp/money#293]

**Comment by daerimin** [comment]
Composer install is missing a lot.  Downloaded the .zip and they seem to be there.

**Comment by sagikazarmark** [comment]
@daerimin we just accepted a PR which removed this class, however at that time it was still in the repository. Are your issues resolved? Please check the documentation to see the changes: http://money.readthedocs.org/

**Comment by daerimin** [comment]
Thank you for the reply! Seemingly so, yes - I have the classes I need and my code is working – but if I understand correctly, the parser is being done away with?  That’s the whole reason I went searching for a library, is so I can turn strings that represent currency (“$1.00”) into something I can do math with.

**Comment by sagikazarmark** [comment]
Parsers has been changed a little bit. If you want to parse a monetary value (with currency) use the IntlParser.
