### ISSUE TITLE
Bitcoin currency repository should throw an exception when currency is unkown

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#295]

**Comment by frederikbosch** [comment]
Why? The contains method already returns false?

**Comment by sagikazarmark** [comment]
What happens if I call it with some random currency? It returns the static value. AFAIK that's exactly why we introduced the UnkownCurrency exception. Am I wrong?

**Comment by frederikbosch** [comment]
It never returns the currency code. It returns boolean for contains, int for subunitFor and iterator for getIterator. I dont see the problem.

**Comment by sagikazarmark** [comment]
https://github.com/moneyphp/money/blob/master/src/Currencies/BitcoinCurrencies.php#L24-L30

This one returns 8 for each currency, while I think it should throw an exception for non-bitcoin: https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php#L44-L46

**Comment by frederikbosch** [comment]
You are right!

**Comment by frederikbosch** [comment]
PR is there.
