### ISSUE TITLE
// $swap = Implementation of \Swap\SwapInterface

### ISSUE THREAD

**Issue by daerimin** [moneyphp/money#299]
Hello,

I apologize if my PHP simply isn't good enough to inherently understand this, but I do not see how to get currency conversions working.  The documentation states to simply "do this" but I do not understand what "this" means, so I would like to ask for some clarification on what to do to implement this.

Thank you!

**Comment by sagikazarmark** [comment]
First you need to install the swap package which you have the command in the docs.

To be complete, you should use this: `composer require florianv/swap:^2.0`. (At the moment we don't support 3.0 yet).

Then you need to configure Swap as per the instructions here: https://github.com/florianv/swap/tree/2.x#usage

Finally you need to follow the rest of the documentation.

Does this help?

**Comment by daerimin** [comment]
Thank you very much for your guidance.  Unfortunately it seems that by using composer to download the code, large portions are left out.  The only way I could get either library to work was to "git clone" both projects, the cd into the new folders and run "composer install" - only doing this seems to provide all the classes.

**Comment by sagikazarmark** [comment]
> Unfortunately it seems that by using composer to download the code, large portions are left out.

That's quite weird. Can you show me your composer.json?

**Comment by daerimin** [comment]
I thought it was as well.  This could just be my ineptitude with Composer.  If so I sincerely apologize.  I typed the command you gave above exactly, and the following composer.json was created:

{
    "require": {
        "florianv/swap": "^2.0"
    }
}

When I include the "vendor" folder in my project and attempt to use the Swap\Builder class, I get a "class not found" error.  When I use the git clone method, and include that code instead, everything works.  Hence my conclusion.  It may be that I'm simply leaving out a step, or there's something else I don't know to do.

**Comment by sagikazarmark** [comment]
Have you done this somewhere?

`require 'vendor/autoload.php';`

**Comment by daerimin** [comment]
Yes, that much I do know.  :)

**Comment by sagikazarmark** [comment]
Hm, strange.
