### ISSUE TITLE
Should we make tests final?

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#301]

**Comment by pamil** [comment]
The real question is: why not? :)

**Comment by frederikbosch** [comment]
@sagikazarmark Yes, final, no need to extend them. If there might ever be a reason to extend, someone can do that in the PR.

**Comment by pamil** [comment]
Almost all specs & tests in Sylius are final and we haven't got any issues with it yet.

**Comment by frederikbosch** [comment]
@sagikazarmark Final was never a habit in the PHP world. Thanks to Mathias et al we learned.

**Comment by frederikbosch** [comment]
Fixed via #296.
