### ISSUE TITLE
Stableize moneyphp/iso-currencies

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#306]

**Comment by frederikbosch** [comment]
I left it dev-master because it has no external purpose.

**Comment by sagikazarmark** [comment]
Well, if we are happy with it, just tag v1.0.0.

This hurts my eyes:

![kepernyokep 2016-10-20 12-38-03](https://cloud.githubusercontent.com/assets/1226384/19556665/6e3c5596-96c2-11e6-9545-b504670222aa.png)

**Comment by frederikbosch** [comment]
Hehehe, I understand, I also have problems with complaining IDEs. Will tag 1.0.0 and reference it here.
