### ISSUE TITLE
Rename packagist package?

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#309]
This would be a perfect opportunity to rename the package to moneyphp/money

**Comment by sagikazarmark** [comment]
Unfortunately money/money is taken

**Comment by sagikazarmark** [comment]
...and it's a fork of this library :joy:

**Comment by frederikbosch** [comment]
Agree: moneyphp/money. Too bad money/money has been taken. And I believe there is an alias option?

**Comment by frederikbosch** [comment]
@sagikazarmark Shall I take care of this one?

**Comment by pamil** [comment]
I guess speaking with the current owner of `money/money` may be worth a try :)

**Comment by sagikazarmark** [comment]
Probably yes, but that would mean that all the packages/applications depending on it would break. It still has 10-20 installs/day.

**Comment by frederikbosch** [comment]
Let's go for moneyphp/money instead of money/money.

**Comment by sagikazarmark** [comment]
Yup. I am also releasing a last beta with the current name.

**Comment by sagikazarmark** [comment]
@frederikbosch Can you please add me here as a maintainer? https://packagist.org/packages/moneyphp/iso-currencies

I cannot add packages with this vendor.

**Comment by frederikbosch** [comment]
You might want to create an alias for `mathiasverraes/money`.

**Comment by sagikazarmark** [comment]
Alias? I want to deprecate that package. I don't think there is such thing as alias, only abandon.

**Comment by frederikbosch** [comment]
Oh, I thought there was such an option. I think I cannot add a maintainer..

**Comment by sagikazarmark** [comment]
Here: https://packagist.org/packages/moneyphp/iso-currencies ???

You created this package

**Comment by frederikbosch** [comment]
I think that goes by changing the composer.json. There is no such thing as changing a maintainer with the UI. Or is there?

**Comment by sagikazarmark** [comment]
Composer maintainer and packagist maintainer is not the same.

**Comment by sagikazarmark** [comment]
My name is mark.sagikazar there

**Comment by frederikbosch** [comment]
Ah, great! Thanks!
