### ISSUE TITLE
Should the docs TOC be arranged by frequency than alphabetical?

### ISSUE THREAD

**Issue by tuwannu** [moneyphp/money#313]
I'm a little reluctant to submit this with #312 because it will cause significant structural changes to the TOC.

Basically my argument is that alphabetical order doesn't help those who need the docs. In order to use alphabetical order efficiently, you need to know what topic you are looking for. By the time you know what topic you should be looking for, you probably don't need the docs anymore.

It's probably better arranged in likely frequency that the feature will be used. Like this?

> - Money
> - Getting Started
> - Concept
> - Inspiration
> - Features
>  - Operation
>  - Comparison
>  - Allocation
>  - Parsing
>  - Formatting
> - Advanced Features
>  - Currencies
>  - Currency Conversion
>  - Bitcoin

I understand that frequency and Features & Advanced Features separation is subjective, but to me this improves readability a lot. What do you think?

**Comment by sagikazarmark** [comment]
I think this is what @frederikbosch meant earlier. I agree, but to avoid conflicts again, this should be the last step.

**Comment by frederikbosch** [comment]
Agreed. Since we both liked the PR, I asked to put them in frequency order.
