### ISSUE TITLE
Reversible Conversion

### ISSUE THREAD

**Issue by timidboy** [moneyphp/money#323]
Wouldn't it make sense if the currency conversion is reversible?

`$exchange = new FixedExchange([
    'EUR' => [
        'USD' => 1.25
    ]
]);`
`$converter = new Converter(new ISOCurrencies(), $exchange);`

`$eur100 = Money::EUR(100);`
`$usd125 = $converter->convert($eur100, new Currency('USD'));`

`$eur100Original = $converter->convert($usd125, new Currency('EUR'));`
`assert($eur100Original->equals($eur100));`

**Comment by bmeynell** [comment]
I had expected this functionality as well in this library. The formula to do a reverse conversion is simple, but would be nice to have as part of this library and unit tested.

**Comment by frederikbosch** [comment]
Agreed. Will be added soon.

**Comment by sagikazarmark** [comment]
Do you specifically mean this feature for the FixedExchange implementation? If so, :+1:

**Comment by timidboy** [comment]
I mean, `EUR/USD 1.25` is the same as `USD/EUR 0.8`, right?
(I don't know much about standards in currency conversion)

Can we just add it to the `Money\Exchange::quote()` specifications?

**Comment by sagikazarmark** [comment]
The problem is that this would require to have multiple calls to an external service in some cases.

Also, in reality conversion rates cannot always obviously calculated from the other (because of rounding, etc).

Therefore I would rather not add it to the API.

Instead I would implement a InverseExchange (or something like that) as a behavioural decorator which adds this behaviour to any exchanges (basically try the inverse of the currency pair if it is not found in the given exchange).

**Comment by frederikbosch** [comment]
We can fix this inside `FixedExchange`, right? The responsibility of reverse conversion inside the swap implementation is not ours.

**Comment by sagikazarmark** [comment]
Honestly I don't like the idea of this reverse thing at all. But if we do this, I would say we should have it as a separate behaviour. If one of the exchanges supports it and the other not it could lead to confusions. With a separate decorator anyone can add it to any exchanges on their own.

**Comment by timidboy** [comment]
@sagikazarmark  So, it's a no then. But, IMHO, you're idea is an unnecessary complexity.

**Comment by sagikazarmark** [comment]
> But, IMHO, you're idea is an unnecessary complexity.

I don't see why. It's a perfect way to avoid duplicating the same behaviour in all exchanges + makes it optional, so that people don't get confused with unexpected behaviour.
