### ISSUE TITLE
BC break not mentioned in CHANGELOG

### ISSUE THREAD

**Issue by garak** [moneyphp/money#325]
I just updated from v1.3.0 to v3.0.0 and got a break (see #324)
The BC break was introduced in e9c7aaa, but it's not mentioned in the CHANGELOG.
I would open a PR myself, I'm just not sure of the position of such change, since it's between 3.0.0-alpha and 3.0.0-beta

**Comment by frederikbosch** [comment]
Private variables may always changes. The fact that Doctrine use Reflection is a risk that that package is taking.

**Comment by garak** [comment]
@frederikbosch I see and I don't want to argue about that.

But considering that people are using this library with Doctrine, maybe a small mention could be fair.

**Comment by frederikbosch** [comment]
@garak Fair enough, just changed the [CHANGELOG](https://github.com/moneyphp/money/blob/master/CHANGELOG.md#changed).

**Comment by sagikazarmark** [comment]
This is a perfect scenario which shows the benefit of option two from #328
