### ISSUE TITLE
Large Values are Converted to Negative Numbers

### ISSUE THREAD

**Issue by AlessandraV** [moneyphp/money#329]
I'm using this package and found that when a value is over 20-ish million, the class will turn it negative. For example, 22,745,142 gets converted to -20,204,531. Is this a known issue? Is there a work-around?

**Comment by sagikazarmark** [comment]
Can you please give us the following:

- Example code of yours
- output of `$ php -m`

At first it sounds like integer overflow, but the given number is not that large and this library handles it (in theory).

**Comment by AlessandraV** [comment]
Maybe this issue is dealing with floats? Part of the issue is that some of our is a float, integer or string before it is converted. So we added some code to handle this. I just now added the if $amount is greater than 20 mil and it seemed to make the large numbers output as not negative numbers. Here is my code:`	

    public static function getMoney($amount, $options = array()) {
		$defaults = array(
			'currency' => self::$currencyCode
		);
		$options = array_merge($defaults, $options);

		$largeValue = false;
		if ($amount > 2000000) {
			$largeValue = true;
			$amount  = $amount / 10000;
		}

		if (!is_int($amount)) {
			if (is_string($amount)) {
				if (strpos($amount, '.') == true) {
					$amount = floatval($amount);
				}
				elseif (intval($amount) == $amount) {
					$amount = intval($amount * 100);
				}
				else {
					$amount = floatval($amount);
				}
			}
			if (is_float($amount)) {
				$amount = intval(round($amount, 2) * 100);
			}
		}
		else {
			$amount = $amount * 100;
		}

		$amount = $amount * 100;

		if ($largeValue == true) {
			$amount = $amount * 10000;
		}
		
		return new \Money\Money($amount, new \Money\Currency($options['currency']));
	}`

**Comment by frederikbosch** [comment]
Please come up with a better description of the issue.
