### ISSUE TITLE
get Currency Symbol

### ISSUE THREAD

**Issue by Surt** [moneyphp/money#330]
Is it possible to get the currency symbol alone for a money object?
Actually I'm using this:

```
function getCurrencySymbol($locale, $currency)
    {
        // Create a NumberFormatter
        $formatter = new \NumberFormatter($locale, \NumberFormatter::CURRENCY);

        // Prevent any extra spaces, etc. in formatted currency
        $formatter->setPattern('¤');

        // Prevent significant digits (e.g. cents) in formatted currency
        $formatter->setAttribute(\NumberFormatter::MAX_SIGNIFICANT_DIGITS, 0);

        // Get the formatted price for '0'
        $formattedPrice = $formatter->formatCurrency(0, $currency);

        // Strip out the zero digit to get the currency symbol
        $zero = $formatter->getSymbol(\NumberFormatter::ZERO_DIGIT_SYMBOL);
        $currencySymbol = str_replace($zero, '', $formattedPrice);

        return $currencySymbol;
    }
```

**Comment by sagikazarmark** [comment]
I am sorry, but this has been discussed numerous times and the answer is no. This is a value object and as such, represents a value. If you need such data create some kind of provider which can tell this to you based on the currency object.

**Comment by Surt** [comment]
Ok, understood. Anyway, despite the "value object" approach, the "Currency" class could have a "getSymbol" as it have a "getCode". I read the approach you are giving to the library, the final class implementation, etc..
Probably I will implement a more versatile formatter to reach my goals.

**Comment by sagikazarmark** [comment]
> Anyway, despite the "value object" approach, the "Currency" class could have a "getSymbol" as it have a "getCode".

It has getCode because code is it's value, but currency is not.

>  Probably I will implement a more versatile formatter to reach my goals.

If you come up with something that you think would be valuable for the community, share with us and we will see if we can include it in this library.

**Comment by Surt** [comment]
Actually my solutions are mostly specific formatters and parsers.
What I don't like is the need of those dependencies over my code. I mean, I wrote lot of lines creating different formatters-parsers instances all over the code for just this library.

I tried with composite, creating some kind of adapter for money, but there is a lot of duplicated code, and workarounds for __call, that seems like patches to me. :( (since the final don't allow to extend.

I also tried creating an utility class with static methods, wich perform all the parsers-formatters instantiation etc.. 

I like the http://carbon.nesbot.com/docs/ approach. Where the "entity" performs all the translations, formats, etc by itself.

well, I guess I'll make up with it after a while :)

**Comment by sagikazarmark** [comment]
> I like the http://carbon.nesbot.com/docs/ approach. Where the "entity" performs all the translations, formats, etc by itself.

Except this is not an "entity", but a value object. :smile: Also, it is possibly a huge break of SRP.

Anyway, usually the functional approach is correct, even if it means you need to write formatters/parsers. That might be dependency on this library, but it won't work without them in case of VOs. This is probably a downside, but enforces better design which is a win IMO.

**Comment by Surt** [comment]
Finally I ended with an ugly workaround, creating a repository of static methods for some functionality. I don't like it but, it's functional for the moment.

```php
class MoneyUtilities
{
    public static function extractPercentage(Money $money, $percentage)
    {
        $result = clone $money;
        $percentage = $result->divide(100 + $percentage)->multiply($percentage);
        $subtotal = $money->subtract($percentage);

        return [
            'percentage' => $percentage,
            'subtotal'   => $subtotal,
        ];
    }

    public static function getSymbol(Money $money)
    {
        return (new SymbolMoneyFormatter())->format($money);
    }

    public static function getConvertedAmount(Money $money, $intl = true)
    {
        return (new AmountMoneyFormatter())->format($money, $intl);
    }

    public static function toString(Money $money)
    {
        return (new IsoMoneyFormatter())->format($money);
    }

    public static function parseString($money, $forceCurrency = null)
    {
        return (new StringMoneyParser())->parse($money, $forceCurrency);
    }
}
```

**Comment by sagikazarmark** [comment]
@Surt this is THE solution, the static proxy is just sauce.

**Comment by AyubM** [comment]
You guys need to get a grip -- this is PHP not Java.

I have to import **5** different classes just to do something basic with your library.

Whatever you call this style, it goes against PHP community standards.

**Comment by ossinkine** [comment]
@sagikazarmark What about adding `symbolFor` method (like `subunitFor`) in `Currencies` interface?

**Comment by kslimani** [comment]
It would be nice to have a "reliable" way to converts a money amount into an array (or object, ?) to retrieve splitted data (_positive or negative, the unsigned part, the decimal part, the symbol, the thousand separator, the decimal separator and the mask_).

This is usefull if you needs to display the amount in a "fancy" way. (_thought it may be out of the scope of this library ?_)

**Comment by ossinkine** [comment]
@sagikazarmark Symbol is needed to pass it to NumberFormatter because:
1. Not all common symbols are supported by `intl` extension.
2. You cannot set fraction digits until the formatter does not know currency symbol.
