### ISSUE TITLE
Allocate refusing integer arguements

### ISSUE THREAD

**Issue by garikaib** [moneyphp/money#332]
Using the example given on the page http://moneyphp.org/en/latest/features/allocation.html I am getting the following error:
Fatal error:  Uncaught TypeError: Argument 1 passed to Money\Money::allocate() must be of the type array, integer given, called in C:\xampp\htdocs\appinterface\test_money.php on line 92 and defined in C:\xampp\htdocs\appinterface\vendor\moneyphp\money\src\Money.php:339
Stack trace:
#0 C:\xampp\htdocs\appinterface\test_money.php(92): Money\Money->allocate(70, 30)
#1 {main}
  thrown in C:\xampp\htdocs\appinterface\vendor\moneyphp\money\src\Money.php on line 339

**Comment by frederikbosch** [comment]
Which is correct. Allocate expects an array where as allocateTo expects an integer.

**Comment by frederikbosch** [comment]
The docs example is incorrect indeed. Must be updated. Thanks!

**Comment by frederikbosch** [comment]
Done

**Comment by garikaib** [comment]
Thank you for this and your excellent work. Using arrays makes more sense
anyway.

**Comment by frederikbosch** [comment]
@garikaib Very welcome!
