### ISSUE TITLE
Multiplication and Division Operands

### ISSUE THREAD

**Issue by digilist** [moneyphp/money#333]
I am doing lots of money based multiplications and divisions, so I tested this library. Looks cool so far, but I ran into one problem. I have a custom Decimal class, that under the hood uses bcmath to do the calculations. Currently, I have to cast the decimal to string everytime before doing a multiplication, because you are checking if the operand is a numeric (see https://github.com/moneyphp/money/blob/master/src/Money.php#L255).

This is a little bit annoying. So what do you think about checking if the passed operand is an object and has a __toString method, and if so, cast it to string and check that value? This would allow to use arbitrary object inputs as operands. If you think it's okay, I'd like to submit a pull request.

**Comment by frederikbosch** [comment]
Hmm interesting case! I am not against this per se. What do you think @sagikazar?mark

**Comment by frederikbosch** [comment]
@digilist Would #334 be sufficient?

**Comment by frederikbosch** [comment]
That PR requires some extra work. However, where would we need to take the possibility of such an object into account? Multiply and divide are obvious, but are there more places that we need to change? If we allow an object as operand we need to implement it comprehensively.

**Comment by digilist** [comment]
Thanks for your quick response! Just casting the value to string is more simple and a good idea. For me this would work. I don't know about other cases yet, as I haven't explored the internals of this library that much yet. But if that's the case, I agree with you, that this should be adjusted everywhere.

However, what about cases in which an object is passed that cannot be casted to string? Then, there will be a "cryptic" error that the object cannot be casted to string ("Catchable fatal error:  Object of class stdClass could not be converted to string"). With an additional check and an explicit error message it will be easier for developers to identify the reason for that error.

Another case I am thinking about is the PHPCalculator if bcmath or gmp is not available. Then, the string must be casted back into an integer all the times. So maybe, if the value is already an integer or float, it might not be casted to string (it would work though).

**Comment by frederikbosch** [comment]
After thinking this through, I think this is not a good idea after all. The API we have now is simple. With this feature, we are moving towards a more complicated API. Maybe we should add this for `PreciseMoney`. I figure that the need then for such a feature is much more severe than with `Money` now.
