### ISSUE TITLE
Supporting operations on amounts for different currencies in different dates

### ISSUE THREAD

**Issue by mnvx** [moneyphp/money#343]
Is it possible to operate with amounts, that represented in different currencies on different dates? For example, is it possible to sum next amounts with this library:?

100 usd on 2016-01-01 + 10 eur on 2015-04-04 + 500 rub on 2017-01-10 = amount in brl on current day?

**Comment by frederikbosch** [comment]
This is not supported out of the box, but you could create something yourself. I think things belongs to your own domain layer. Though, there is something to say for this feature.

@sagikazarmark How do you feel about this?

**Comment by sagikazarmark** [comment]
I agree with @frederikbosch: this is not really related to money as a value, but your custom need. You could create a nice wrapper around Exchanges and Money to get the desired result.

At least I don't really see how this would fit into a generic purpose money package.

**Comment by mnvx** [comment]
Thanks. I think it is good way.
