### ISSUE TITLE
Bitcoin formatter issues PHP notice with small amounts

### ISSUE THREAD

**Issue by Firehed** [moneyphp/money#346]
When trying to print a fraction of a bitcoin with the bitcoin formatter, if the number of digits requested is too few (I think where it would effectively round to zero, since the subunit for bitcoin is so large), a string offset warning is issued. 

```
<?php
require 'vendor/autoload.php';
use Money\Currency;
use Money\Currencies\BitcoinCurrencies;
use Money\Formatter\BitcoinMoneyFormatter;
use Money\Money;

$btc = new Money(100, new Currency('XBT'));

$btcFormatter = new BitcoinMoneyFormatter(2, new BitcoinCurrencies());
echo $btcFormatter->format($btc);
```

`Notice: Uninitialized string offset: -3 in DIR/vendor/moneyphp/money/src/Number.php on line 199`

My composer.lock file says this is with v3.0.0.

**Comment by frederikbosch** [comment]
Thanks, fixed in current master
