### ISSUE TITLE
Support for historical exchange rates

### ISSUE THREAD

**Issue by stefandoorn** [moneyphp/money#347]
The search didn't show an early PR / discussion to me regarding this: support for converting using historical exchange rates. There is of course the option to use the `FixedExchange`, but this requires loading the exchange rates separately.

Money already supports the `SwapExchange`, using Swap's `latest` method to retrieve the exchange rate. But, Swap also offers an `historical` method to get the exchange rate of an earlier moment in time. 

I'm in need of it for a current project and if there is interest for including it, I could submit a PR. 

If so, there a some options of implementation:

* Add a method to `SwapExchange` & and a method to `Converter`
* Add an optional parameter to `SwapExchange::quote` & `Converter::quote`
* Add an extra Exchange class, e.g. `HistoricalSwapExchange` & and add method to `Converter`

Etc.

What would have your preference?

**Comment by sagikazarmark** [comment]
Thanks for contributing to the project.

I think the third option sounds like the cleanest, but modifying the converter sounds a little bit weird to me. It has a nice, single responsibility, I wouldn't add more to that.

Probably adding a historical exchange interface, an implementation for swap and a HistoricalConverter could be the way to go?

WDYT @frederikbosch

**Comment by stefandoorn** [comment]
I had to move on already a bit to get the support in my current project, so I took your suggestions and forked the repo and implemented support.

Progress here: stefandoorn/moneyphp@7b267d1b625798dceb2f4ab5861fdb00d42b4a79.

If this makes sense, I can finalise and submit the PR.
