### ISSUE TITLE
Divide method and division by zero checking

### ISSUE THREAD

**Issue by damonjones** [moneyphp/money#352]
The divide function uses the current calculator to check for a zero divisor:
```
if ($this->getCalculator()->compare((string) $divisor, '0') === 0) {
        throw new \InvalidArgumentException('Division by zero');
}
```

As the BCMathCalculator doesn't use any precision value, values < 1 are treated as 0 (which shouldn't be a problem for values that are not even close to 0).

For example, if I have a value which has received a 10% discount (original * 0.9), dividing by 0.9 would give me the original value before the discount.

**Comment by sagikazarmark** [comment]
Thanks for the report, I will take a look at this soon.

**Comment by frederikbosch** [comment]
@damonjones Can you see what #352 does?

**Comment by frederikbosch** [comment]
Uh, that should be #353
