### ISSUE TITLE
Converting dollars to cents?

### ISSUE THREAD

**Issue by NinoSkopac** [moneyphp/money#355]
Hi, this is a question.

Let's say I have a float: `1.00`, denoting one dollar, and since `Money` only understands cents - what is the best approach when it comes to giving `Money`'s constructor cents?

Is it `$cents = bcmul(1.00, 100);` ?

**Comment by frederikbosch** [comment]
Use a parser, see http://moneyphp.org/en/latest/features/parsing.html#decimal-parser

**Comment by NinoSkopac** [comment]
Awesome, thanks.
