### ISSUE TITLE
Multiply with zero error

### ISSUE THREAD

**Issue by jildertmiedema** [moneyphp/money#356]
The `GmpCalculator` gives an error in this case:
```php
Money:EUR(0)->multiply(0.8);
```

The result of the GmpCalculator is `".0"`, but the GmpCalculator `floor` and `ceil` will throw an `InvalidArgumentException`, because the value ".0" is invalid.

https://github.com/jildertmiedema/money/blob/issue-gmp-with-zero/tests/Calculator/GmpCalculatorTest.php

**Comment by sagikazarmark** [comment]
Thanks, we will look into this.

**Comment by frederikbosch** [comment]
Fixed by #357
