### ISSUE TITLE
DecimalMoneyParser() not parsing some common numeric values

### ISSUE THREAD

**Issue by judgej** [moneyphp/money#360]
We have had to put in extra checks to modify some values before passing it on to the parser. The parse throws an exception if it is given any of these:

* An empty string (arguably correct)
* \.99 (No digits before the decimal point)
* 99\. (No digits after the decimal point)

I would argue that the second two at least are unambiguous in what value they represent and should be parsed. The previous `mathiasverraes/money` package we used parsed all these, including an empty string to zero.

Our workaround is to append or prepend a "0" if the value to parse starts or ends with a decimal point.

**Comment by frederikbosch** [comment]
@judgej When is the exception being thrown? I wonder if this is a DecimalMoneyParser problem or a Money problem.

**Comment by judgej** [comment]
Good question - I should have noted that. I'll take my data fixes out and get the details.

**Comment by judgej** [comment]
ErrorException in DecimalMoneyParser.php line 54: Cannot parse ".99" to Money.

**Comment by sagikazarmark** [comment]
I am not against adding empty string parsing, although we have to make sure that all parsers support empty strings in this case.

The other two are rather parser specific I think, but sound reasonable too.

After a quick look, this regex would probably fix the decimal point ones:

`/^(?P<sign>-)?(?P<digits>0|[1-9]\d*)?\.?(?P<fraction>\d+)?$/`

For the empty string we can use a separate check.

**Comment by frederikbosch** [comment]
@sagikazarmark And we must make sure that our decimal parser can at least work with the same values that Money accepts.

**Comment by judgej** [comment]
Brilliant - much appreciated :-)
