### ISSUE TITLE
Better CurrencyPair

### ISSUE THREAD

**Issue by mdrost** [moneyphp/money#363]
Current CurrencyPair api can cause problems with really big or small factors. For example 1 Indonesian rupiah is worth 7.5×10-5 U.S. dollars (according to google). Should I really provide such factors? IMHO there should be api that takes two Money instances and take advantage for better calculation precision. This approach you can see on this site http://www.nbp.pl/kursy/xml/LastA.xml where 10000 Indonesian rupiah is worth 2.9904 Polish zloty (at this moment). You can think about it like there is TWO factors.

**Comment by frederikbosch** [comment]
@mdrost Can you explain with causes problems?

**Comment by frederikbosch** [comment]
Since the description of this issue is too limited, I am closing it. Because I can somewhat understand what you mean, I listed a possible solution to the list of ideas for the next major version.
