### ISSUE TITLE
Expose numericCode for ISOCurrencies

### ISSUE THREAD

**Issue by barryvdh** [moneyphp/money#373]
The ISOCurrencies have a numeric ISO code, can we expose that, similar to `subunitFor`?
For usage in Omnipay for example, see https://github.com/thephpleague/omnipay-common/pull/151

**Comment by sagikazarmark** [comment]
Do you mean exposing it as part of the interface or as part of that specific repository?

If it's the latter, I am not against it.

**Comment by barryvdh** [comment]
Not the interface (I assume only ISOCurrencies has it), but as part of the ISOCurrencies class itself.

**Comment by sagikazarmark** [comment]
I don't have a reason why we couldn't, but in that case you need to directly rely on that repository. It depends on your use case if it's good or bad.

@frederikbosch anything to add?

@barryvdh would you mind opening a PR?

**Comment by frederikbosch** [comment]
Hmmm... the ISOCurrencies states the following.

> Please be aware that this library solely exists to provide iso currencies for moneyphp/money. Using this library for other purposes is at your own risk. Numeric codes are not use, because we didn't need it.

Therefore, if numeric codes will serve a purpose for *functionality / domain logic* within the Money library, I will obviously agree. If, however, it is being done purely to extend our currencies class as *repository / persistence logic*, I am against it.

If this is for the latter case, I would recommend to create your own currencies repository. You are allowed to grab my code from the [ISOCurrencies](https://github.com/moneyphp/iso-currencies) package and turn it into your own needs. Then you still have the opportunity to implement the `Currencies` interface, if you want to serve your own class as repository for `Money`. It will serve as perfect boundary.

But why not simply extend the class/repository? `Money` is created for domain logic, not for currency repositories. We should focus on that, and do that well. Moreover, the amount of code you need to create your own repo [is very small](https://github.com/moneyphp/iso-currencies/tree/master/src).  

@barryvdh If I were you, I'd have the currencies in your package, even if we would extend our repository. Having that responsibility in your package, gives you the power to change. It is not worth it to have it as an abstraction that is handled by someone else.

**Comment by frederikbosch** [comment]
@barryvdh Why do you need it any how?

**Comment by barryvdh** [comment]
I have them in my package currently, even copied from that package: https://github.com/thephpleague/omnipay-common/blob/master/update_currencies.php

But with the related PR, I was trying to offload some of the money parsing etc to this package, but it feels a bit duplicated. Especially since I need your currency class to parse the money, they need to be in sync. And I can replace all of it with your currencies, except to conversion to numeric code.

But what you are suggesting, is that I either create my own OmnipayCurrencies class, which loads the currencies from my own resources, or that I extend ISOCurrencies and add the method there?

I think I can do the latter, to keep the maintenance here.

> @barryvdh Why do you need it any how?
See https://github.com/thephpleague/omnipay-common/pull/151
Gateways format the amount etc, but sometimes need to convert the currency code to numeric.

**Comment by barryvdh** [comment]
Oh I can't extend you `ISOCurrencies` class because it's final. I could create my own ISOCurrencies, but that would be duplicating your implementation, resources etc.

**Comment by frederikbosch** [comment]
> But what you are suggesting, is that I either create my own OmnipayCurrencies class, which loads the currencies from my own resources, or that I extend ISOCurrencies and add the method there?

That is what I am suggesting.

```php
namespace Omnipay\Common\Currencies;

use Money\Currencies;

final class ISOCurrenices implements Currencies {
}
```

**Comment by frederikbosch** [comment]
> Oh I can't extend you ISOCurrencies class because it's final. I could create my own ISOCurrencies, but that would be duplicating your implementation, resources etc.

Correct. But there is nothing wrong with code duplication. Having that code in your own package gives you control over it. I think you need it over time.

**Comment by frederikbosch** [comment]
> Gateways format the amount etc, but sometimes need to convert the currency code to numeric.

Do you have an example? Maybe we could create formatter with the numeric code too. Then it is more than just repository needs. Then we are solving a case.

**Comment by sagikazarmark** [comment]
Hm, I don't see this as a huge break of our principles. That information is part of the currency list, so exposing it doesn't sound like a big problem to me. But I leave it to you, you kind of own this part of the project.

**Comment by frederikbosch** [comment]
@sagikazarmark I'd rather remove it from our currency list then. If we do, there must be more to it. [The repo](http://www.currency-iso.org/dam/downloads/lists/list_one.xml) contains more data than just the minor unit and the currency code. We once decided not to incorporate the name and other fields in our package. I think I will leave it like this.

**Comment by barryvdh** [comment]
This is what would change in https://github.com/thephpleague/omnipay-common/pull/151 after the PR in #374 : https://github.com/thephpleague/omnipay-common/commit/c75183a503615740db10f8e6b80905f7897fa618

Omnipay abstract the gateways, so a customer would pass an amount + currency, similar to all. The gateway defines if it wants the decimal formatted string as amount or the integer value. Same goes for the currency, it is passed as extra parameter (in http request to the gateway driver), usually with the USD code, but sometimes the numeric code.
