### ISSUE TITLE
Support lowercase currency names

### ISSUE THREAD

**Issue by eberkund** [moneyphp/money#376]
Some financial libraries/APIs use lower case to represent different currencies, such as Stripe.

I think it would make this library more flexible if the Currency class constructor used `strtoupper()` so that if I enter "usd" and "USD" I get the same currency. I can't think of any downsides to adding this, and the ISO standard doesn't specify that one or either is wrong so it makes sense to support both.

**Comment by sagikazarmark** [comment]
Hi Erik,

Thanks for bringing this up.

Although I see this would be convenient, I also have some concerns about it. Although the main use-case of this library is to use it with ISO currencies, it's not the only possibility. So it may not cause issues in case of ISO currency names, but it could in other cases (like Bitcoin).

How about the following:

``` php
$money = new Money(100, new Currency(strtoupper($currency));
```

I don't think it's a problem if you do it in your code and we do not force and introduce such thing in Money.

What do you think?

**Comment by eberkund** [comment]
Thanks for the suggestion, that is indeed what I am doing right now.

I can see what you're saying but in the case of crypto-currencies isn't it the same situation? I can't imagine any cases where you would have currency "XYZ" and currency "xyz" refer to different things.

**Comment by sserbin** [comment]
This also results in an exception when using `Currencies\IsoCurrencies` to determine the currency scale:
```php
$usd = new Money\Currency('usd');

$currencies = new Money\Currencies\ISOCurrencies;
$scale = $currencies->subunitFor($usd); // throws Money\Exception\UnknownCurrencyException: Cannot find ISO currency usd
```
I suppose the `Currency` constructor should normalize the input *or* the  `Currencies\ISOCurrencies` should test for `contains` in a case-insensitive manner.

Or should I create a separate issue?

**Comment by eberkund** [comment]
I think it is the same issue which stems from currency symbols being case sensitive. You'll have to use `strtoupper` like @sagikazarmark suggested.

Personally I think currency symbols should be case insensitive but this is a decision for the library author/maintainers.
