### ISSUE TITLE
Allow multiply / divide methods to accept Money instance as parameters.

### ISSUE THREAD

**Issue by brunoleles** [moneyphp/money#381]
Proposal:
```php
$a	 = new \Money\Money(10, new \Money\Currency('BRL'));
$b	 = new \Money\Money(2, new \Money\Currency('BRL'));
$c	 = $a->divide($b); // $c = \Money\Money(5, new \Money\Currency('BRL'));
```

This make easier to handle some use cases when $b may or may not be a instance of money.

**Comment by sagikazarmark** [comment]
Thanks for the proposal, but I think it does not fit well into the domain. Although it might be more comfortable, I would vote on correctness in this case.

I would wait for some opinion from @frederikbosch though before closing.

Sorry for the negative answer.

**Comment by frederikbosch** [comment]
Agree with @sagikazarmark. You simply don't divide *by* another amount. You split it [according a ratio](http://moneyphp.org/en/latest/features/allocation.html#allocate-by-ratios). Correctness over comfort.
