### ISSUE TITLE
Parser doesn't accept currency object

### ISSUE THREAD

**Issue by AyubM** [moneyphp/money#386]
Are you willing to accept a pull request to make parser objects accept currency objects in addition to strings?

e.g. this currently throws an error

    $currencies = new ISOCurrencies();
    $moneyParser = new DecimalMoneyParser($currencies);
    $c = new Currency('USD');
    $moneyParser->parse('1.00', $c);

It really should accept the currency object and not force me to write `$c->getCode()` in some places and just `$c` in others.

**Comment by frederikbosch** [comment]
Good one. Actually I think it is a mistake that we accept a string. It would have been better if we only would have accepted `Currency` object. So yes, I think it is a good one. If you create a PR, please update all the parsers.

For BC reasons we should leave the allowance of the string in. In new major versions we should remove the allowance for string.
