### ISSUE TITLE
Renaming Money::equals and Currency::equals to isEquals

### ISSUE THREAD

**Issue by XAKEPEHOK** [moneyphp/money#388]
Maybe it is only my preference, but every time when I write code, I start typing as `isEquals` instead of `equals`. Every time! I think, that it is should be renamed in next major version, like as isZero, isPositive and isNegative

**Comment by XAKEPEHOK** [comment]
May be is good idea will be add additional method `isEquals` which will be like alias for `equals`

**Comment by frederikbosch** [comment]
I understand your reasoning, though I prefer to have one method for one piece of functionality. If there would have been a completely incorrect chosen name, I might have accepted an alias function for BC reasons. Since that is not the case, I close this issue. Thanks for your suggestion though.
