### ISSUE TITLE
Once currencies.php is outdated it is no longer ISO currencies.

### ISSUE THREAD

**Issue by gmponos** [moneyphp/money#392]
Hello there,

A day ago I created [this PR](https://github.com/moneyphp/money/pull/390).

No problem on that PR but I guess that if I had an application that uses this library in order to get the new ISO currencies I would have to update to the newer version of the library. Along with that I am tight in updating and keep following the changes of the library in order to get the actual ISO currencies.

Also if I do not update I might end up in my application initializing an ISOCurrencies class and since the source file is outdated you can not say that they are actually ISO.

Moreover what happens if a change is introduced in the ISO currencies and the user needs these changes fast. He will have to wait for this package to be tagged.

An argument here could be that this library solves this by introducing an abstraction layer. So having an Interface `Currency` gives the user the ability to create his own ISOCurrency with his own source and also this [PR](https://github.com/moneyphp/money/pull/391) comes to give one more solution to the developer.

I would like also to suggest one more solution. What about extracting the loadCurrencies function into a Loader Class and import that into ISOCurrencies and also create loaders for that. Making the import though a static function and adding a static variable BC can remain intact.

**Comment by frederikbosch** [comment]
@gmponos You could always create your own currencies implementation, like you are already suggesting. That way you can have your ISO currencies always up-to-date.

Regarding your suggestion, that is at least something we should discuss for a next major release. Unfortunately, it would have BC breaks if we would change the constructor (with injecting a loader) now.

**Comment by frederikbosch** [comment]
@gmponos I updated the library with up-to-date currencies.

**Comment by gmponos** [comment]
What i would've suggest was something like this:

```
<?php
namespace Money\Currencies;
use Money\Currencies;
use Money\Currency;
use Money\Exception\UnknownCurrencyException;
/**
 * List of supported ISO 4217 currency codes and names.
 *
 * @author Mathias Verraes
 */
final class ISOCurrencies implements Currencies
{
    /**
     * Map of known currencies indexed by code.
     *
     * @var array
     */
    private static $currencies;

    private static $loader;

   public function __construct() {
       self::$loader = new ISOCurrenciesLoader();
   }

    /**
     * {@inheritdoc}
     */
    public function contains(Currency $currency)
    {
        return isset($this->getCurrencies()[$currency->getCode()]);
    }
    /**
     * {@inheritdoc}
     */
    public function subunitFor(Currency $currency)
    {
        if (!$this->contains($currency)) {
            throw new UnknownCurrencyException('Cannot find ISO currency '.$currency->getCode());
        }
        return $this->getCurrencies()[$currency->getCode()]['minorUnit'];
    }
    /**
     * Returns the numeric code for a currency.
     *
     * @param Currency $currency
     *
     * @return int
     *
     * @throws UnknownCurrencyException If currency is not available in the current context
     */
    public function numericCodeFor(Currency $currency)
    {
        if (!$this->contains($currency)) {
            throw new UnknownCurrencyException('Cannot find ISO currency '.$currency->getCode());
        }
        return $this->getCurrencies()[$currency->getCode()]['numericCode'];
    }
    /**
     * @return \Traversable
     */
    public function getIterator()
    {
        return new \ArrayIterator(
            array_map(
                function ($code) {
                    return new Currency($code);
                },
                array_keys($this->getCurrencies())
            )
        );
    }
    /**
     * Returns a map of known currencies indexed by code.
     *
     * @return array
     */
    private function getCurrencies()
    {
        if (null === self::$currencies) {
            self::$currencies = $this->loadCurrencies();
        }
        return self::$currencies;
    }

    /**
     * @return void
     */
    public static function setLoader(LoaderInterface $loader)
    {
         self::$loader = $loader.
    }
}

```

One more solution could be that in someway you could require (not as dev) the `moneyphp/iso-currencies` and put in `composer require/install/update` commands to automatically fetch the ISO currencies and update the file. This means that the file must be added in .gitignore.

**Comment by frederikbosch** [comment]
@gmponos I dont like that idea. I agree that the library should have the feature you are suggesting. But using static setters to implement a feature is not the correct way forward. Moreover, we are not limiting the feature to be used now. If you create your own currencies implementation, you can use it now.

**Comment by gmponos** [comment]
> But using static setters to implement a feature is not the correct way forward. 

Yea I can feel you here. I just suggested that as a BC change that will resolve this issue. I believe we have an understand and I don't think this needs more argue. 

> One more solution could be that in someway you could require (not as dev) the moneyphp/iso-currencies and put in composer require/install/update commands to automatically fetch the ISO currencies and update the file. This means that the file must be added in .gitignore.

Please consider also researching this solution before moving to a Loader (as you said on the other issue).

**Comment by frederikbosch** [comment]
The latter suggestion was discussed before I believe. @sagikazarmark Can you remember why we choose not to implement it like that?

**Comment by gmponos** [comment]
> Can you remember why we choose not to implement it like that?

ping @sagikazarmark

**Comment by frederikbosch** [comment]
I believe that requires an internet connection to be there all the time. Second I think one cannot use composer commands in a dependency. So if one adds moneyphp as dependency to the root composer.json (or as a dependency of a dependency), one should also add the comand.

If we change current implementation, we should improve it. Not hack it. Until we have the solution I suggest to aff a feature by implementing  Currencies in your own namespace.

**Comment by sagikazarmark** [comment]
I don't really like the idea of auto-updating. That way you cannot lock to a version which is known to be working.
