### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by vladyslavstartsev** [moneyphp/money#395]
That will super awesome if you will have simple app that shows how this library works with (for example) laravel/symfony

**Comment by sagikazarmark** [comment]
Thanks for the suggestion. I'll add it to the todolist.

**Comment by frederikbosch** [comment]
Let's not do this. This is a library. We should be application agnostic. Therefore I see no reason to give examples. Moreover, I never would want to give support on such thing. Finally, this issue would be open for ages. Therefore, I rather close it.

**Comment by melokki** [comment]
@vladyslavstartsev 

I am using this library with laravel. You just add the library to your composer.json file like any other package, composer update and you are ready to go.

Examples from the documentation worked out of the box for me.

**Comment by vladyslavstartsev** [comment]
@melokki Thanks! I was having issues because 1) I didn't know what is value object 2)I didn't know how to represent it (Money, Currency and etc.) in DB.
