### ISSUE TITLE
Discuss moving to PHP 7.x

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#399]
So we have already been talking about moving to PHP 7.x, but I was against it so far, because Money 3.x is relatively young and I wanted to avoid maintaining two separate major versions.

That said, I would like to start thinking about the possibility.

I still think that we would have to support 3.x for quite some time and by support I mean backporting features from the 4.x release line whenever possible, which is probably a huge overhead.

I would like to hear some opinion on this matter.

**Comment by patkar** [comment]
Do it. There is no reason to support php 5 anymore for new releases. Any project staying at 5.x doesn't deserve it ^^

Also consider to use php 7.1 as minimum

**Comment by jaikdean** [comment]
I fully support bumping the requirement to 7.1, it brings a lot of benefits. A lot of popular open source frameworks and libraries (Symfony, Laravel, Doctrine etc) are making the switch to 7 or 7.1 in their next major release.

I'd suggest only backporting bug fixes. The current feature set is very strong, so new features are unlikely to be critical to existing projects, and in the cases where they are, upgrading to PHP 7.1 is often quite straightforward.

**Comment by Gummibeer** [comment]
Cause the active support ends this year and the security next year I also see no reason to create more releases with php5.6 or even lower in mind.
http://php.net/supported-versions.php
For me: every library that, active, supports php5 anymore slow down the acceptanceof php7.

**Comment by willemstuursma** [comment]
We would love to see a PHP 7.1 version.

**Comment by sagikazarmark** [comment]
Thanks for all the feedback. I would like to concentrate on the 3.1 release ahead of us, but after that I will start working on migrating to PHP 7, probably 7.1

That should let us clear a bunch of docblocks and remove deprecations.

**Comment by frederikbosch** [comment]
Let's conclude that version 4 will be targeting PHP 7.1+.
