### ISSUE TITLE
Parse floats and floats as strings

### ISSUE THREAD

**Issue by Aerendir** [moneyphp/money#406]
This is really a great library, but it lacks of a fundamental feature: parsing `float` numbers or `float` numbers casted to `string`.

I mean that a value like `12.89`, `'12.89'` or `'12,89'` cannot be parsed.

But this is a fundamental feature as dealing with APIs we ever return numbers in various formats.

Yes, maybe this is something we should take into account by ourselves, but providing such parsing feature should be a requirement for this library that aims at being THE money library.

What do you think about?

**Comment by unglud** [comment]
```
function parseFloat($float)
    {
        $currencies = new ISOCurrencies();
        $moneyParser = new DecimalMoneyParser($currencies);

        return $moneyParser->parse((string)$float, 'EUR');
    }
```

**Comment by unglud** [comment]
```
function toString($print = false)
    {
        $currencies = new ISOCurrencies();
        $moneyFormatter = new DecimalMoneyFormatter($currencies);
        $formatted = $moneyFormatter->format($this->money);

        if ($print) {
            return number_format((float)$formatted, 2, ',', '.');
        }

        return $formatted;
    }
```

**Comment by Aerendir** [comment]
@unglud Is this code anywhere in the library?

**Comment by unglud** [comment]
Nope, but you can just extend the library with your own class and make it behave as you willing to. Also it will insure you from possible breaking updates.

**Comment by Aerendir** [comment]
But don't you think this should be a feature of the library itself? Why should have I to write code outside the library when I have a library that deals with monetary values?

It should provide me all the ways to get a `Money` object, without taking care of what I pass... This is the purpose of a library, or not? Also because the effort is not so great as you demonstrated providing me the code in less than a minute...

Also if it doesn't deal with all the possible formats and castings a money value can have.

**Comment by unglud** [comment]
The thing is, stuff you described works well for you and for me, but for other people not. Lib do what it suppose to do. Single responsibility thing. It's just simple construction block, which suppose work perfectly in all places where you use it. If you want lib make a coffee or laundry you just extend the lib, 'cuz in this case you make specific task done.

**Comment by unglud** [comment]
What I really do not like, but it's just my opinion, that class Money itself is final, which complicate it extension.

**Comment by Aerendir** [comment]
And also `Currency` is `final`... This caused me really a lot of headaches...

I agree with the single responsibility principle... But following it too strictly I think is not good in this case.

I'm don't saying that the Money object itself should handle those situations.
I'm saying that providing a generic parser should be a really good help for those who need to parse money values in the most common ways they are represented (maybe also with currency symbols and similar things).

In my opinion this IS responsibility of this library as it wants to provide tools and utilities to manage monetary values.

And as monetary values are represented also in this way, then...

A formatter is parser in my opinion... But, yes, it is only an opinion of mine and I cannot force anyone...

**Comment by unglud** [comment]
You can start with the pull request and see how it goes.

**Comment by sagikazarmark** [comment]
@Aerendir I think there is a bit of misunderstanding: `DecimalMoneyParser` and `DecimalMoneyFormatter` *are* part of the library, only the example code presenting the usage was made up by @unglud.

So I don't think there is anything to do here.

**Comment by frederikbosch** [comment]
Exactly, use the decimal parser, see documentation. Furthermore there is also `Number::fromFloat`.
