### ISSUE TITLE
Support for parsing scientific notation.

### ISSUE THREAD

**Issue by bendavies** [moneyphp/money#408]
Hey there,

So i hit upon a bug in my API recently, where i'm accepting values of money using symfony's [MoneyType](https://symfony.com/doc/current/reference/forms/types/money.html).

Now, during some testing i managed to trigger an error in Money by submiting a large value to my API, specifically:
```
Uncaught PHP Exception InvalidArgumentException: 
"Invalid fractional part 0E+17. Invalid digit E found" at /.../vendor/moneyphp/money/src/Number.php line 219
```

What is happing here is:
1. I submit a value of `1000000000000000` to my API.
2. That is transformed to a float `1.0E+15` by [NumberToLocalizedStringTransformer](https://github.com/symfony/form/blob/7fdcf54a3a754f40dcea1d9851eac65adf6f8f97/Extension/Core/DataTransformer/NumberToLocalizedStringTransformer.php#L139) (and then `1.0E+17` by [MoneyToLocalizedStringTransformer](https://github.com/symfony/form/blob/7fdcf54a3a754f40dcea1d9851eac65adf6f8f97/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php#L80).
3. `1.0E+17` is given to the Money constructor, and fails in [Number](https://github.com/moneyphp/money/blob/149ba5943511e118bf68f9118e3c84bbe42bf94f/src/Number.php) as above.

So the questions are:
1. Does anyone know how I can get this number though symfony forms without being converted to float in scientific notation.  
2. Can `Number` add support for scientific notation?

Cheers

**Comment by bendavies** [comment]
How about we convert the float back to a string with sprintf?
https://3v4l.org/H0FVj

**Comment by unglud** [comment]
I guess you can try to parse value from symfony object before you put it to money. 
https://github.com/moneyphp/money/issues/406#issuecomment-332131006

**Comment by bendavies** [comment]
I have fixed it in my forms MoneyTransformer at the moment:
`return new Money(\sprintf('%.0f', $value['amount']), new Currency($value['currency']));`

**Comment by bendavies** [comment]
I've just noticed `Number::fromFloat`, so my `Money` is now constructed as
`return new Money(Number::fromFloat($value['amount']), new Currency($value['currency']));`

This can probably be closed.
