### ISSUE TITLE
BitcoinMoneyFormatter is not locale aware

### ISSUE THREAD

**Issue by willemstuursma** [moneyphp/money#412]
There is no way to pass in locales to the `BitcoinMoneyFormatter`. Is this by design? 

Basically, it always shows the Bitcoin symbol on the left side, no spacing and only `.` as decimal separator. Also there is no grouping if I have thousands of bitcoins to display.

**Comment by willemstuursma** [comment]
Also, slightly related:

```
 new AggregateMoneyFormatter([
                '*'   => new IntlMoneyFormatter($numberFormatter, new ISOCurrencies),
                'XBT' => new BitcoinMoneyFormatter(8, new BitcoinCurrencies())
            ])
``` 

instanciates the formatters in the correct way (e.g. one formatter to format all currencies and Bitcoin.

The formatters cannot be passed as a normal array, even though they have a `contains()` method that can be used to see if they support the currency.

**Comment by Gummibeer** [comment]
@willemstuursma if you take a look into the `DecimalMoneyFormatter` (the only other formatter without dependencies) it also uses just the english format.
I think the formatters in this package are very limited - one reason is that strings are used what makes the usage of `number_format` impossible - so it has to be rebuild.
My idea would be a combination of `chunk_split()`, `substr()` and some math. The best formatter would be one that can handle a template similar to the `date()` function to define the output string.

```php
$string = $formatter->format($money, '{i:3:,}'); // integer separated every 3 chars with ,
$string = $formatter->format($money, '{f:3:,:2:.}'); // float separated every 3 chars with , and 2 decimal separated with .
$string = $formatter->format($money, 'U{f:3:,:2:.}'); // unit on left with float
$string = $formatter->format($money, '{f:3:,:2:.}U'); // unit on right with float
```

Does this makes sense? And what should be definable? It could be also in a more coding way like:
```php
$string = $formatter->format($money, Formatter::TYPE_FLOAT, 3, ',', 2, '.', Formatter::UNIT_LEFT);
```

**Comment by willemstuursma** [comment]
I don't want to define any output templates, I need a formatter that I can just pass the locale and it will deal with it.

I'm not an expert on which formatting applies in each territory, so I need the formatter to figure this out for me. 

I just need `$formatter->format($money, string $locale);` It works perfectly fine for the ISO currencies. 

Personally, I wouldn't go for any string chopping / concatination but instead try to reuse some of the goodies from `ext-intl`.

**Comment by willemstuursma** [comment]
I can do a PR if you want?

**Comment by frederikbosch** [comment]
@willemstuursma I think that if you want to have an internationalized formatted bitcoin, you should use the `NumberFormatter` from ext-intl and the `IntlMoneyFormatter`.

```php
$currencies = new AggregateCurrencies([
  new ISOCurrencies(),
  new BitcoinCurrencies()
]);

$xbtNumberFormatter = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY);
$xbtNumberFormatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, "\xC9\x83");

$formatters =  new AggregateMoneyFormatter([
  '*'   => new IntlMoneyFormatter($isoNumberFormatter, $currencies),
  'XBT' => new IntlMoneyFormatter($xbtNumberFormatter, $currencies)
]);
```

[This gives you the proof that you can use intl even with your own currency](https://3v4l.org/AVVCO).

But that leaves you with the problem that the locale must be injected instead of passed to a method, which might be more what you are looking for. In that case, I advice you to create a factory within your own namespace. An example what the class might look like is as follows.

```php
namespace OutsideMoney;

final class LocaleMoneyFormatterFactory
{

  private $currencies;

  public function __construct(Currencies $currencies) {
    $this->currencies = $currencies;
  }

  public function factory(string $locale): MoneyFormatter
  {
    $xbtNumberFormatter = new \NumberFormatter($locale, \NumberFormatter::CURRENCY);
    $xbtNumberFormatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, "\xC9\x83");

    return new AggregateMoneyFormatter([
      '*'   => new IntlMoneyFormatter($isoNumberFormatter, $this->currencies),
      'XBT' => new IntlMoneyFormatter($xbtNumberFormatter, $this->currencies)
    ]);
  }

}
```

This does not belong in the Money namespace because what is inside the factory is not necessarily  restricted to the domain of this library. There can be all sorts inputs to a factory.

As this an answer to the issue at hand, I am closing it. We can always reopen in case there is reason for it.

**Comment by willemstuursma** [comment]
Hi @frederikbosch, I can't get your example to work: 

```
<?php

require  "../vendor/autoload.php";

$currencies = new \Money\Currencies\AggregateCurrencies([
    new \Money\Currencies\ISOCurrencies(),
    new \Money\Currencies\BitcoinCurrencies()
]);

$isoNumberFormatter = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY);

$xbtNumberFormatter = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY);
$xbtNumberFormatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, "\xC9\x83");

$formatters =  new \Money\Formatter\AggregateMoneyFormatter([
    'XBT' => new \Money\Formatter\IntlMoneyFormatter($xbtNumberFormatter, $currencies),
    '*'   => new \Money\Formatter\IntlMoneyFormatter($isoNumberFormatter, $currencies)
]);


$amount = Money\Money::XBT(1);

var_dump($formatters->format($amount));
```

Output:

```
string(7) "XBT0.00"
```

Are you sure you can use the `IntlFormatter`?

**Comment by frederikbosch** [comment]
@willemstuursma That is related to subunits since `Money\Money::XBT(1)` is actually 0.00000001 XBT. The number of subunits for Bitcoin is 8. So you will have to initialize a larger amount, or change the number of decimals in the `\NumberFormatter`.

**Comment by willemstuursma** [comment]
Okay, but then the symbol is still not used (even though it is set).

**Comment by willemstuursma** [comment]
> change the number of decimals in the \NumberFormatter.

Shouldn't it be set automatically by the `IntlMoneyFormatter` based on the `Currency`?

**Comment by willemstuursma** [comment]
@frederikbosch do you have any more ideas, or should I dive into it?

**Comment by frederikbosch** [comment]
> Shouldn't it be set automatically by the IntlMoneyFormatter based on the Currency?

We had a discussion on this topic when I proposed merging the `Formatter` and its implementations in. I can remember I was of the same opinion as you are now. However, we decided not got for it. Cannot recall why.
