### ISSUE TITLE
How deal with custom subunit

### ISSUE THREAD

**Issue by Viperoo** [moneyphp/money#413]
Hi,

I use this library in one project, great job!

I have problem with saving custom prices in format 0.1234 for USD or EUR.

I know that I can implement my own currency with my own subunit as here https://github.com/moneyphp/money/blob/master/src/Currencies/BitcoinCurrencies.php#L36

Do you know a simple way to work around this?

Cheers

**Comment by Gummibeer** [comment]
No, you have to define your own `Currencies` that handles existing or your custom `Currency`. The easiest way would be to override the `ISOCurrencies->loadCurrencies()` and load your own/customized list. https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php#L95
The subunit is loaded from the `minorUnit` key. https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php#L40

**Comment by sagikazarmark** [comment]
You might be interested in #391 which lets you instantiate your custom currency list. If you ever need further ISO currencies (and you don't want to add each of them one by one, and of course don't need to support larger amount of subunits) you can wrap your custom one and the ISO one in an aggregate with yours being the first. I believe this is a cleaner approach than extending the ISOCurrencies class.

For the moment you can just copy the class and use the one from this library whenever it gets merged and released.

**Comment by frederikbosch** [comment]
Solutions given. Issue closed.
