### ISSUE TITLE
final class Money

### ISSUE THREAD

**Issue by unglud** [moneyphp/money#414]
Is there any reason why Money class is final?
I would like to extend class and modify it's behaviour in some cases, but now it's hard to do.

Thanks!

**Comment by sagikazarmark** [comment]
Yes, it is a design decision we made and discussed quite a few times (you can search for it in the issue tracker).

Modifying behavior is exactly one thing that we wanted to forbid, adding behavior is another question, but it's forbidden for now too.

What is your use case? Usually there is an other way that's usually cleaner than extending the money class.

This will probably not change.

**Comment by unglud** [comment]
I have several use cases
First simplified constructor
Instead `Money::EUR(500)` I use `new Money(5)` 'cuz I have only one currency and want to put in argument what ever I want.

Second, I have legacy object, which methods return numbers, and I want them return Money instead. So I have something like `Money::createFrom($oldObject)` and now I have `$oldObject instanceof Money`, where I can do like `$oldObject->getNetValueOfLols() instanceof Money`

My current implementation is I have `MyMoney` class which have parameter `$this->money  instanceof Money` and to be able use `MyMoney->add` for example I do this ugliness: 
```
public function add($addend)
{
    return new self(0, $this->money->add($addend->getMoneyObject()));
}
```
It pretty messy explanation I agree, but all I want to say, everything will be much much easer if I could just simply extend Money class.

Here gist, if you want
https://gist.github.com/unglud/3215dd0e5f77ecad135048fd56533e66

**Comment by Gummibeer** [comment]
@unglud if you want to make the public methods of `Money` available on your `MyMoney` you can use the overloading `__call` method http://php.net/manual/de/language.oop5.overloading.php#object.call . With a simple check like:

```php
if(method_exists($method, $this->money)) {
  return call_user_func_array([$this->money, $method], $arguments);
}
```

This code isn't tested so could be that I forgot one line or so - but this is a classic way to make methods from other classes available. And I would rename your `MyMoney` to `MoneyManager` - after this rename it's exactly what it does and no more reason to extend the original class.

**Comment by sagikazarmark** [comment]
> First simplified constructor
> So I have something like Money::createFrom($oldObject)

It's a common misconception that you have to put all these functions into static methods of a class, but PHP is not Java, you can simply create functions which do that for you. Especially if it contains some kind of business logic, it has no place in the money value object. Some would argue that what Money is depends on the domain (which is true), but you can wrap money if necessary.

> It pretty messy explanation I agree, but all I want to say, everything will be much much easer if I could just simply extend Money class.

Extension in terms of extends is overused and abused in most of the cases IMO, that's why we decided to make Money final.

**Comment by spiro79** [comment]
I'm facing some issues on my application while unit testing because of the final class.

On our unit tests we try not to instantiate any external dependencies but being a final class it is not possible for PHPUnit to mock it.

I see your point for composition over inheritance but shouldn't that be left for the implementation to decide?

If you want to leave it final you could provide an interface, that way you can easily provide the means to mock your class.

**Comment by Gummibeer** [comment]
I have to support @spiro79 - in my opinion it's not the task of the package provider to protect the User/Dev. No one can destroy your work if it's not final but it makes a lot much harder for the user.

**Comment by sagikazarmark** [comment]
I think a few concepts are being mixed up here. Money is not a dependency in terms being *injected* to somewhere. You don't inject (or mock) string literals or integers, do you? Money is also rather a value, not a service, so it should not get *injected*. It doesn't mean of course that you cannot pass it to another object to *set it's state*, but it's not dependency injection.

So ultimately, you shouldn't mock Money in the first place.

Adding an interface has also been discussed quite a few times and IMO it's also a kind of abusing OOP: there is no alternative implementation that does things differently than the current one, therefore adding an interface would merely be a hack to fool PHP and allow things like mocking (which should not be necessary in the first place).

**Comment by frederikbosch** [comment]
Discussed thousand times. Get over it, it is not final. Search the issues why.

@sagikazarmark I really do not understand why you keep replying to this. Waste of your time. I say: immediate closure and lock conversation.

**Comment by sagikazarmark** [comment]
You mean it's final, right? Hehe

Jokes aside: I hate to turn other people down because they don't understand/accept this decision. I try to discuss and find a solution...which I believe sometimes succeeds.
