### ISSUE TITLE
Composer downloading version 2.0.3

### ISSUE THREAD

**Issue by timidboy** [moneyphp/money#417]
A rather stupid question, but why is composer always picking up version 2.0.3?

I'm running it on php 5.6.30

I tried deleting the composer cache, result is the same. Also noticed the latest build is failing. Can it be the reason?

Thanks!

**Comment by unglud** [comment]
try command:
`composer why-not moneyphp/money ^3`
you will see the reason

**Comment by timidboy** [comment]
Oh. I'm so stupid. I was requiring `money/money` instead of `moneyphp/money`.
Sorry for the trouble. Thanks!
