### ISSUE TITLE
Do you know any javascript formatter?

### ISSUE THREAD

**Issue by Aerendir** [moneyphp/money#420]
I'd like to format a MoneyPHP object using Javascript (in React): do you know any javascript library that can help?

**Comment by sagikazarmark** [comment]
How do you want to format a PHP object in javascript? I mean: you somehow need to return the object to javascript in a string representation, so why not format the value there? Unfortunately I don't use too much JavaScript, so I can't help with that.

**Comment by Aerendir** [comment]
I worked around this with a Doctrine embeddable, saving also the converted amount other than the base amount... Anyway, thank you for your reply!
