### ISSUE TITLE
Converter is also final

### ISSUE THREAD

**Issue by ossinkine** [moneyphp/money#435]
There are many issues where discussed why Money class is final, it's value object and so on.
But why is Converter is final? It also doesn't implement any interface, so no way to mock it in tests. Converter is not value object, right?

**Comment by Gummibeer** [comment]
How far I got - all classes except of the Currencies are final ones.
So I think that it is a general decision.

**Comment by ossinkine** [comment]
@Gummibeer Currencies are also final. I can understand why value objects should be final, but why should services be?

**Comment by Gummibeer** [comment]
I mean the interface: https://github.com/moneyphp/money/blob/master/src/Currencies.php

**Comment by ossinkine** [comment]
Final interface? Seriously?

**Comment by sagikazarmark** [comment]
Making classes final by default is generally a good idea when no extension (mean: inheritance) is expected. If you need to add behaviour you can use composition to create your own wrapper or simply copy the class you want to modify.

**Comment by ossinkine** [comment]
I agree, but if this is a service I expect it implements some interface and my new service (with the composition) also will implement it. And when I test my class which depends on this service I will mock interface which impemented by this class.

**Comment by sagikazarmark** [comment]
Sorry, really don't see the issue with what you described.

**Comment by Gummibeer** [comment]
The issue is that there is no Interface for the final classes that I can use for custom implementations to have a contract what this class offers.
Interfaces are also awesome for dependency injection.

So the primary question isn't why everything ist final, this is discussed enough and a mix of standards and subjective opinions, but why the final classes doesn't have Interfaces that I can reuse to customize and extend some behaviors.

---

And sorry for the silly first comments.^^ I haven't thought about.

**Comment by ossinkine** [comment]
@Gummibeer Correct.
@sagikazarmark Let's look at a following example.
I have some class which depends on `Converter`:
```php
class SomeService
{
    private $converter;

    public function __construct(Converter $converter)
    {
        $this->converter = $converter;
    }

    public function doSomething()
    {
        // ...
        $this->converter->convert($money, $counterCurrency, $roundingMode);
        // ...
    }
}
```
How do you propose to add new behavior to `Converter`? And how should I write a unit test for `SomeService`?

**Comment by Gummibeer** [comment]
And a basic example usecase why it's usefull to extend `Converter` would be magic methods like `convertToUSD` which is catched by `__call` and a check if the part after `convertTo` is an available currency.
There are even more examples for other classes - these don't have to be in the package but it will help to be able to add these methods in a simple way without creating a whole new `Converter`.

**Comment by ossinkine** [comment]
@Gummibeer Actually you can impement your example right now with the composition:
```php
class NewConverter
{
    private $converter;

    public function __construct(Converter $converter)
    {
        $this->converter = $converter;
    }

    public function __call($method, $arguments)
    {
        if (strpos($method, 'convertTo') === 0) {
            // some else checks
            $this->converter->convert(...);
        }
    }
}
```
My issue related to LSP. I want to be able to transparently replace original converter with my new one where it is needed. For example `CachedConverter` like a [CachedCurrencies](https://github.com/moneyphp/money/blob/master/src/Currencies/CachedCurrencies.php).

**Comment by Gummibeer** [comment]
@ossinkine Yes, but after this `NewConverter` isn't checkable to be a converter - with an interface `ConverterContract` I can use it for dependency injection, instance of checks and so on.
But yes, adjusting the existing logic is the best usecase.

**Comment by frederikbosch** [comment]
I believe we just added the `Converter` class as generic contract for combining `Exchange` and `Currencies`. The latter two were separate concepts before. The `Converter` creates a simple API for conversion. I don't see a problem with adding an interface, but I also do not see why you want to decorate the converter.

@ossinkine If you want to cache, what do you want to cache? Currencies or Exchange? You can inject `CachedCurrencies` or create a CachedExchange. The library is lacking the `CachedExchange`, it would be an addition to the library to have it.

**Comment by frederikbosch** [comment]
Closed until there is an explanation that explains the need to interface the converter. I am happy to discuss it.

**Comment by ossinkine** [comment]
`CachedConverter` might cache a result of conversion. There are a lot of cases why decoration is needed, `CachedConverter` is one of them. Just try to imagine.
Another issue I faced is unit test. There is no way to test class which use `Converter` without instantiate the converter. If the test creates a new converter it is not the unit test anymore.

**Comment by mbessolov** [comment]
@ossinkine if there is a dependency in your code on the Converter, and you want to replace the Converter  implementation with your own implementation, why not just modify the dependency in your code then?

If the dependency exists in somebody else's code, then  you may ask them to modify the way the dependency is declared (as using an interface is not the only option). After all, if they want their system to be easily customized, they should provide others a way to do it.

And if they don't want their system to be easily customizable, the interface wouldn't help either way, as they will not use it.

**Comment by ossinkine** [comment]
@mbessolov Why someone should create own interface for converter and use it if converter is a part of this library and it is logical that it should be placed here? If two or more independend systems use converter, they will have two different interfaces.
I understand I can stop using this library and create own new one, but this issue was created because we all want to make this library better.
Besides, I have outlined the concrete problem and so far no one has proposed a concrete solution.

**Comment by frederikbosch** [comment]
> Besides, I have outlined the concrete problem and so far no one has proposed a concrete solution.

Welcome to open source. If you have a concrete problem, you propose the solution yourself. There is even a name for it: Pull Request. Maintainers have no obligation what-so-ever to propose a concrete solution for a specific problem that *you* seem to have. If you want to have things done, create a PR. And then we can discuss that.

**Comment by ossinkine** [comment]
@frederikbosch I can create PR where create an interface but you will close it and say something like "I don't see the issue in final class with no interface".
So I've created this issue first to discuss here.
Do I create such a PR?

**Comment by frederikbosch** [comment]
@ossinkine I fail to see the need for the interface, but I also do not see any harm in it. If it makes you - and perhaps other - happy, we could merge it. That said, I am not the only maintainer of the library, and their arguments might lead to the outcome that the PR will not be merged. Nonetheless, the amount of time it takes to create the PR is already much less than the time invested in this discussion...
