### ISSUE TITLE
Deal with numbers represented with E-XX

### ISSUE THREAD

**Issue by sotsky** [moneyphp/money#444]
Using converter with crypto currencies often can got very small numbers which represented like `5378617246039E-6`

Right now `\Money\Number::fromString` do not handle those numbers correctly.
It make sense to add something like
```
$number = rtrim(sprintf('%.20F', $number), '0')
```
at the beginning of the method.

**Comment by sstok** [comment]
> 5378617246039E-6

That seems an integer overflow, are you using a 32bit PHP version or don't have the gmp extension installed?

**Comment by sotsky** [comment]
It's valid exponential form of the float numbers.

see http://php.net/manual/en/language.types.float.php
 Floating point numbers (also known as "floats", "doubles", or "real numbers") can be specified using any of the following syntaxes:
```
<?php
$a = 1.234; 
$b = 1.2e3; 
$c = 7E-10;
```

**Comment by bendavies** [comment]
@sotsky https://github.com/moneyphp/money/issues/408
use `Number::fromFloat`

**Comment by sotsky** [comment]
@bendavies 
Issue occur when I use converter at \Money\Converter::convert:48
So that is internal issue.

**Comment by bendavies** [comment]
Ah yes, I see the issue. I'll try submit a PR today.

**Comment by sotsky** [comment]
Thanks

**Comment by bendavies** [comment]
@sotsky can you see if https://github.com/moneyphp/money/pull/445 fixes your problem?

**Comment by frederikbosch** [comment]
Because I believe BCMath and GMP don't return any number with the exponential character `e`. Only PHP does that. My advise would be to install one of the two extensions. The Money library will automatically do the switch.

**Comment by sotsky** [comment]
@frederikbosch  @bendavies 
Yes that fixes my issue.

I have BCMath installed.

**Comment by frederikbosch** [comment]
@sotsky Which calculation is resulting in an value with exponential character? Because I don't think BCMath will do that.

**Comment by sotsky** [comment]
@frederikbosch 

I have following exchange
```
Money\Exchange\ReversedCurrenciesExchange {
  exchange: Money\Exchange\FixedExchange {
    list: [
      "BTC" => [
        "UAH" => "273509.80"
      ]
    ]
  }
}
```

and than call
```
$converter->convert($moneyParser->parse(1, 'BTC'), new \Money\Currency('UAH'))->getAmount()
```

**Comment by frederikbosch** [comment]
Ah, that is something we can work with, thanks! I will test and fix it.

@bendavies Thanks for your work. I am going to have a look at the example above, compare the results between current code and your PR and see what is the best solution to this problem.
