### ISSUE TITLE
Float conversion ratio raises exception on some locales (v3.1.0 only)

### ISSUE THREAD

**Issue by insbrook** [moneyphp/money#446]
```
$exchange = new FixedExchange([
    'EUR' => [
        'USD' => 1.25
    ]
]);

$converter = new Converter(new ISOCurrencies(), $exchange);

$eur100 = Money::EUR(100);
$usd125 = $converter->convert($eur100, new Currency('USD'));
```
In some cases this code (from documentation) raises error 
`Invalid integer part 1,25. Invalid digit , found` at `src/Number.php:234`
It depends on active locale. For example on ru_RU.UTF-8 float `1.25` ratio becomes a `"1,25"` string. Meanwhile Number::fromString($value) can't deal with comma separated number string.

**Comment by frederikbosch** [comment]
Version 3.0.x is not doing that?

**Comment by sagikazarmark** [comment]
No, it is not.

Unfortunately this is an issue that occurs when float is casted to string on specific locales.

There is no float casting in version 3.0.x here:

https://github.com/moneyphp/money/blob/v3.0.0/src/Converter.php#L42

But there is on the latest master.

Trying to write test for this now.

**Comment by sagikazarmark** [comment]
Looks like the solution is rather trivial: do not cast float to string at all. Sprintf seems to be a good alternative, we just have to use `Number::fromFloat` everywhere.

**Comment by frederikbosch** [comment]
@sagikazarmark I can remember having a discussion on topic before... but we should simply not accept a float. What if the conversion rate `1.25` (float) would be `'1.25'` (string)?

**Comment by sagikazarmark** [comment]
As far as I can see the conversion ratio can only be float right now. At least based on docbloc, and I think it's fine.

Also, this works: https://3v4l.org/KffDE

**Comment by frederikbosch** [comment]
Maybe for now. But any floating point has given us nothing but trouble. If we are moving towards a new version, we strict typing, we should only accepts strings and integers. Maybe we should a `fromScalar` then, which is accepts `int`, `string` and `float` and does the right thing depending on the type.

**Comment by sagikazarmark** [comment]
The conversion ratio will always be float, so we have to deal with float values at some points.

@insbrook can you check if #447 solves your problem?

**Comment by insbrook** [comment]
Yes, that's it, problem solved. 
Thanks a lot.

**Comment by chekalskiy** [comment]
@frederikbosch I think we should reopen this issue because problem still here:

```php
 $full_summ = new Money(1000000, new Currency('RUB'));
 $vat_summ = $full_summ->divide(1.18);

echo 'Should be: ' . round(10000/1.18, 2);
echo "<br>\n";
echo 'We have: '. $vat_summ->getAmount()/100;
```

Gives us:
```
Should be: 8474,58
We have: 8474,57
```

After debugging I found that it's because of `divide($amount, $divisor)` — there we have `return (string) $result` — on some locales (e.g. ru_RU.UTF8) it creates 847457,627 instead of 847457.627 and after that that part after the comma are gone in further operations.

**Comment by sagikazarmark** [comment]
Can you please open a separate issue for that? You can address it to be a general solution for this problem, I suspect we have to review all string casting operations.
