### ISSUE TITLE
Allow arithmetical operations with zero or null money without conversion?

### ISSUE THREAD

**Issue by Itach1Uchixa** [moneyphp/money#449]
Hi there!
```php
$usd = Money::USD(0);
$uzs = Money::UZS(100000);

$usd->add($uzs);
```
The code above will throw "InvalidArgumentException: Currencies must be identical" exception.
It will make sense if it would work.
And to make it work one must have to convert 0$ or 0 UZS or vice versa. 
It will be useful if it would work without conversion e.g. like null object or something like that.
As a simple solution it can be done with whatever named null currency object. Or with simple amount check if amout is 0 than allow to add or subtract.

Simple case of it's usefulness:
```php
class TariffPlan
{
    /**
     * @var Fee[]
     */
    protected $extraFees;
    
    /**
     * @return Money
     */
    public function totalExtraFee(): Money
    {
        // total is 0 amount of money by default
        // method hasn't return plain null if there are no extra fees
        // as a result it will avoid tons of type checks and make life easier
        $total = Money::null();
        
        foreach ($this->extraFees as $fee) {
            $total = $total->add($fee);
        }
        
        return $total;
    }
}
```

**Comment by Itach1Uchixa** [comment]
`$someVar`

**Comment by frederikbosch** [comment]
See Converter and Exchange, and corresponding docs.

**Comment by frederikbosch** [comment]
Also see Money::sum and its discussion. You might want to contribute your opinion there.

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say

**Comment by Itach1Uchixa** [comment]
I know that there are ways to do it. I already read the documentation moreover I have experience of doing it. Please read it again and try to understand what I'm trying to say
