### ISSUE TITLE
Example from documentation dont work

### ISSUE THREAD

**Issue by windows1087** [moneyphp/money#450]
I'm trying to use the https://github.com/moneyphp/money package for PHP (version 7.1 with Laravel 5.5 on debian).

The documentation has this section: http://moneyphp.org/en/latest/features/parsing.html#intl-localized-decimal-parser

But if i copy this code, they throw an exception "Cannot parse 1.000,00 to Money. Number parsing failed: U_PARSE_ERROR".

I have installed the intl extension. This section works fine: http://moneyphp.org/en/latest/features/parsing.html#intl-money-parser

Originally posted at: https://stackoverflow.com/questions/48624110/moneyphp-dont-work-like-in-documentation

**Comment by sagikazarmark** [comment]
Thanks for reporting this issue. Looks like the code is indeed wrong (probably a copy&paste error).

Please see #451 for the fixed example.
