### ISSUE TITLE
Make Number and/or Calculators internal

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#465]
Currently we use Number internally for a lot of things, but as far as I can see it's rarely present in interfaces. Let's make it internal, so we can do whatever we want with it.

The calculator interface is a bit harder from this point of view. IMO we can leave it public, but in that case we cannot use Number in type hints.

**Comment by bmeynell** [comment]
@sagikazarmark - I've found `Number` to be a nifty little utility for representing a [Decimal](https://en.wikipedia.org/wiki/Decimal) - somewhere between the "numeric" PHP primitives and a full-fledged `Money` object.
