### ISSUE TITLE
Attempting to allocate an amount smaller than the number of ratios errors

### ISSUE THREAD

**Issue by davidomelettes** [moneyphp/money#466]
I'm not certain what the expected behaviour is here, but the following produces an `Undefined offset` error:

`(new Money(1, $currency))->allocate([1, 1])`

I would have thought the right thing to do is treat this case in the same way as other remainders, and return `[1, 0]`.

**Comment by sagikazarmark** [comment]
Thanks for reporting. Can you check if the linked PR solves the issue for you?

**Comment by davidomelettes** [comment]
@sagikazarmark Linked PR resolves the issue, thanks.

**Comment by sagikazarmark** [comment]
Released 3.1.3 with the fix
