### ISSUE TITLE
Construct Money from JSON stdClass

### ISSUE THREAD

**Issue by willemstuursma** [moneyphp/money#474]
The `Money` object can be serialized to JSON, however there is no way to construct it back.

Can we add a method `public static function Money::fromJson(stdClass $object): Money`?

I prefer taking a `stdClass` as the json decode is not a reposibility of `Money` and it may be part of some deeper nested structure.

**Comment by sagikazarmark** [comment]
stdClass is not a contract, so I would rather not accept it as a parameter.

Why would this method be better than `new Money($json->amount, new Currency($json->currency))`?

**Comment by willemstuursma** [comment]
Sure, that is also very easy but a convenience function would even be handier:
```php
$json = json_decode(...);
$money = Money::fromJson($json);
```

`stdClass` is the default output from `json_decode`, but arrays are also very common.

**Comment by sagikazarmark** [comment]
Well, after decoding from JSON it does not really have anything to do with JSON, so `fromJson` sounds odd to me.

Using array sounds a bit more logical to me: that's what we output from `jsonSerialize` and I think it's easier to work with.

Also with arrays, we can support multiple representations:

- `['amount' => '123', 'currency' => 'EUR']`
- `['123', 'EUR']`

An alternative I can think of is a `Money\json_decode` function which internally does the decoding, validates the value and just instantiates the Money object.

**Comment by willemstuursma** [comment]
> Well, after decoding from JSON it does not really have anything to do with JSON, so fromJson sounds odd to me.

It's supposed to be the inverse of `json_encode($money);`.

**Comment by sagikazarmark** [comment]
```php
$json = new \stdClass();
$json->amount = '123';
$json->currency = 'EUR';

$money = Money::fromJson($json);
```

When you call that method, you can no longer talk about json, only about an object which is a result of a `json_decode` call. If json decoding is not part of the job then it's not about json anymore from money point of view. No matter what your use case is.

**Comment by willemstuursma** [comment]
Maybe the naming could be improved.

**Comment by sagikazarmark** [comment]
I would also be more comfortable with implementing one of the two solutions suggested above instead of using stdClass.

**Comment by willemstuursma** [comment]
This is an example use case I had in mind:

```php
<?php

class ChargebackNotification
{
    public function addPayload(Payment $payment, Money $amount)
    {
        $this->payload = json_encode([
            "amount" => $amount,
            "payment_id" => $payment->getPrimaryKey()
        ]);
    }

    protected function getAmount(): Money
    {
        $decoded = $this->getPayload(); /** @var stdClass $decoded */
        return Money::fromJson($decoded->amount); //?
    }
}
```

I hope this clarifies it a bit. As you can see, the encoded Money object is part of a larger structure.

**Comment by sagikazarmark** [comment]
Maybe something like #475 ?

**Comment by gmponos** [comment]
IMHO the example above is against defensive programming therefore I believe that it should not be an argument for implementing a feature like this.

Encoding/decoding the object will lead you to generate new objects each time that might end up with unwanted results.

Doing a long shot here I believe that this class `ChargebackNotification` will be used to an API or for storing it to the database. In both cases this has nothing to do with the implementation of your Client or Database.

For instance doctrine supports having a field as Json. Guzzle client supports converting an array or an object to a JSON automatically etc etc.

So IMHO you shouldn't encode it in the first place.

Sorry if I am not getting it maybe I miss the bigger picture.
