### ISSUE TITLE
Convert a Money object from one subunit to another.

### ISSUE THREAD

**Issue by gmponos** [moneyphp/money#476]
I have the following scenario.

We use the SubUnits from IsoCurrencies to handle our Money objects (for formating and parsing).

But we need to do requests to payment providers that have their own SubUnits. For instance there are some Payment Providers taht the minorUnit for HUF would be 0.

So my Money object has an amount of 1 HUF as `100`. What I need to do is convert that to a Money object which has amount of 1 HUF as `1`.

Would you be willing to accept a PR with a class like this:

``` php
<?php

namespace Money;

use Money\Currencies;
use Money\Exception\FormatterException;
use Money\Money;

class SubunitCurrencyConverter
{
    /**
     * @var Currencies
     */
    private $from;

    /**
     * @var Currencies
     */
    private $to;

    public function __construct(Currencies $from, Currencies $to)
    {
        $this->from = $from;
        $this->to = $to;
    }

    /**
     * @param Money $money
     * @param int $roundingMode
     * @return Money
     * @throws SubunitCurrencyConverterException
     */
    public function convert(Money $money, $roundingMode = Money::ROUND_HALF_UP)
    {
        if (!$this->to->contains($money->getCurrency()) || !$this->from->contains($money->getCurrency())) {
            throw new SubunitCurrencyConverterException('Currency must be contained in both lists of converter');
        }

        $baseCurrencySubunit = $this->from->subunitFor($money->getCurrency());
        $counterCurrencySubunit = $this->to->subunitFor($money->getCurrency());
        if ($baseCurrencySubunit === $counterCurrencySubunit) {
            return $money;
        }

        $subunitDifference = $baseCurrencySubunit - $counterCurrencySubunit;
        $ratio = pow(10, $subunitDifference);
        return $money->multiply($ratio, $roundingMode);
    }
}
```

**Comment by sagikazarmark** [comment]
I think you can already achieve this with the current converter: 

- Set up a fixed exchange with the currency with 1 as the ratio
- Pass the same currencies with different subunit to the converter

Alternatively you can implement a constant exchange which always returns one, no matter the currencies. That way you can spare some configuration.

**Comment by gmponos** [comment]
I thought about implementing a Converter but this is the signature of the Converter

`public function convert(Money $money, Currency $counterCurrency, $roundingMode = Money::ROUND_HALF_UP)`

It requires the $counterCurrency which I don't need and passing it for the above scenario and ignoring it afterwards feels kinda dirty. That's why I asked about it.

**Comment by gmponos** [comment]
I am not sure if my case was clear enough since I didn't understand how returning a fixd exchange of `1` will solve my problem. So I will explain a little better.

Both my application and the payment provider reads amounts a minor units in their APIs but I use IsoCurrencies which says that the HUF has 2 decimals but Payment Provider says that HUF has 0 decimals


| amount | our minor amount | minor amount that I must send 
|---------|--------------------|---------------------------------
| 1 HUF   | 100 |  1
| 2 HUF  | 200 | 2
| 5000 HUF | 500000 | 5000

and vise versa there are other payment providers that we need the oposite

| amount | our minor amount | minor amount that I must send 
|---------|--------------------|---------------------------------
| 1 IDR   | 1 |  100
| 2 IDR | 2 | 200
| 5000 IDR | 5000 | 500000

and bit coin too. We have 8 and they have 6

| amount | our minor amount | minor amount that I must send 
|---------|--------------------|---------------------------------
| 1 BTC | 100000000 |  1000000

**Comment by sagikazarmark** [comment]
Since you already typehint `PayPalCurrencies`, you could avoid the extra `ISOCurrencies` injection and implement the subunit difference logic directly in `PayPalCurrencies`.

@gmponos does the above code solve your problem?

Although I would like to keep the core library as minimal as possible (it's not the LOC, it's maintainability and complexity of the library), it's clear that there are tons of use cases around this library and the community could use some central place to share code and knowledge. I would like to support that, I'm just not yet completely sure what would be the best way to do it (accept community packages to be in this org, documentation pages, an awesome-money repo, etc).

I would be happy to hear your opinion about the matter.

**Comment by frederikbosch** [comment]
This has not been followed up, and there seems to be a fine solution outside this library. Closing.
