### ISSUE TITLE
New currency denominations: STN and MRU

### ISSUE THREAD

**Issue by pascal-hofmann** [moneyphp/money#477]
See https://status.openexchangerates.org/incidents/mtm1d2f4f05z

**Comment by frederikbosch** [comment]
The ISO 4217 currently [only accepted the Mauritanian currency](https://www.currency-iso.org/en/shared/amendments/iso-4217-amendment.html). Can you create a PR with the updated currencies? You can do that in [the separate package](https://github.com/moneyphp/iso-currencies). Therefore I close it here.

**Comment by pascal-hofmann** [comment]
The currency of Sao Tomé and Príncipe was accepted with [ISO 4217 amendment number 164](https://www.currency-iso.org/dam/downloads/dl_currency_iso_amendment_164.docx).

Thanks for the pointer to the correct package. I've created a [PR for moneyphp/iso-currencies](https://github.com/moneyphp/iso-currencies/pull/7).

**Comment by frederikbosch** [comment]
I merged the currencies PR and tagged a new release (3.1.1). Now we should be able to update the currencies here.
