### ISSUE TITLE
Rounding to the "Nearest" Whole Unit of Currency 

### ISSUE THREAD

**Issue by broberts-mrmc** [moneyphp/money#480]
While I've looked through the code and documentation, I have not found a built-in method for rounding, using any of the available rounding methods (http://moneyphp.org/en/latest/features/operation.html#rounding-modes), to the "nearest" whole unit of currency.  Am I just over looking it? If so, what is the method?

Inputs and [expected] corresponding outputs:
```
ROUND(0.01 USD) = 0.00 USD
ROUND(0.49 USD) = 0.00 USD
ROUND(0.50 USD) = 1.00 USD
ROUND(0.51 USD) = 1.00 USD
ROUND(1.01 USD) = 1.00 USD
ROUND(1.49 USD) = 1.00 USD
ROUND(1.50 USD) = 2.00 USD
ROUND(1.51 USD) = 2.00 USD
```

**Comment by oligus** [comment]
This would be really nice to have, here is what I'm doing at the moment:

```
$money = Money::USD(151);
$rounded = round($money->getAmount(), -2);
$result = Money::USD($rounded); // 200
```

**Comment by broberts-mrmc** [comment]
@oligus Well, I guess that's two votes!  For such a well-developed library/project, it's surprising this kind of rounding isn't needed more often and isn't yet incorporated in Money.  I'm sure there are a few nuances to a complete implementation including currency agnosticism.

The logic in your solution is more concise than mine, which is also a currency specific (USD) solution.  I attempted to avoid native, numeric types (e.g. integer, float) and operations in the intermediate logic since in any instance that could, potentially involve large values.  As you know, PHP's built-in `round()` function always returns a float, and therefore has the storage and operational "features" of that type.  

My solution should probably also include some exception handling for the various exceptions thrown by Money.  I contemplated writing a custom class that extends Money in order to add this functionality in a manner that was integrated into an overall money solution, but the maintainers chose to define the Money class as FINAL.

Here's my solution in case it's helpful to you or you wish to expand upon it.

```
// Obtain amount as string from existing Money object
$str = $input->getAmount();

// If not zero...
if ($str !== '0') {

	// Obtain whole units of currency
	$whole = substr($str, 0, strlen($str)-2).'00';

	// Obtain fractional units of currency
	$factional = (int) substr($str, -2);

	// If there are no whole units of currency...
	if ($whole === '00') {

		// Force to single zero
		$whole = '0';
	}

	// Create money object from whole units of currency
	$result = Money::USD($whole);

	// If factional units of currency should round to the
	// nearest whole unit of currency...
	if (abs($factional) >= 50) {

		// If whole units of currency are positive...
		if ($result->isPositive() === true) {

			// Addend should be positive
			$addend = Money::USD(100);

		// Otherwise, if whole units of currency are negative...
		} else if (result->isNegative() === true) {

			// Addend should be negative
			$addend = Money::USD(-100);

		// Otherwise...
		} else {

			// If fractional units of currency are positive...
			if ($factional >= 0) {

				// Addend should be positive
				$addend = Money::USD(100);

			// Otherwise...
			} else {

				// Addend should be negative
				$addend = Money::USD(-100);
			}
		}

		// Add appropriate unit of currency corresponding to
		// fractional units of currency to facilitate the
		// rounding operation
		$result = $result->add($addend);
	}

// Otherwise...
} else {

	// Convert value to money object
	$result = Money::USD(0);
}
```

**Comment by sagikazarmark** [comment]
@broberts-mrmc @oligus This sounds like a great addition to this library. I will try to find some time to work on it.

**Comment by frederikbosch** [comment]
I think it is pretty easy to come up with a solution. The only question is where to add the method. Rounding to nearest whole unit requires to know the number of subunits. So if we add the method [`rounded`](https://www.google.com/search?sq=rounded+price) to `Money` than it might look like this.

```php
function rounded(int $subunits) {
  return new Money(Number::roundMoneyValue($this->amount, 0, $subunits));
}
```

This is not tested yet, but I guess it should work.

**Comment by frederikbosch** [comment]
I agree, my proposed name is not ideal. `roundToSubunits` sounds good. We do not have any aliases, and my suggestion would be to not ever have them. Just pick a name that suits you best, and we will discuss it when the PR is there.

**Comment by rtheunissen** [comment]
Isn't this just half away from zero?

https://3v4l.org/AAlXq

**Comment by mewejo** [comment]
Was any progress ever made on this? It'd be really cool to have this built into the library

**Comment by mewejo** [comment]
I just had a quick go and this should work, with all currencies?

```php
use Illuminate\Support\Str;
use Money\Money;

$price = Money::GBP(1337);

// Round up the nearest whole unit, which will end with '00'
while(!Str::endsWith($price->getAmount(), '00'))
{
    // Add one unit (pence) on each iteration
    $price = $price->add(new Money(1, $price->getCurrency()));
}

// $price is now equal to 1400
```
