### ISSUE TITLE
Creating Money Object Errors on large number

### ISSUE THREAD

**Issue by Yamakasi** [moneyphp/money#481]
It seems that the object for MoneyPHP is crashing on large amounts, is this known ?

I cannot find out yet on which number it fails but I started to see it on this amount:

`$money = new Money('16333.17', new Currency('EUR'));`

I hope this is not a bug because when I change 16333.17 to 100 it works again.

**Comment by bmeynell** [comment]
@Yamakasi - `16333.17` is not a large amount -- in the grand scheme of things.

What version are you using? In my composer version (`^3.0`) your example with throw an `InvalidArgumentException('Amount must be an integer(ish) value')`.

**Quick Test 1:**
```php
$amount = '16333.17';
var_dump(filter_var($amount, FILTER_VALIDATE_INT)); // bool(false)
$number = Number::fromString($amount);
var_dump($number->isInteger()); // bool(false)
```

Try this instead (note, no decimal):

```php
$money = new Money('1633317', new Currency('EUR'));
```

**Quick Test 2:**
```php
$amount = '1633317';
var_dump(filter_var($amount, FILTER_VALIDATE_INT)); // int(1633317)
$number = Money\Number::fromString($amount);
var_dump($number->isInteger()); // bool(true)
```

... If you still have issues after attempting what's above then please reply with as much information and surrounding context as possible. For example, saying _"it fails"_ is useless for people who want to help, but an actual exception, fatal error, stacktrace, etc., etc., goes a long way to getting an answer and solution expediently.

**Comment by bmeynell** [comment]
@Yamakasi - There's also very good documentation at http://moneyphp.org/en/latest/ if you haven't come across it. Below is a small screenshot from http://moneyphp.org/en/latest/getting-started.html which looks related to what you're attempting to do.

<img width="738" alt="screen shot 2018-04-19 at 10 29 43 am" src="https://user-images.githubusercontent.com/1051554/38998073-cbdb5348-43bc-11e8-9f3d-8b8afa76cd09.png">

**Comment by Yamakasi** [comment]
@bmeynell:

Thanks, this is indeed wrong at my side but it's strange it works good with a value of 100000.00

I don't see the exception, could be codewise here, I need to check, but the above working example is strange isn't it ? It does seem to crash from some higher number.

**Comment by bmeynell** [comment]
@Yamakasi - The documentation (and screenshot above) states that trailing `.00` will resolve as valid, but nothing else will. It does seem odd, but I'm sure there's reason and discussion behind that behavior, I simply don't know what it is. Glad your code is working better now!

**Comment by Yamakasi** [comment]
@bmeynell thanks, I'm always curious about such behaviour. What is best to store the money in a Database: as Decimal and create an Integer out of it for this library or an Integer is best ?

**Comment by bmeynell** [comment]
> What is best to store the money in a Database

There is much active discussion about this here (search the repo) and overall -- as well as how to integrate with an ORM. Personally, I lean toward storing the smallest possible denomination (e.g., "cents") in one column and the ISO currency code in a tandem column.

**Comment by Yamakasi** [comment]
Yes I have exactly the same way. Thanks for the confirmation!

**Comment by bmeynell** [comment]
@Yamakasi - Please close this issue if you're satisfied it's been resolved. TY!
