### ISSUE TITLE
Money Object to INT/Cents

### ISSUE THREAD

**Issue by Yamakasi** [moneyphp/money#483]
When I have created and calculated a money object what should I do with it to the INT format I need to have for my Database Insert ?

My moneyObject (simple uncalculated one):

`$amount = new Money('100', new Currency('EUR'));`

But this is the way to Parse normally 100 euro to 10000:
```
$currencies = new ISOCurrencies();
$moneyParser = new DecimalMoneyParser($currencies);
$money = $moneyParser->parse('10000', 'EUR');
```

How to combine these two in a decent manner ?

**Comment by Yamakasi** [comment]
It seems you need to parse a DecimalMoneyParser and calculate with that, if I'm right.

**Comment by frederikbosch** [comment]
See the docs.
