### ISSUE TITLE
Add support for currencies which use symbols different to their alphabetic Code

### ISSUE THREAD

**Issue by gkarugi** [moneyphp/money#484]
An example of which is: 

Kenyan shilling ( Alphabetic code : KES, symbol used is Ksh ),
or Tanzanian shilling( Alphabetic code : TZS, symbol used is Tsh)

I think there are many more like these.

**Comment by frederikbosch** [comment]
We are not supporting symbols inside `Currencies` at all. Only formatting. If you want to use symbols, you can use the `IntlFormatter`, which in turn uses the intl extension.
