### ISSUE TITLE
Extending ISOCurrencies

### ISSUE THREAD

**Issue by simPod** [moneyphp/money#488]
Hello,

what is the recommended approach to extending ISOCurrencies? I need to overrride minorUnit for 2 currencies from the ISO list. The class is final and therefore not extensible.

Thanks

**Comment by sagikazarmark** [comment]
I recommend creating a wrapper around the ISOCurrencies class, implementing the Currencies interface. That way you can override the minorUnit for the currencies you need to.

**Comment by frederikbosch** [comment]
Correct, look at how to decorate classes, or implement the `Currencies` interface yourself.
