### ISSUE TITLE
Summing together different currencies

### ISSUE THREAD

**Issue by judgej** [moneyphp/money#489]
Yes, I want to sum the totals of multiple currencies. Actually, I don't, by the ISO20022 PAIN.001 file format does!

The ISO20022 pain.001 file contain a `CtrlSum` field in the header that sums up all amounts that the batch file contains, and that can be a mix of any currencies. They are to be summed as major units, with the decimals handled appropriately.

In effect, this is like a currency-less Money amount, with a fluid decimals amount rather than a currency. Adding $1.23 to €2.00 should give an amount of ¤3.23 (no currency, but decimals of 2). Adding on BHD 1.009 should result in ¤3.239, which now has decimals of 3. 

Does this library have a solution that would solve this? Or is this totally out of scope of what this library is trying to achieve?

**Comment by sagikazarmark** [comment]
@judgej not only this library has no solution, everywhere two money objects interact the currency must be the same. 😄 

Jokes aside: It seems to me that this is a quite specific use case and we are trying to keep the library as minimal as possible. That being said, I'm not against collecting knowledge for specific use cases somewhere in the MoneyPHP ecosystem.

If you come up with a decent solution, I'm more than happy to provide some space to host it:

- documentation page
- separate repo as an example (I guess writing code for the above problem wouldn't count as a whole package, would it?)
- this issue
- etc

As for the solution: I guess you would have to use one of the Calculators (or convert to int) and manually add the values together. You can use the Currency to determine the subunit for each of them.

**Comment by judgej** [comment]
Yes, it is a bit of a unique case. What I have is the guts of the `Money` class copied and pasted into a custom class to do the calculations. Because `Money` is marked as `final`, it puts a walled garden around what it contains, so nothing inside it can be put to use for other purposes. Also because `Money` does not have an interface, I'm resorting to duck-typing when summing a `Money` object with a `MixedMoney` object, which does not feel ideal.

I'll see what I can do to tidy up and maybe simplify what I have and link/post it here to see if it will be of any use to others.
