### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by mathiasverraes** [moneyphp/money#49]

**Comment by sagikazarmark** [comment]
For now, I am willing to maintain the sphinx version

**Comment by frederikbosch** [comment]
@sagikazarmark Shall I fill the documentation gaps (exchange, swap) and remarks? Then release RC1?

**Comment by frederikbosch** [comment]
I think documentation is acceptable at this stage.

**Comment by frederikbosch** [comment]
Just committed documentation for currencies. I am going to close this one too.
