### ISSUE TITLE
Allow Converter to accept a CurrencyPair

### ISSUE THREAD

**Issue by jaikdean** [moneyphp/money#498]
As per the current documentation, you can get a conversion rate and convert a `Money` object to another currency as follows:

```php
$exchangeRate = $exchange->quote(new Currency('GBP'), new Currency('USD'));
$tenPoundsInDollars = $converter->convert(Money::GBP(1000), new Currency('USD'));
```

We need to log the exchange rate that was used for a conversion alongside the converted value. We can do the above, but that relies on `$exchange->quote()` returning the same value when called by `Converter::convert()`, which in some cases may not be true.

I suggest we add a method to `Converter` to allow a value and a `CurrencyPair` to be passed in, rather than having `Converter` always call `Exchange::quote()`:

```php
$exchangeRate = $exchange->quote(new Currency('GBP'), new Currency('USD'));
$tenPoundsInDollars = $converter->convertFromCurrencyPair(Money::GBP(1000), $exchangeRate);
```

**Comment by Padam87** [comment]
+1 Same here.

Our system is HUF based, but we allow customers to use other currencies for payment.

We store the exchange rate at the time of purchase.

We also log expenses for every order, and store the ratio at the time of logging those expenses.

1 to 4 currencies are usually involved for every order.

For our profit stats, we convert everything to HUF, using the stored ratios. This feature would make it a lot easier.

**Comment by sagikazarmark** [comment]
This sounds like a nice addition to the library.

For now you can create a custom exchanger with fixed rates to ensure you always get the same result.

Where this method should go: I will have to think about it. It would be nice to keep it separated from the exchange stuff, so a separate class would probably be a better fit, but we will see.

In the meantime, feel free to submit a PR to see how it would work.

**Comment by judgej** [comment]
So I understand, is it necessary to create a dummy `Exchange`, in order to create a converter, if you are only going to convert using `convertAgainstCurrencyPair()`? Does that method use the exchange? It doesn't look like it does. Creating a class that is necessary as a depenency, but is then not used, feels wrong. Should the exchange be an optional argument, or should `convertAgainstCurrencyPair()` be in a class of its own?
