### ISSUE TITLE
Create new tag

### ISSUE THREAD

**Issue by shirshir** [moneyphp/money#499]
There are a [couple of commits](https://github.com/moneyphp/money/compare/v3.1.3...master) in master that are not released/tagged yet. Could you create a new tag?

**Comment by frederikbosch** [comment]
How about a new tag @sagikazarmark? Why shouldn't we just release it?

**Comment by sagikazarmark** [comment]
Yeah, good idea. I'm going to release 3.2 and postpone the rest of the things in the tube.

**Comment by UlrichEckhardt** [comment]
I'd also love to have a 3.1.4 or 3.2.0, can I help somehow?

**Comment by sagikazarmark** [comment]
Done in: https://github.com/moneyphp/money/releases/tag/v3.2.0
