### ISSUE TITLE
Add historic currencies to Money\Currencies\ISOCurrencies

### ISSUE THREAD

**Issue by anton-siardziuk** [moneyphp/money#500]
Hello there!

This is a next step of this feature and pr: https://github.com/moneyphp/iso-currencies/issues/8

My idea is to implement it in Money would be this: lets create static constructors `ISOCurrencies::current()`, `ISOCurrencies::historic()` and `ISOCurrencies::all()`. Also I would change default behaviour of `ISOCurrencies::__construct()` to use `all()` instead of `current()`, maybe we can do this in new major version as strictly speaking this would be a (however very light) BC break. Another idea would be to deprecate `ISOCurrencies::__construct()` and make it private in some future major version, so you are forced to use new static constructor everywhere and it is explicit what list you are using here.

What do you think about it? I will gladly provide PR for this, I just wanted to discuss it before with you.

**Comment by marcosdsanchez** [comment]
After https://github.com/moneyphp/iso-currencies/pull/9#discussion_r237204506 is fixed, instead of static constructors which break BC, I'd prefer to have different classes depending on what's the set about. We can also create a new class which is an aggregate of historical + isoCurrencies.

Something like this:

```php
final class AllISOCurrencies implements Currencies
{
    private $aggregate;

    public function __construct()
    {
        $this->aggregate = new Currencies\AggregateCurrencies([
           new Currencies\ISOCurrencies(),
           new HistoricalCurrencies(),
        ]);
    }
    ....
```

**Comment by m00t** [comment]
@marcosdsanchez makes sense. Thanks for noticing the minor units issue!

**Comment by frederikbosch** [comment]
I will postpone fixing this is issue until a solution is found for [moneyphp/iso-currencies#9 (comment)](https://github.com/moneyphp/iso-currencies/pull/9#discussion_r237204506).

**Comment by frederikbosch** [comment]
This will not be implemented. People can add their own `Currencies` implementation, using the array of historic currencies provided by [moneyphp/iso-currencies](https://github.com/moneyphp/iso-currencies/). We do not want to maintain history!
