### ISSUE TITLE
allocate returns wrong rounded result 

### ISSUE THREAD

**Issue by Artem-Schander** [moneyphp/money#506]
Hi everyone, firstly many thanks for the lib. It does an awesome job.  
But either i understood something wrong or the `allocate` method returns wrong results.  
Here is an example:
```php
$grossValue = 977.59;
$taxRate = 15.966386554622;

$money = new Money($grossValue * 100, new Currency('EUR'));
list($netValue, $taxValue) = $money->allocate([100 - $taxRate, $taxRate]);
```

Expected result is:
```php
$netValue === 821.50; // not rounded value is 821.50420168067
$taxValue === 156.09; // not rounded value is 156.08579831933
```

But instead I got these values:
```php
$netValue === 821.51;
$taxValue === 156.08;
```

I think i've missed something.

**Comment by mishavantol** [comment]
I'm able to reproduce this behaviour, will update the it_allocates_amount test and look into it.
