### ISSUE TITLE
Subtract and add not using scale

### ISSUE THREAD

**Issue by dzona** [moneyphp/money#507]
``BcMathCalculator`` add and subtract methods ignore scale set up for calculator, thus giving wrong results.

````
$total = '0.00125148';
$fee = '0.00005006';
$calc = new BcMathCalculator($bitCoinScale = 8);
$amount = $calc->subtract($total, $fee);
var_dump($amount); // string(1) "0"
````

**Comment by bmeynell** [comment]
@dzona - I'm curious about this too - did you come to any conclusions? `0` is clearly hard-coded for `add()` and `subtract()` in lieu of `$this->scale`:

**Add:**
https://github.com/moneyphp/money/blob/8655b0f62763acb893bad53be35323af25ad557c/src/Calculator/BcMathCalculator.php#L46-L49

**Subtract:**
https://github.com/moneyphp/money/blob/8655b0f62763acb893bad53be35323af25ad557c/src/Calculator/BcMathCalculator.php#L59-L62

🤔

**Comment by tonydspaniard** [comment]
scale is a must for any operation to provide proper results.
