### ISSUE TITLE
[Question] Best way to create a custom currency

### ISSUE THREAD

**Issue by rogervila** [moneyphp/money#518]
Hello,

I'm working on a ecommerce that converts 'fidelity points' to money, and I think that the best approach is to create a 'fidelity' currency that can be c[onverted through the custom fixed exchange ](http://moneyphp.org/en/stable/features/currency-conversion.html#fixed-exchange)

I have checked https://github.com/moneyphp/money/issues/29 and https://github.com/moneyphp/money/pull/58, but I would like to ask what is the best way to create a custom currency.

Thank you.

**Comment by sagikazarmark** [comment]
It depends on what you want to do with your currency. Creating the currency itself is easy: just give it a currency code and use it.

If you want currency conversion, then you can either implement your own Exchange class (which eg. contacts a separate service asking for conversion rate) or just use the FixedExchange with hardcoded values.

For formatting you will need to implement a MoneyFormatter. If you use other currencies as well, you can channel it into an AggregatedMoneyFormatter.

Likewise, you can do the same for parsing a string representation of your currency.

Last, but not least, you might want to implement your own Currencies, which is a collection of currencies. As with the exchange, you can also use an existing implementation, like CurrencyList.

I suggest you checking out the Bitcoin implementations.

(Note to self: we might have to write some documentation about this topic)

**Comment by sagikazarmark** [comment]
You can easily use multiple currency source with the `AggregatedCurrencies` class. Other than that: yeah, this could work.

**Comment by frederikbosch** [comment]
As @sagikazarmark has stated, your best option is to use [`AggregateCurrencies`](http://moneyphp.org/en/stable/features/currencies.html#aggregate-currencies) together with [`CurrencyList`](http://moneyphp.org/en/stable/features/currencies.html#currencylist).

```php
$currencies = new AggregateCurrencies([
    new BitcoinCurrencies(),
    new ISOCurrencies(),
    new CurrencyList([
         'CUSTOM_CURRENCY_CODE' => 2,
    ])
]);
```

Inject that into other classes that require `Currencies` interface in the constructor.
