### ISSUE TITLE
Remove Currencies from constructor BitcoinMoneyFormatter

### ISSUE THREAD

**Issue by frederikbosch** [moneyphp/money#524]
It does not make sense to inject `Currencies` into since it is used for only 1 currency and all unknown factors are static.

**Comment by frederikbosch** [comment]
I decided to drop this issue. If someone creates an own implementation of `Currencies` for Bitcoin, with a different subunit, then it can still use the formatter. Therefore I think it is fine to leave it as is.

**Comment by gmponos** [comment]
At least add a docblock about it in order not to be spawned again?
