### ISSUE TITLE
$forceCurrency is ignored in BitcoinMoneyParser

### ISSUE THREAD

**Issue by cebe** [moneyphp/money#539]
https://github.com/moneyphp/money/blob/70b0c99beed1dc76dc2d6c7210df9e4f64db9159/src/Parser/BitcoinMoneyParser.php#L34

`$forceCurrency` has no effect because bitcoin currency is hardcoded in 

https://github.com/moneyphp/money/blob/70b0c99beed1dc76dc2d6c7210df9e4f64db9159/src/Parser/BitcoinMoneyParser.php#L65

**Comment by gmponos** [comment]
dup of https://github.com/moneyphp/money/pull/527

**Comment by cebe** [comment]
How is this a duplicate? This issue is about the parser, the PR is about the formatter.

**Comment by gmponos** [comment]
My bad... 👍  misread..
