### ISSUE TITLE
ReversedCurrenciesExchange float problem

### ISSUE THREAD

**Issue by rntorm** [moneyphp/money#549]
I understand that in below case the conversion from on currency to other and back is not the same because of the rounding after conversion is done. I couldn't think of a way to avoid this problem. Has anyone any suggestions how to get this kind of use-case to work with current library? 

```
public function testShowFloatProblem()
{
        $generator = Factory::create();
        $priceInPounds = $generator->randomFloat(2, 0.01, 1000);
        $currencies = new ISOCurrencies();
        $moneyParser = new DecimalMoneyParser($currencies);
        $gbp = $moneyParser->parse((string)$priceInPounds, 'GBP');

        $exchangeRate = $generator->randomFloat(5, 0, 1);
        $exchange = new FixedExchange([
            'GBP' => [
                'EUR' => $exchangeRate
            ]
        ]);

        $converter = new Converter($currencies, $exchange);
        $eur = $converter->convert($gbp, new Currency('EUR'));

        $reverseExchange = new ReversedCurrenciesExchange($exchange);
        $converter = new Converter(new ISOCurrencies(), $reverseExchange);
        $newGbp = $converter->convert($eur, new Currency('GBP'));

        $moneyFormatter = new DecimalMoneyFormatter($currencies);

        $this->assertEquals($moneyFormatter->format($gbp), $moneyFormatter->format($newGbp));
}

**Comment by bmeynell** [comment]
What is the failure message in your test case?

> Has anyone any suggestions how to get this kind of use-case to work with current library?

My guess: It's just math and nothing to do with this library. Once you round, the value you have is completely _new_ -- even for the same currency. If you need inverse function then your best bet is likely to store both the integer and fractional part that make up the decimal as a ratio and use that ratio to support the inverse function. See https://ren.zone/articles/safe-money for storing as a rational number.
