### ISSUE TITLE
Extended CryptoCurrencies Support

### ISSUE THREAD

**Issue by zek** [moneyphp/money#552]
I know we can use BitcoinCurrencies and BitcoinMoneyFormatter for XBT (Bitcoin)

Is it possible to make a bit general class for Ethereum, Ripple etc.

Do you suggest anything?

**Comment by frederikbosch** [comment]
I created these classes, but I am not using them. It was frequently requested. I think our previous decision was to avoid to become a currency repository. @sagikazarmark What do you think?

**Comment by zek** [comment]
BTC might be almost same thing but actually BTC !== XBT (at least in my situation)

https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=XBT

As you see the rate is not 1. Some markets work as XBT some others work as BTC. 

So the Currency Conversion also fails in this situation. Cuz your class uses XBT but cryptonator.com uses BTC. I had to manually change currency field before converting to USD or EUR.

So  I created my own basic class and I use BTC instead of XBT. 

I know supporting cryptocurrencies is not liability of this library but cryptocurrencies is the future and you may think supporting it better.

**Comment by frederikbosch** [comment]
I am ok with merging a `CryptoCurrencies` class (implementing `Currencies`) PR. This could look similar as the `ISOCurrencies` class. See also [our iso currencies repo](https://github.com/moneyphp/iso-currencies). Are you aware of any (pseudo)official source for all crypto currencies? In the iso currencies repo we are using the ISO 4217 Maintenance Agency. If we go for this I would prefer similar methodology: automatic update based on a third party. I don't like the idea that this library also becomes maintenance agency.

**Comment by zek** [comment]
> Are you aware of any (pseudo)official source for all crypto currencies?
I use cryptocompare and coinmarketcap but coinmarketcap is paid now. As I know the best option is 
https://www.cryptocompare.com/api/data/coinlist/

> I don't like the idea that this library also becomes maintenance agency.
Definitely. There are thousands of crypto currencies we can't support all of them cuz ever day a new one pops.

**Comment by ivaaaan** [comment]
Any updates about this task? At least we can add support of the most popular cryptocurrencies. What do you think about this? If we agreed on such a list, I would try to implement this.

**Comment by frederikbosch** [comment]
I am not a fan personally. This feature will lead to a significant increase in the support we have to give to this library. The dynamics of crypto currencies is huge. I am not willing to maintain that. I can see the value in it for sure. My suggestion would be that someone creates a separate package for this. 

@sagikazarmark Do you have an opinion in this matter?

**Comment by ivaaaan** [comment]
Quickly created for my own purposes: https://github.com/ivaaaan/cryptocurrencies-money

**Comment by tmlee** [comment]
Hey guys, have you given the CoinGecko API a try? It is free and publicly available without keys at https://www.coingecko.com/api

We cover over 4000 cryptocurrencies from over 300 exchanges. And got plenty of endpoints for you to play with.

Happy to answer any questions! Cheers!

**Comment by ivaaaan** [comment]
@tmlee there's no subunits info in this API. What value should we use by default? 10^-8?

**Comment by tmlee** [comment]
@ivaaaan all price amount is displayed as follows 
1 USD as $1.00
1 BTC as 1.0 BTC
0.001 ETH as 0.001 ETH

I supposed if 10^8 is your subunit, yes 10^-8 is the way to normalize it

**Comment by zek** [comment]
I guess ethereum is 10^9

So it may change
6 Mar 2019 Çar, saat 09:46 tarihinde TM Lee <notifications@github.com> şunu
yazdı:

**Comment by frederikbosch** [comment]
Hi guys, as I really think that this discussion/issue belongs in its own library, I am going to close this issue. This library is not a currency repository, but focuses on the logic side of money related calculations.

Once there is a library that organizes everything around bitcoin, we are more than happy to include a link to that library on our readme/frontpage.

**Comment by slunak** [comment]
Hi everyone and @frederikbosch 

Are you still willing to accept a PR with `CryptoCurrencies` class implementing `Currencies`?

I have created a library similar to iso-currencies, please have a look here https://github.com/slunak/cryptocurrencies-money-php

The source for cryptocurrencies is Binance crypto exchange. More sources can be added, the library supports it.

What is the best way to integrate the library into money-php do you think?

**Comment by frederikbosch** [comment]
Hi @slunak, it looks like you took [moneyphp/iso-currencies](https://github.com/moneyphp/iso-currencies) as base for your own package. Are you OK with moving your code into the `moneyphp` organization? I am willing to create a `moneyphp/crypto-currencies` and add you as a maintainer there. Afterwards we can add a `CryptoCurrencies` here, similar to the `ISOCurrencies`.

**Comment by slunak** [comment]
Indeed, @frederikbosch, I used `ISO-currencies` library as a base, with some minor tweaks. Absolutely OK to move the code under `moneyphp`.

**Comment by frederikbosch** [comment]
Great, created the repo and send you an invitation as maintainer of the repo.

**Comment by frederikbosch** [comment]
Perfect, looking forward!
