### ISSUE TITLE
ext-decimal calculator

### ISSUE THREAD

**Issue by bendavies** [moneyphp/money#554]
Hey there,

Wondering if there is any appetite or objections for implementing a calculator using http://php-decimal.io/ ?

Cheers!

**Comment by Padam87** [comment]
One (or perhaps the only) major flaw of this library is that it mixes decimal issues with money issues, so integrating this library would be most welcome.

Money = Decimal + Currency

**Comment by sagikazarmark** [comment]
#516 has been submitted, but it probably needs some polishing.

**Comment by frederikbosch** [comment]
This can be published in a separate library.
