### ISSUE TITLE
Trim trailing zeros

### ISSUE THREAD

**Issue by grzegorztomasiak** [moneyphp/money#556]
Is it possible to trim trailing zeros, so $1.00 becomes $1 and $1.23 stays $1.23?

**Comment by frederikbosch** [comment]
Yes, see http://moneyphp.org/en/stable/features/formatting.html#intl-money-formatter and https://www.php.net/manual/en/numberformatter.setattribute.php

See NumberFormatter::FRACTION_DIGITS.
