### ISSUE TITLE
Remove bcmath dependency

### ISSUE THREAD

**Issue by terrafrost** [moneyphp/money#558]
See https://github.com/phpseclib/bcmath_compat .

It basically turns phpseclib's BigInteger class into a BigDecimal class.

**Comment by frederikbosch** [comment]
It’s only require-dev. Right? Nice project btw.

**Comment by terrafrost** [comment]
> It’s only require-dev. Right?

Yah - good point.

I went ahead and created a PR: #559 

> Nice project btw.

Thanks!!
