### ISSUE TITLE
DecimalMoneyParser strange rounding 

### ISSUE THREAD

**Issue by golubkovden** [moneyphp/money#561]
I think it's bug with rounding value with DecimalMoneyParser. 

```php
$parser = new \Money\Parser\DecimalMoneyParser(
    new \Money\Currencies\ISOCurrencies()
);

$currency = new \Money\Currency('USD');

$parser
    ->parse('10.125', $currency)
    ->getAmount();
// output: 1013

$parser
    ->parse('10.1245', $currency)
    ->getAmount();
// output: 1012
```

**Comment by UlrichEckhardt** [comment]
There is no bug, as far as I can tell: Everything below X.5 is rounded down to X. X.45 is /not/ first rounded to X.5 and then to X+1.

BTW: If you report a bug where something doesn't behave as expected, it is very useful to actually state what you expected in a way that is observable. The interpretation "strange rounding" is not really helpful.

**Comment by golubkovden** [comment]
@UlrichEckhardt yeah, i understand your point. But it'll be better if `DecimalMoneyParser` will either round numbers completely or not and throw some exception about wrong number length.

**Comment by UlrichEckhardt** [comment]
Hold on: Before we engage in any discussion about correct or incorrect behaviour, please answer the following two questions:

1. What happend actually?
2. What did you expect to happen instead?

**Comment by frederikbosch** [comment]
Exactly, unclear description of the problem. I am closing it.
