### ISSUE TITLE
Allow DecimalMoneyFormatter to set decimal character

### ISSUE THREAD

**Issue by NoxxieNl** [moneyphp/money#565]
Hiya,

Maybe a Idea to allow the `DecimalMoneyFormatter` class to allow the definition of a decimal character rather then hardcoded `.` (dot). 

Could not find any issue's regarding it :-).

Would be happy to send a PR for this.

**Comment by frederikbosch** [comment]
Basically what you are asking for is a localized decimal money formatter. You can use the IntlMoneyFormatter for this. See http://moneyphp.org/en/stable/features/formatting.html#intl-money-formatter.

**Comment by NoxxieNl** [comment]
And what if the user does not have access to the `intl` component because of shared hosting or what so ever, would come in handy that the user still can select a different formatting option on the `DecimalMoneyFormatter`

**Comment by frederikbosch** [comment]
@NoxxieNl You are free to create an implementation of `MoneyFormatter` yourself. It is an interface, which you implement in your own namespace. Just copy the decimal formatter to your own namespace, adjust it to your needs and use it.

This library does not have to have every possible feature. Through interfaces we are offering people to communicate with Money instances. Just implement your own feature to one of the interfaces. Feel free to create a PR for them, but we might decide not to merge them. Every line of code needs maintenance, maintenance needs time and time is limited.
