### ISSUE TITLE
Can you make Currency class not final? (for DB persist)

### ISSUE THREAD

**Issue by legalcash** [moneyphp/money#567]
i want to make it persisted with some additional fields

**Comment by sagikazarmark** [comment]
Sorry, no we can't. If you need to add behavior to Money, wrap it in a custom class.

**Comment by shadoWalker89** [comment]
6 years later, i found this issue.

I find it hard to understand why an open source package intended for being used by other people makes it hard to extend it's functionality.
The way i see it, if someone extends a class and then mess things up that is his responsibility, he should not mess with things that he does not understand.
Baby sitting developers is not a good thing.
I know my message will not change your opinion and i don't intend to do so but i just wanted to say that out loud.
