### ISSUE TITLE
Dealing with taxes

### ISSUE THREAD

**Issue by margaritacoco** [moneyphp/money#569]
Hello everybody, currently running the latest version of MoneyPHP.

I am trying to work with taxes, the most complex form of tax value that is in my project is: "9.975%". MoneyPHP can't handle it in cents. Which means, 9975 returns 99.75$. 

Considering this, I cannot do "product_price * (tax_amount / 100)" to get the amount. Since the tax_amount will be 99.75$, not 9.975$.

On top of this, MoneyPHP doesn't consider the decimals to round numbers. Which means, no matter the product price, the initial numbers are the result and the decimals do not matter.

How am I suppose to calculate taxes, with decimals amounts(as tax amounts) and then return a proper amount?

Example(Actual, real non-functional one):
Product Price:30.73$(3073)
Tax: 9.975%(0.09975$)

Test(01)
30.73 * 0.09975 = 3,0653175
Considering MoneyPHP only accepts INT, once converted to an int the answer is: 306(3.06$)
_Which is logical, with decimals it would be a float._

Test(02)
3073(Value in Database) * 0.09975 = 306,53175
Still returns 3.06$(306) because it doesn't take decimals into consideration. Since an INT is required. 

_**Even if I change my price to 3073,3074,3075, which returns a result of 3.066 and more, the answer REMAINS 306 no matter what the decimals ARE.**_
Once formatted by MoneyPHP, returns 

So how am I suppose to accomplish this sort of calculations?
*I have looked every issue on here regarding taxes, decimals and percentage
**I have looked at Laracasts, CodeCourse and Google
***The only thing left, is changing package(the only thing that was suggested)

**Comment by UlrichEckhardt** [comment]
Taxes or more generally percentages are unitless. Trying to represent them as `Money` instances is simply wrong. For illustration, consider 50$ times 9.75%$: What is the unit of the result? Dollar squared? No, the factor is 9.75%, which is simply a different way of spelling 9.75/100. A percentage doesn't have a unit, % is not a unit.

Concerning the rounding and precision, it would help if you provided actual code that doesn't behave as expected. Also, keep in mind that for e.g. US Dollars, the unit of that currency is cent, which is also what this is rounded to.

**Comment by margaritacoco** [comment]
@UlrichEckhardt I may have overthought this whole situation.

*I am open to suggestions, totally.

Are you suggesting for the taxes that I type them as strings, and never use them as Money instances. My goal is more to render the output of the "tax * product" to a money instance.

I didn't supply code, but the result of the multiplications which are literally what the code is. The results from Test 01 is with raw data(a simply multiplication) and the Test 02 is made with the AMOUNT of the Money instance.

No other code affects those tests. I haven't tried to round it or whatever.

A "solution", I have found is:

`        $awkardformat = ($this->moneyFormatter->format(new MoneyPHP(3073, new Currency('CAD'))) * (0.0975 / 100)) * 1;
        $intRounded = round($awkardformat, 2);
        $strFormat = strval("$" . $intRounded);

        dd($moneyParser->parse($strFormat));`

This code, returns `3.07` which represents the rounded result, and also formatted as a Money Instance.

The code is a test, not made to be beautiful or anything.

**Comment by prae-torian** [comment]
Hey @margaritacoco 
I think you're mixing "tax rate" (9.975%) with "tax amount" (e.g. $3.07). Like stated above the tax rate is unitless and can't be represented as `Money` object, but the tax amount can.

You can achieve your desired result with this example:
```php
$productPrice = new Money(3073, new Currency('CAD'));

$taxRate   = 9.975 / 100; // 9.975%
$taxAmount = $productPrice->multiply($taxRate);

var_dump($taxAmount);

// object(Money\Money)#14 (2) {
//   ["amount":"Money\Money":private]=>
//   string(3) "307"
//   ["currency":"Money\Money":private]=>
//   object(Money\Currency)#8 (1) {
//     ["code":"Money\Currency":private]=>
//     string(3) "CAD"
//   }
// }
```

If you need different rounding rules, the `multiply` method accepts as second parameter the following constants.
```php
// Money::ROUND_HALF_UP (default)
// Money::ROUND_HALF_DOWN
// Money::ROUND_HALF_EVEN
// Money::ROUND_HALF_ODD
// Money::ROUND_UP
// Money::ROUND_DOWN
// Money::ROUND_HALF_POSITIVE_INFINITY
// Money::ROUND_HALF_NEGATIVE_INFINITY
```

**Comment by frederikbosch** [comment]
I think this can be closed.
