### ISSUE TITLE
Allocation docs are outdated

### ISSUE THREAD

**Issue by lode** [moneyphp/money#574]
The allocation docs at http://moneyphp.org/en/stable/features/allocation.html still mention the idea of adding the remained to the first value passed. Since https://github.com/moneyphp/money/pull/526 that is not true anymore.

**Comment by sagikazarmark** [comment]
@lode thanks for reporting this issue! Would you mind sending a PR to fix it?

**Comment by lode** [comment]
I tried and failed. I might try again sometime but I notice I don't understand the mechanics to make it good enough.
