### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by benr77** [moneyphp/money#589]
It seems there's not yet any support for PHP 7.4? I'm getting errors such as

`Trying to access array offset on value of type int`

e.g. This is related to src/Formatter/IntlMoneyFormatter.php (line 44) 

`if ($valueBase[0] === '-') {`

PHP 7.4 does not permit accessing integer values with array access any more.

I've tried replacing the above with 

`if (substr($valueBase, 0, 1) === '-') {`

This works, but it feels wrong using a string function on an integer value.

Any thoughts? I'm happy to submit a pull request.

**Comment by UlrichEckhardt** [comment]
I searched https://www.php.net/ChangeLog-7.php#7.4.0 and only came up with 
https://wiki.php.net/rfc/deprecate_curly_braces_array_access, but that doesn't explain what you're seeing...

**Comment by benr77** [comment]
I believe it's the first entry on this page https://www.php.net/manual/en/migration74.incompatible.php

**Comment by UlrichEckhardt** [comment]
Ah, so the problem is that `$valueBase` is of type `int`. Using `substr()` then implicitly causes a conversion to string, so this works again, but that's probably not a "proper" solution. I'd like to understand the context of this error a bit better though.

**Comment by benr77** [comment]
Yes, but it only does a type conversion in order to do the comparison to determine the sign of the number. `$valueBase` is still an integer after the substr statement.

However, inside the `if` statement there's already a `substr()` in operation, and the resulting value of $valueBase is converted to a string anyway, as it is the return value of `substr()` - meaning depending upon the initial sign of $valueBase, after the `ìf` statement it could be either a string or an integer.
```
if ('-' === $valueBase[0]) {
    $negative = true;
    $valueBase = substr($valueBase, 1);
}
```
Surely we can just replace this with integer only processing to the same effect:

```
if ($valueBase < 0) {
    $negative = true;
    $valueBase = $valueBase * -1;
}
```
Here, $valueBase will start and end up as an integer value.

**Comment by benr77** [comment]
Looking across the codebase, it seems all of the cases where some $var is accessed as an array, it is already a string, or is treated as a string immediately afterwards.

I can't see any good reason not to just switch to using `substr()` to determine the negativity in all these cases. 

Any thoughts?

**Comment by UlrichEckhardt** [comment]
Hmmm. I claim that none of us properly understand this behaviour yet. The point is, that `$valueBase = $money->getAmount();`. This method is documented (per docstring) to return a `string`. The only place the according `$amount` member is set (in the constructor) explicitly converts it to a `string`. So, I wonder how that code gets invoked in a way that the amount is an integer. That is what shouldn't have happened in the first place!

That said `$someString[0]` is not what causes the error, the change in 7.4 only concerns null, bool, int, float or resource values treated as arrays.

**Comment by benr77** [comment]
I now have some more information on the matter. Our applications use our own Symfony bundle to integrate Money/Money - https://github.com/headsnet/money-bundle

This bundle has declared the Doctrine `amount` column type to be `integer` which will allow summing of amount values with DB queries etc, as opposed to storing the amount as a string.

However, when hydrating a Money instance from the database, Doctrine does not use the object's constructor. Therefore it is able to create a Money object that contains the correct currency value as a Money\Currency object, but with the amount value as an integer - despite the amount being cast to a string in the constructor.

So this is how, in my case at least, the amount property is ending up as an integer and not a string.

I consider this a reasonable use case - would you agree? 

One solution is to change the Doctrine column definition to store the amount as a string, but this loses several advantages. 

Would you instead consider casting to a string in the `$money->getAmount()` method when returning the value? It should have zero effect on any other behaviour as in all current cases it would be a string anyway.

**Comment by UlrichEckhardt** [comment]
The constructor of a class is used to ensure "class invariants", which is an essential part of encapsulation. For `Money`, one such class invariant is that `$amount` is a string. If Doctrine circumvents the constructor and thus manages to break that class invariant, any other code that relies on these breaks as well. In other words, Doctrine's at fault. Heck, that would even fail if someone decided that `$sum` was shorter than `$amount` and renamed the private (!) member.

If you look at this from a different perspective, you will see another aspect of this: The reason why this library avoids using PHP's numeric types (float or int) for `$amount` is that it *needs* a decimal representation for proper computation and rounding. The numeric types either don't offer the required precision (`float`), range (`int`) or significant digits (both), which are effectively unlimited except by memory constraints with a decimal representation based on `string`.

Suggested fix: Change you DB column to string (varchar or text or somesuch) and see what Doctrine makes of it. Maybe the DB even has a "decimal" type with arbitrary precision that could be used. Also, adjusting the code to (de-)hydrate the object to use the constructor could be a promising approach.

In any case, it's somewhere between a bug and a serevely missing feature that Doctrine fills an `@var string` variable with a numeric type and doesn't even complain about it. Consider filing a bugreport for that, too!

**Comment by benr77** [comment]
Thanks for your reply. Doctrine's constructor-less construction of objects is one of its core features. If actions happen in the constructor, they are intended to be executed when the object is constructed as a new object. Doctrine is rebuilding an object from persistence that was actually created some time previously - so not using the constructor is important. 

The fault indeed lies with our bundle using an integer column type - as mentioned already this is to provide the ability to use DB queries to perform e.g. sum calculations directly on the amount column.

I think as you suggest, an easy solution would be to introduce a new custom Doctrine column type for amount (we already have this for Currency), and use it to convert the integer value in the database to a string value for Money/Money and vice versa. This would not require any changes in this package, which is of course Doctrine agnostic.

Anyway, thanks for the discussion and help - I've learned a few things looking in to this issue :)

**Comment by benr77** [comment]
For future Google searches, if you use a Doctrine "decimal" type and set the scale to "0", you effectively get an integer based numeric column type in the database, but Doctrine returns it as a PHP string, which solves this problem completely without anything more than a configuration change.

**Comment by sagikazarmark** [comment]
Sorry for joining the conversation late.

I believe Doctrine allows you to define metadata outside of the class (yaml and XML mappings). You could use those to define a string type.

Speaking of PHP 7.4: property types will probably solve this situation, but we are not there yet.
