### ISSUE TITLE
Cannot resolve currency pair

### ISSUE THREAD

**Issue by llKoull** [moneyphp/money#592]
Hi!

I've been using this awesome library for a while and today i saw that i was getting an error in a request for some users. I did some testing and i saw that the conversion from EUR to USD is failing.

<p>Type: Money\Exception\UnresolvableCurrencyPairException</p>
<p>Message: Cannot resolve a currency pair for currencies: EUR/USD</p>

How can i perform this exchange?

I'm just doing:

$eur = Money::EUR(var_int($price_in_eur));
$f_price = $converter->convert($eur, new Currency('USD'));

Thanks and best regards!

**Comment by kslimani** [comment]
This exception is throw by the exchanger instance provided to converter constructor.

You should verify if the service plugged behind the exchanger is still able to convert EUR to USD.

**Comment by llKoull** [comment]
Hi @kslimani !

Thanks for your response!

I'm using florianv/swap like in the example of the official documentation (http://moneyphp.org/en/stable/features/currency-conversion.html#third-party-integrations) and as you can see in the example, they are converting from € to $ and i was also doing the same without any problem since some days ago.

Best regards!

**Comment by kslimani** [comment]
@llKoull your issue seems to be more related to florianv/swap or florianv/exchanger than moneyphp.

Catching and dumping the exception stacktrace may give you some hints on why your request to the fixer api *may* be failing.

_(also ensure you have the latest florianv dependencies installed in your project, as sometimes echangers api changes etc...)_

**Comment by llKoull** [comment]
Hi @kslimani !

Thanks again for your answer, you were right, the problem wasn’t related with moneyphp. My customer reached the limit of requests to Flex. He should buy a bigger plan hehehe.

Best regards!
