### ISSUE TITLE
[Parser] Parse without rounding using IntlLocalizedDecimalParser

### ISSUE THREAD

**Issue by awebartisan** [moneyphp/money#601]
First of all, I am sorry I don't know where to ask this question so creating an issue is my last option 😞

**Version: 3.3**
**PHP: 7.4**

### Context
I am working with Nexmo SMS API. It only works with **EUR**.  In our app, we are handling money in **USD**.  When an SMS is sent, I need to deduct the SMS price from user balance (which is in USD).

So, I need to convert SMS price from EUR to USD.

### Problem
SMS prices from Nexmo are small values. For example:
`"price": "0.04770000"`
Before converting it to USD using **SwapExchange**, I need to **parse** it, right? 

### Parsing
```php
        $parser = new IntlLocalizedDecimalParser(
            new NumberFormatter('en_150', NumberFormatter::DECIMAL),
            new ISOCurrencies()
        );

        $money =  $parser->parse("0.04770000", new Currency('EUR'));

        return $money->getAmount();
```
It returns **5** 🤷🏻‍♂️

Digging in **parse** method definition, came across following line:

`$decimal = Number::roundMoneyValue($decimal, $subunit, $fractionDigits);`

Tried to find if its **optional** but I guess its not.

Any guideline/help would be appreciated. Thank you 🙏🏼

**Comment by frederikbosch** [comment]
You should use a [`CurrencyList`](http://moneyphp.org/en/stable/features/currencies.html#currencylist) and increase the amount of subunits, by passing 'EUR' => 8 to the currency list.

**Comment by awebartisan** [comment]
Thanks @frederikbosch .
