### ISSUE TITLE
MoneyParser::parse $forceCurrency parameter

### ISSUE THREAD

**Issue by daniser** [moneyphp/money#602]
If I'm parsing money using interface without knowing its actual implementation, there's a risk that this implementation would be, for example, DecimalMoneyParser, which require second parameter to be defined (or otherwise it just throws an exception).

On the other hand, if I pass that second parameter to other implementations, which actually get currency from parsed string, it overrides that currency. I'm finding this highly illogical.

Is there a sense to change that second parameter to $fallbackCurrency? Then it will not override parsed currency (if it is actually parsed).

**Comment by frederikbosch** [comment]
@sagikazarmark I think this is a fair remark. When **$force**Currency is passed, it should be forced. Would you agree on this?
