### ISSUE TITLE
Suggestion: add alternative implementations of Martin Fowler's pattern from other languages

### ISSUE THREAD

**Issue by frolovdev** [moneyphp/money#603]
Hi, first of all, thanks for your great work guys! I appreciate it, and I was inspired by your library and your design decisions and write my implementation of this pattern with JavaScript.

So, what about adding a section with libraries from other languages? (I can help with a pull request)
Something like:

- Java [Moneta](https://github.com/JavaMoney/jsr354-ri)
- JavaScript [easymoney](https://github.com/frolovdev/easymoney)
- Go [go-money](https://github.com/Rhymond/go-money)

**Comment by frederikbosch** [comment]
Please create a PR for this.
