### ISSUE TITLE
Please change link on official docs

### ISSUE THREAD

**Issue by hsm2k3** [moneyphp/money#614]
The link on the docs is broken.
http://blog.verraes.net/2011/04/fowler-money-pattern-in-php/

This link works, I believe it's the same content. 
https://verraes.net/2011/04/fowler-money-pattern-in-php/

**Comment by sagikazarmark** [comment]
Can you point me to where you found that link? A quick search in the repo does not have any results.

**Comment by hsm2k3** [comment]
Sorry, I was looking on the website http://moneyphp.org/en/stable/ for the docs. That's where I found the bad link.

**Comment by garak** [comment]
The wrong link is still there

**Comment by sagikazarmark** [comment]
Fixed
