### ISSUE TITLE
Serialization of Money class

### ISSUE THREAD

**Issue by Ferikl** [moneyphp/money#616]
Hi guys! thanks so much for great package!
I am using it a lot and found small inconvenience: 
JSON serialization create next object:
```
{
    "amount": "4000",
    "currency": "USD"
}
```
as you can see "amount" field is a string

Can you please change serialization strategy to make "amount" integer?
Thanks!

**Comment by frederikbosch** [comment]
This is because we support integers greater than PHP's maximum integer. In order to be able to do that, it must be denoted as a string.
