### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by peterdevpl** [moneyphp/money#619]
PHP 8 is being released today. So far it's not possible to run full test suite for MoneyPHP on PHP 8. I've identified following issues:
* `cache/taggable-cache` is unavailable for PHP 8, looks like there's a read-only repo
* PHPUnit 9 is required, which forces dropping support for PHPUnit 5, and this forces dropping PHP 5.6 (see https://phpunit.de/supported-versions.html)
* waiting for an update of `florianv/swap`

As dropping PHP 5.6 is required, I believe this ticket will be related to #393

**Comment by Ocramius** [comment]
Overall, dropping PHP <7.3 is acceptable: 7.2 is EOL (also from security updates) [since last year](https://www.php.net/supported-versions.php), so a bump to `^7.3 || ^8.0` is acceptable, and would also fix #633

**Comment by frederikbosch** [comment]
You can use the latest version 3. Very recently I made it compatible.
