### ISSUE TITLE
DecimalMoneyFormatter How to show comma seperator for amount in thousands

### ISSUE THREAD

**Issue by rstmsn** [moneyphp/money#628]
Is there an option for the DecimalMoneyFormatter object to add commas to amounts in the thousands?

eg 3000.00 is displayed as 3,000.00 ? 

Thanks

**Comment by rojtjo** [comment]
I think this is what you're looking for https://moneyphp.org/en/stable/features/formatting.html#intl-decimal-formatter

**Comment by rstmsn** [comment]
Thanks. Turns out I needed to construct the NumberFormatter as a 'NumberFormatter::CURRENCY'. I didn't realise NumberFormatter was a native object, otherwise I would have referred to the PHP docs!
