### ISSUE TITLE
Format with thousand/million/billion/trillion suffix

### ISSUE THREAD

**Issue by 4n70w4** [moneyphp/money#652]
Hi!

I did not find in the documentation whether such formatting can be done.

For example:

`1k` instead `1 000` or `1 тыс.` instead `1 000` if ru_RU locale.
`1.1k` instead `1 100` or `1,1 тыс.` instead `1 100` if ru_RU locale.

`1m` instead `1 000  000` or `1 млн` instead `1 000 000` if ru_RU locale.
`1.5m` instead `1 500  000` or `1,5 млн` instead `1 500 000` if ru_RU locale.
...etc

**Comment by frederikbosch** [comment]
@4n70w4 This is dependent on the availability of such formatting in the `intl` extension. See [the docs on the IntlMoneyFormatter](https://moneyphp.org/en/stable/features/formatting.html#intl-money-formatter). You will have to experiment with this yourself. I cannot answer this question for every locale.
