### ISSUE TITLE
Magic method RUB, USD, etc does not tell about possible InvalidArgumentException

### ISSUE THREAD

**Issue by Legion112** [moneyphp/money#657]
The magic methods 
```
 * @method static Money AED(string|int $amount)
 * @method static Money ALL(string|int $amount)
 * @method static Money AMD(string|int $amount)
 * @method static Money ANG(string|int $amount)
 * @method static Money AOA(string|int $amount)
 * @method static Money ARS(string|int $amount)
 * @method static Money AUD(string|int $amount)
 * @method static Money AWG(string|int $amount)
 * @method static Money AZN(string|int $amount)
 * @method static Money BAM(string|int $amount)
 * @method static Money BBD(string|int $amount)
 * @method static Money BDT(string|int $amount)
 * @method static Money BGN(string|int $amount)
```
Do not tell the static analyzer about the possible exception that might be thrown. 
I recommend rewiring them to the real method with throws doc block.

**Comment by BonBonSlick** [comment]
true, with ref that 
// string is accepted if fractional part is zero
$fiver = new Money('500.00', new Currency('USD'));

looking how to add what is left after . point delimeter

**Comment by frederikbosch** [comment]
>  recommend rewiring them to the real method with throws doc block.

How would that look like?

**Comment by Legion112** [comment]
> How would that look like?
Writing method and putting there php throw doc block?

**Comment by frederikbosch** [comment]
Nothing holds you from using the real constructor `new Money(100, new Currency('EUR'))` or creating your own factory method/class that adds an @throws. These factory methods are [created for IDE and DX purposes](https://github.com/moneyphp/money/pull/469). While I was never in favor of this, I believe Mark was right that it was an OK comprise. This issue won't be fixed.
