### ISSUE TITLE
Format without money symbol

### ISSUE THREAD

**Issue by kephren226** [moneyphp/money#659]
In there a way to format or print the format result witout the currency symbol 
I'm using this new Money(10000, new Currency('XOF'))

and ai want to print this 10 000 instead of that 10 000 F CFA

**Comment by kslimani** [comment]
Maybe with [Intl Decimal](https://www.moneyphp.org/en/stable/features/formatting.html#intl-decimal-formatter) or  [Decimal ](https://www.moneyphp.org/en/stable/features/formatting.html#decimal-formatter) formatter.

**Comment by kephren226** [comment]
> Maybe with [Intl Decimal](https://www.moneyphp.org/en/stable/features/formatting.html#intl-decimal-formatter) or [Decimal ](https://www.moneyphp.org/en/stable/features/formatting.html#decimal-formatter) formatter.

Thanks 
didn't see that
