### ISSUE TITLE
Rector rule for upgrading to 4.0

### ISSUE THREAD

**Issue by Wirone** [moneyphp/money#667]
Lately I've created [Rector issue](rectorphp/rector/issues/6588) for creating rule that would allow to refactor codebase and migrate `moneyphp/money` from 3.* to 4.*. But on the other hand maybe it would be good thing if this library provided such rules - having library in the Composer dependencies would mean that Rector rules are there too and can be used for automatic refactoring. And library maintainers know the best what needs to be changed between versions 🙂 

What do you think?

**Comment by sstok** [comment]
It should properly be kept as a separate package, which could be part of this organization (for better findability).

**Comment by frederikbosch** [comment]
If someone wants to contribute this, we could embed it in this Github org. Please contact us if you are interested. But for now, I do not want to add another tool in this codebase.

**Comment by Wirone** [comment]
FYI: I've created [`codito/rector-money`](https://packagist.org/packages/codito/rector-money) that handles automatic refactor using Rector so it can quickly make code compatible with `moneyphp/money` v4 🙂 It's tagged as `1.0.0-RC1` as of now, but it's considered as stable and working, I just wanted to get some feedback before tagging stable release.
