### ISSUE TITLE
Rounding up / down as an operation?

### ISSUE THREAD

**Issue by tyteen4a03** [moneyphp/money#681]
How do I round a price up/down to the nearest integer as an operation? `round()` seems to be a function but it's private so I can't use it in userland.

**Comment by frederikbosch** [comment]
You pass the rounding mode with operations like `multiply` and `divide`. Further, [see](https://www.moneyphp.org/en/stable/features/operation.html#rounding-modes).

```php
$money->multiply(1.2, Money::ROUND_HALF_UP);
```
