### ISSUE TITLE
Change return type of getAmount to `numeric-string`

### ISSUE THREAD

**Issue by BackEndTea** [moneyphp/money#683]
We are dealing with some legacy code where we are introducing MoneyPHP. 
At some points we are going back to the underlying amount, instead of money PHP, and we are doing calculations with it.

Right now we are getting some errors of our SA tooling about unallowed binary operations with the result from `getAmount`.

I'd be willing to provide a PR to change this if that is something that you'd consider. (Preferably at the 3.x branch, as that is the one we are still using atm)

**Comment by frederikbosch** [comment]
I think this is something you should solve in your own code.
