### ISSUE TITLE
Question about Japanese Yen cent amount

### ISSUE THREAD

**Issue by driesvints** [moneyphp/money#684]
I just discovered that Japanese Yen requires three number of cents rather than the regular two of other currencies.

Meaning the following:

```php
new Money(12100, 'JPY');
```

Will result in `¥12,100` rather than the expected `¥121,00`.

This is an extremely important gotcha in my eyes. I might have glanced over it in the docs? Also, I realise that this probably is due to my lack of knowing how much cents there are for each currency but I was wondering if moneyphp helps with this somehow? If not, is there a complete list somewhere with all supported currencies and how many cents they have (or a built-in API)?

Thanks for any help! 🙏

**Comment by gmponos** [comment]
I think JPY does not have cents.

The comma separator there is for thousands.

**Comment by gmponos** [comment]
Also from the WIKI above 

> The sen and the rin were eventually taken out of circulation at the end of 1953

**Comment by driesvints** [comment]
I see. Thank you for responding @gmponos & @UlrichEckhardt. I'm wondering what the correct way to handle this in MoneyPHP is? Should we always rely on the value of `minorUnit`?

**Comment by driesvints** [comment]
I'm btw working with Paddle which returns values as floats/strings.

**Comment by driesvints** [comment]
I've got something working:

```
// With $plan being an object with a price (string) and currency (string)
// Example: "121.0" & "JPY"
// Other example: "12.24" & "EUR"
// This is how Paddle gives us these.

$currency = new Currency($plan->currency);
$subUnit = (new ISOCurrencies)->subunitFor($currency);
$factor = 1;

for ($i = 0; $i < $subUnit; $i++) {
    $factor *= 10;
}

$amount = bcmul((string) $plan->price, (string) $factor);

$money = new Money($amount, $currency);

$numberFormatter = new NumberFormatter('en', NumberFormatter::CURRENCY);
$moneyFormatter = new IntlMoneyFormatter($numberFormatter, new ISOCurrencies());

return $moneyFormatter->format($money);
```

And that returns `¥121` and `€12.24` properly. Dirty but working 😅

**Comment by driesvints** [comment]
Does anyone here have any thoughts about the above code? Does that seem okay to you all? Maybe @frederikbosch?

**Comment by frederikbosch** [comment]
@driesvints The number of subunits returned by the `ISOCurrencies` class is based on the list of ISO 4217 currencies as provided by the official ISO Maintenance Agency. It comes from [this package](https://github.com/moneyphp/iso-currencies), also in the moneyphp organization. 

`new Money` expects you to pass the value in the smallest unit but `Money` itself is not aware of the subunit. This is a value that only lives in implementations of the [`Currencies` interface](https://github.com/moneyphp/money/blob/master/src/Currencies.php).

So if you are using `ISOCurrencies` - as @gmponos says - it will return is 0 subunits for JPY, while it returns 2 for EUR. You are free to overwrite this behavior in your implementation of Currencies. It is quite easy actually. The following uses the ISO list but uses a fixed subunits, as parameter of the constructor.

```php
final class FixedSubunitCurrencies implements Currencies 
{
    private Currencies $delegated;
    private int $subunits;

    public function __construct(Currencies $delegated, int $subunits)
    {
         $this->delegated = $delegated;
         $this->subunits = $subunits;
    }

    public function contains(Currency $currency): bool
    {
          return $this->delegated->contains($currency);
    }

    public function subunitFor(Currency $currency): int
    {
         return $this->subunits;
    }

    public function getIterator(): Traversable
    {
          return $this->delegated->getIterator();
    }
}

$currencies = new FixedSubunitCurrencies(new ISOCurrencies(), 2);
$currencies->subunitFor(); // always 2
```

Of course it all depends what you want to achieve, but I think you should be able to solve this issue without the factor calculation and an additional `bcmul` call.

**Comment by driesvints** [comment]
@frederikbosch thank you for those insights! But this is more of an issue where I have the values already formatted up front (from Paddle) and need to convert them to the proper integer value before instantiating the Money object. So I think I still need to do calculations.
