### ISSUE TITLE
Deprecated: Return type of Money\Currencies\ISOCurrencies::getIterator() should either be compatible with IteratorAggregate::getIterator()

### ISSUE THREAD

**Issue by seyfcom** [moneyphp/money#692]
Hi 
I got this error, any idea?
Thanks

> Deprecated: Return type of Money\Currencies\ISOCurrencies::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in S:\wamp64\www\Camt_Converter\vendor\moneyphp\money\src\Currencies\ISOCurrencies.php on line 64
> 
> Deprecated: Return type of Money\Currency::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in S:\wamp64\www\Camt_Converter\vendor\moneyphp\money\src\Currency.php on line 86
> 
> Deprecated: Return type of Money\Money::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in S:\wamp64\www\Camt_Converter\vendor\moneyphp\money\src\Money.php on line 521

PHP 8.0.1
Laragon install on Windows 10

**Comment by frederikbosch** [comment]
See v4.0.4.
