### ISSUE TITLE
Deprecation notice on Money\Currencies\ISOCurrencies::getIterator() with PHP 8.1

### ISSUE THREAD

**Issue by kissifrot** [moneyphp/money#693]
Hello,

I'm getting the following deprecation notice with PHP 8.1 (8.1.6 GA precisely):

`Deprecated: Return type of Money\Currencies\ISOCurrencies::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

Looks like some fixes were already done is master branch, maybe a release would be appropriate? :slightly_smiling_face:

**Comment by frederikbosch** [comment]
See v4.0.4.
