### ISSUE TITLE
ISOCurrencies::getIterator needs return type to be specified

### ISSUE THREAD

**Issue by OneHatRepo** [moneyphp/money#709]
Getting this error in PHP 8.1.10:
`"Return type of Money\Currencies\ISOCurrencies::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [in APP/vendor/moneyphp/money/src/Currencies/ISOCurrencies.php, line 62]"`

So line 62 needs to read:
`public function getIterator(): \Traversable`
and the error goes awaay

**Comment by frederikbosch** [comment]
This is not an issue. There is no support for PHP 8.1 for Money v3. However, if you create a PR with the ReturnTypeWillChanged attribute added to the method, I will merge it and create a tag for you.
