### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by rvanlaak** [moneyphp/money#714]
The 8.2 RC phase has started, so for testing sake I've tried upgrading an application. The Money dependency is not supporting PHP 8.2 yet, do we know what needs to be done to add support for PHP 8.2? 

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/2707563/192489995-e9b1bff1-17f3-42b8-a5f8-8bc1b8102cfb.png">

**Comment by BenCavens** [comment]
The phpunit testsuite is running fine on 8.2. 

It seems that phpspec is the only hurdle towards 8.2 support as it currently doesnt support 8.2 yet.
I looked into the phpspec project and it seems that there is currently not much activity. (Many open issues)

**Comment by sagikazarmark** [comment]
I don't feel very comfortable adding 8.2 support without being able to run tests. Let's hope that phpspec adds 8.2 support soon.

**Comment by mbardelmeijer** [comment]
PHP 8.2 support has been added to the phpspec project: https://github.com/phpspec/phpspec/commit/ead440eef8bb7bf89e9f96fe9b7473bd5fa6a335

No release/tag yet, but expect that should follow shortly.

**Comment by frederikbosch** [comment]
Yes!

**Comment by onlime** [comment]
> Yes!

Yes soonish or just a plain 3-character Yes? 😉 Thanks for your efforts!
