### ISSUE TITLE
BCMath is unmaintained

### ISSUE THREAD

**Issue by pevdh** [moneyphp/money#718]
The bcmath extension has not had a maintainer since 2004 [[ref]].
This is currently preventing us from upgrading to 4.0, since our policy prevents us from enabling the bcmath extension.

Would it be possible to make the bcmath extension an optional requirement? I'd be happy to submit a PR.

[ref]: https://github.com/php/php-src/blob/865f2c026ed61e2fdb444b8754322b8decdc1a33/EXTENSIONS#L235

**Comment by arokettu** [comment]
You can declare that bcmath exists in config.platform or install a bcmath polyfill like https://github.com/phpseclib/bcmath_compat

**Comment by frederikbosch** [comment]
Great suggestions @arokettu. But I leave this issue open for ow. I agree with @pevdh, making bcmath required while it is actually unmaintained deserves our attention. Maybe @Ocramius can help so shed us his thoughts on this remark.

**Comment by Ocramius** [comment]
`ext-bcmath` is maintained as part of `php-src`: https://github.com/php/php-src/tree/3fb7198034c0f2ed49eeb71f9757b58aaa26260d/ext/bcmath

It receives regular updates, and is not unmaintained?
