### ISSUE TITLE
PHPDoc issue

### ISSUE THREAD

**Issue by riccardobosini** [moneyphp/money#719]
Good morning, 
I'm writing cause I've the following issue.
I've a project with installed this package [laravel-money](https://github.com/cknow/laravel-money) that abstracts this project.
Let's suppose this code: 
```php
use Money\Currency;

$revenueA = new \Cknow\Money\Money(123, new Currency('EUR'));
$revenueB = new \Cknow\Money\Money(123, new Currency('EUR'));

$revenueTotal = $revenueA->add($revenueB);
```
In my case PHPStorm highlight the last row showing this message: `Expected parameter of type '\Money\Money', '\Cknow\Money\Money|null' provided`. It expects that the parameter passed to the `add` method to be of type `\Money\Money`.

It's annoying cause working with amounts the screen is full of warnings.

Can you please help me about this?
Thanks in advance.

**Comment by agustingomes** [comment]
Hi @riccardobosini 

I stumbled upon this report, and briefly looking at it, it feels you would get more adequate help if you open the issue in the `laravel-money` package, as this particular issue may be originating there.

**Comment by riccardobosini** [comment]
> Hi @riccardobosini
> 
> I stumbled upon this report, and briefly looking at it, it feels you would get more adequate help if you open the issue in the `laravel-money` package, as this particular issue may be originating there.

The following is the warning that shows up. The laravel-money version is `v6.4.0`.
![image](https://user-images.githubusercontent.com/23011509/205270380-4d9d0e77-2764-4bd3-9f58-fcbb29953ef6.png)

**Comment by frederikbosch** [comment]
Sorry, cannot provide support for facades, IDEs and frameworks. No time. Good luck!
