### ISSUE TITLE
PHP 8.2 Release

### ISSUE THREAD

**Issue by rogervila** [moneyphp/money#727]
Hello @frederikbosch,

Now that #724 and #725 are merged, is there anything else needed before releasing a new version supporting PHP 8.2?

If this is not considered a major, it could be released as `v4.0.5`. Otherwise, it would be the first `v5.0.0` release.

Let me know if there is something I can do on my side to help on releasing that new version.

Thank you!

**Comment by frederikbosch** [comment]
I will tag `v4.1.0` after the weekend. By tagging a minor version we leave room to create tags for non-PHP8.2 versions in the 4.0 range. A new major seems not necessary because there has been no backward incompatible change. Support for PHP 8.2 is a feature, and therefore I deem `4.1.0` the best decision.

**Comment by frederikbosch** [comment]
@rogervila, if you have some time, could you have a look at PR #726? I know my colleague @sagikazarmark is mostly working on other libraries and I guess he is not in the opportunity to help. But Mark, if you read this and do have the opportunity, go ahead!

**Comment by frederikbosch** [comment]
Since I am not working that often on this library, I want to have #726 in before tagging 4.1.0. It is almost ready to go.

**Comment by frederikbosch** [comment]
In the latest commit I already prepared `CHANGELOG.md` for the new release, adding all modifications to the library since the latest release.

**Comment by frederikbosch** [comment]
Version [4.1.0](https://github.com/moneyphp/money/releases/tag/v4.1.0) has just been released.
