### ISSUE TITLE
ratioOf works incorrect for currencies with different minor units

### ISSUE THREAD

**Issue by smelesh** [moneyphp/money#732]
`ratioOf` assumes that the given amount has the same minor units as the current amount, otherwise the result is incorrect:

```php
Money::EUR(20_00)->ratioOf(Money::JPY(1000))
```
expected: 0.02
actual: 2.00

Probably `ratioOf` should throw an exception when currencies don't match to avoid unexpected results.

**Comment by peterdevpl** [comment]
Yes, it makes sense for `ratioOf` to throw an exception on unmatched currencies, especially that `mod` already does that. I made a PR.
