### ISSUE TITLE
Bring back support for VEF currency (at least for 3.x)

### ISSUE THREAD

**Issue by Wirone** [moneyphp/money#733]
We have large PHP application that uses Money library. Currencies may be used in the code itself, but also can be provided from custom fields in the database, that are defined by users and in short: we can't be sure about actual currency usage without thorough research. Currently we have frozen `3.2.1` release, because [`3.3.0` removed `VEF` currency, and added `VES` instead](https://github.com/moneyphp/money/pull/581). I believe it's a breaking change and it should NOT be introduced in minor release.

It's a problem for us because we're working hard on migrating to PHP8 and in terms of PHP's `IteratorAggregate::getIterator()` changes Money library made required changes in `3.3.3` - we need update to this version, but at the same time we can't because of missing `VEF` currency.

Please bring back `VEF` currency and release 3.3.4 with it, so we can update to PHP8-compatible version 🙏 🙂 

CC: @sagikazarmark

**Comment by Wirone** [comment]
FYI: [Twitter thread about supporting historical currencies](https://twitter.com/_Codito_/status/1623648729637978115).

**Comment by frederikbosch** [comment]
You can create your own implementation of `Currencies`. Nothing is stopping you from doing that. This library supports the latest `ISOCurrencies`.
