### ISSUE TITLE
not working for php version 8.2.1

### ISSUE THREAD

**Issue by peeter2** [moneyphp/money#736]
not working on the latest php version

**Comment by frederikbosch** [comment]
Why not?

**Comment by peeter2** [comment]
Because it requires older versions of PHP. 
"require": {
        "php": "~8.0.0 || ~8.1.0 || ~8.2.0",


too bad I have the latest version of php :(

**Comment by frederikbosch** [comment]
That should work: ~8.2.0 means >= 8.2.0 && < 8.3.0.

**Comment by hyphen81** [comment]
For anyone else that might run into this problem as well. I was getting this error when trying to install the package and it also said I was missing the bcmath extension, which is on my docker environment. I ran the below command, ignoring the bcmath 
extension, which allowed the package to be installed and appears to be working as expected.

composer require pelmered/filament-money-field --ignore-platform-req=ext-bcmath
