### ISSUE TITLE
Missing `SLE` currency

### ISSUE THREAD

**Issue by LVoogd** [moneyphp/money#737]
As of 1 July 2022, the ISO 4217 code is `SLE` due to a redenomination of the old leone (`SLL`).

This currency isn't supported in this library yet. Are there any plans to support `SLE` in the future?

https://en.wikipedia.org/wiki/Sierra_Leonean_leone

**Comment by frederikbosch** [comment]
See PR #739, will merge after the weekend, if I not forget.
