### ISSUE TITLE
SwapExchange does not work with small floating point numbers

### ISSUE THREAD

**Issue by martiis** [moneyphp/money#743]
If [SwapExchange](https://github.com/moneyphp/money/blob/master/src/Exchange/SwapExchange.php#L34) would return a rate like `0.0000550000` PHP will display as `5.5E-5` thus simply casting to string will result to `"5.5E-5"`. Then [Converter](https://github.com/moneyphp/money/blob/master/src/Converter.php#L66) passes ratio to the Number class which will throw [invalid fractional part exception](https://github.com/moneyphp/money/blob/4c872e4fae123167ae206ea3cd07c38ff4d07c4f/src/Number.php#L249).

Although this issue has been handled in [ExchangerExchange](https://github.com/moneyphp/money/blob/master/src/Exchange/ExchangerExchange.php#L43) by using `sprintf` :)

**Comment by frederikbosch** [comment]
If you can make a PR with the `sprintf` solution, including a test, would be great.
