### ISSUE TITLE
PHPUnit comparator breaks under PHPUnit 10/comparator 5

### ISSUE THREAD

**Issue by Firehed** [moneyphp/money#745]
There was a breaking change going from `sebastian/comparitor:4` to `5`, which by default you'll pull in updating to PHPUnit 10.

At a glance, there are two adjustments:

- don't call `parent::construct`
- add `: bool` return type to `accepts`

I think the latter is fine for forward compatibility, but the former may require some hacking to get around the [loss of constructor](https://github.com/sebastianbergmann/comparator/commit/bf22fc1b035ecf7a4e989e2a5ace1ceb06dd9bcf#diff-715109ab56f1e98d6b0529699f097a1ce0841e3437fc7bb3a4bc771bac1f1db5)

I'll take a quick attempt at a PR to address this.

**Comment by frederikbosch** [comment]
Fixed by #784.
