### ISSUE TITLE
numberFormat refuses to use comma as decimal separator.

### ISSUE THREAD

**Issue by getJv** [moneyphp/money#752]
Hello all,

The snippet below is returning "€ 1,234,567.89", stead of "€ 1.234.567,89".

I already tried a different number of configs but with no success:
 - locale as it_IT or nl_NL
 - Set the system [locale to Berlin](https://wiki.alpinelinux.org/wiki/Setting_the_timezone)in the Alpine Container
 - different kinds of patterns, etc

Do any of you know what should be done to use commas as decimal operator with this lib?

```php
   $money = new Money('123456789', new Currency('EUR'));
   $currencies = new ISOCurrencies();
   $numberFormatter = new \NumberFormatter('de_DE', \NumberFormatter::CURRENCY);
   $numberFormatter->setPattern('¤ #,##0.###'); //#.##0,00
   $moneyFormatter = new IntlMoneyFormatter($numberFormatter, $currencies);
   echo $moneyFormatter->format($money);
```

**Comment by frederikbosch** [comment]
Did you create your container with the `icu-data-full`  package installed before compiling PHP?

**Comment by getJv** [comment]
Thank you so much for your help @frederikbosch, that was precisely missing. now my intl is working well.

snipped from my docker file 
```bash
#... 
RUN apk add --no-cache icu-dev gnu-libiconv gettext tzdata icu-data-full \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-enable intl
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so
#...
```
