### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by cs278** [moneyphp/money#756]
The documentation at https://www.moneyphp.org/en/stable/ does not appear to have been updated since 2020.

For example this commit https://github.com/moneyphp/money/commit/512333ef834bd77f76e865a30eb5963d480e2ed7 isn't reflected in the live docs: https://www.moneyphp.org/en/stable/features/allocation.html

**Comment by Chris53897** [comment]
If i follow the link  "Edit on GitHub"
It links to https://github.com/moneyphp/money/blob/122664c2621a95180a13c1ac81fea1d2ef20781e/doc/index.rst
I guess only the owner of the Homepage can change it.

**Comment by frederikbosch** [comment]
Fixed
