### ISSUE TITLE
"psr/cache" 3 can not be installed because of cache/tag-interop

### ISSUE THREAD

**Issue by Chris53897** [moneyphp/money#776]
"cache/tag-interop" is blocking the installation of "psr/cache" v3
https://packagist.org/packages/cache/tag-interop

I am not sure what exactly needs to be done, to fix it.

**Comment by frederikbosch** [comment]
That's correct. It does not support psr/cache 3.0 yet, see what they have listed at `require` on that page that you just linked to. This is a cache/tag-interop problem.
