### ISSUE TITLE
ISK convert gives wrong amount (x100)

### ISSUE THREAD

**Issue by SteveMave** [moneyphp/money#787]
The conversion of ISK goes wrong somewhere in the convertAgainstCurrencyPair()

`           
 $ratio = Number::fromString($ratio)
            ->base10($subunitDifference)
            ->__toString()
`

the ratio always goes through the base10() here and comes out 100 times bigger than expected

this is the only currency (found so far) where this is the case

ratio goes from "0.006724" to "0.6724", 

I might be missing something

**Comment by frederikbosch** [comment]
This is probably not a bug. [ISK uses a minorUnit of 0.](https://github.com/moneyphp/money/blob/master/resources/currency.php#L482). That has to be taken into account when converting to a currency with subunit 2, e.g. [EUR](https://github.com/moneyphp/money/blob/master/resources/currency.php#L342) or [USD](https://github.com/moneyphp/money/blob/master/resources/currency.php#L1035).
