### ISSUE TITLE
Enhancement:: Allow multiply by float numbers less than 1 

### ISSUE THREAD

**Issue by TAGHREEDAA** [moneyphp/money#791]
I got an issue while trying to multiply by float multiplier less than 1 values 

example:
`$price = (new Money(4320, new Currency('SAR')))->multiply(0.78)->multiply(2);
`
this gives zero result because `0.78 `is not a string

I suggest to modify the multiply function [here ](https://github.com/moneyphp/money/blob/a1daa7daf159b4044e3d0c34c41fe2be5860e850/src/Money.php#L237)

```
public function multiply(float|string $multiplier, int $roundingMode = self::ROUND_HALF_UP): Money
    {
        if (is_int($multiplier) || is_float($multiplier)) {
            $multiplier = (string) $multiplier;
        }

        $product = $this->round(self::$calculator::multiply($this->amount, $multiplier), $roundingMode);

        return new self($product, $this->currency);
    }
```

**Comment by begench993** [comment]
No float :),[ it has been explained before](https://github.com/moneyphp/money/issues/650)
