### ISSUE TITLE
Switch Psalm with PHPStan

### ISSUE THREAD

**Issue by ruudk** [moneyphp/money#798]
Currently, Psalm blocks testing this on PHP 8.4 #796 .

I also wonder why the package uses Psalm, as [PHPStan feels much more alive](https://github.com/phpstan/phpstan-src/pulse/monthly) than [Psalm](https://github.com/vimeo/psalm/pulse/monthly).

**Comment by frederikbosch** [comment]
Why would Psalm be blocking that? I don't see any failed tests because of it.

**Comment by ruudk** [comment]
Because I added `--platform-ignore-reqs=php` to the PR in the meantime.

**Comment by frederikbosch** [comment]
Oh, I did not do a good review then, that's a blocker.

**Comment by frederikbosch** [comment]
It's not a bad idea to switch to PHPStan. The contributions to Psalm are not what it has been, while PHPStan has recently released version 2. There is also no urgency in the project to support PHP 8.4 which stops us at the moment from supporting 8.4. 

So, if anyone would like to contribute the switch, I would love to help. I lack the time at the moment to create the PR myself.

**Comment by ruudk** [comment]
@frederikbosch 🫡 challenge accepted
