### ISSUE TITLE
Bitcoin not supported by stringToUnits()

### ISSUE THREAD

**Issue by thedavidmeister** [moneyphp/money#97]
Because stringToUnits() explicitly expects only 2 trailing decimals, it cannot support Bitcoin and we see "The value could not be parsed as money"

**Comment by josecelano** [comment]
Hi @thedavidmeister maybe this could be interesting for you:

https://github.com/mathiasverraes/money/issues/7#issuecomment-91863422

**Comment by thedavidmeister** [comment]
yeah, that does look interesting. I'm *just* about to roll a release for something I'm working on that uses the current Money setup, so I don't want to start a refactor now. But it's something worth following up as I had to jump through some hoops along the way that I would have expected Money to handle better.

**Comment by frederikbosch** [comment]
The parser in #148 does not support bitcoin. My suggestion would be to close this issue after #148 is merged and leave implementation up to the user. A very simplistic approach could be as follows.

```php
<?php
use Money\Currency;
use Money\Money;
use Money\MoneyParser;

class BitcoinSupportedMoneyParser implements MoneyParser
{
    private $innerParser;

    public function __construct(MoneyParser $innerParser)
    {
        $this->innerParser = $innerParser;
    }

    public function parse($formattedMoney, $forceCurrency = null)
    {
        if (strpos($formattedMoney, "\0xC9\0x83") !== false) {
            // bitcoin parsing here
            return new Money($formattedMoney, new Currency('XBT'));
        } else {
            return $this->innerParser->parse($formattedMoney, $forceCurrency);
        }
    }
}
```

**Comment by frederikbosch** [comment]
@sagikazarmark This one can be closed too

**Comment by sagikazarmark** [comment]
Hm, should we include this in the repo?

**Comment by frederikbosch** [comment]
Why would we want include it? By using the intl parser together with the parser interface, the user has all the possibilities to implement such a bitcoin parser of his own.

If we include this one, what is then the boundary what to include and what not?

**Comment by frederikbosch** [comment]
And if we include a bitcoin parser, we should - by means of consistency - also include a formatter. 

Maybe we avoid getting same questions by including one. I am happy to PR both formatter and parser. Can you let me know what your decision is @sagikazarmark?

**Comment by sagikazarmark** [comment]
Well, it seems bitcoin is a widely requested feature. Further more, it is plain PHP code without any dependencies. Given these two details, I don't think it's a problem to include it.

**Comment by frederikbosch** [comment]
Ok, will PR next week.

**Comment by frederikbosch** [comment]
@josecelano @thedavidmeister Could you please have a look at PR #155? Thanks.

**Comment by frederikbosch** [comment]
Recommitted to master. Who can do a review on the bitcoin parser and formatter? We need someone who deals with this on a regular basis.
